### ISSUE TITLE
depreciated epub:types should generate USAGE not ERROR

### ISSUE THREAD

**Issue by nekennedy** [w3c/epubcheck#1009]
Currently deprecated epub:type elements are generating an error, unknown ones are generating a usage message:

ERROR(OPF-087): ./Documents/Development/Sprints/Jeremy/4_2/9781524761547.epub/OEBPS/Acho_9781524761547_epub3_c01_r1.xhtml(12,57): Property 'list' is not allowed on documents of type 'application/xhtml+xml'.
USAGE(OPF-088): ./Documents/Development/Sprints/Jeremy/4_2/9781524761547.epub/OEBPS/Acho_9781524761547_epub3_c01_r1.xhtml(15,32): Unrecognized property 'chair'.

**Proposal:** either make them the same, or change the deprecated property to USAGE and "Depreciated property 'XXXXX'."

**Comment by rdeltour** [comment]
Thanks @nekennedy for the feedback! 👍

> ERROR(OPF-087): ./Documents/Development/Sprints/Jeremy/4_2/9781524761547.epub/OEBPS/Acho_9781524761547_epub3_c01_r1.xhtml(12,57): Property 'list' is not allowed on documents of type 'application/xhtml+xml'.

In the [latest editor's draft of the Structural Semantics Vocabulary](https://idpf.github.io/epub-vocabs/structure/structure.html) (that will be published in sync with EPUB 3.2), the `"list"` property is defined as **not allowed** in HTML (it is only defined for SMIL documents).

> USAGE(OPF-088): ./Documents/Development/Sprints/Jeremy/4_2/9781524761547.epub/OEBPS/Acho_9781524761547_epub3_c01_r1.xhtml(15,32): Unrecognized property 'chair'.

Yes, this is now [conforming to EPUB 3.2](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-contentdocs-default-vocab), which says:
>> Unprefixed terms that are not part of the [EPUB-SSV] MAY be included, but their use is discouraged.

> deprecated `epub:type` elements are generating an error

I see where you're coming from, when looking at the `list` term… but again, these are special cases which are no longer marked as _deprecated_ but really as _not allowed_. _Deprecated_ terms (e.g. [`"subchapter"`](https://idpf.github.io/epub-vocabs/structure/structure.html#divisions) are now reported as `WARNING`.

See also the discussion in #531 and w3c/publ-epub-revision#1222.

If you think this behavior should be reconsidered it would need to be discussed in the CG, for instance by commenting on w3c/publ-epub-revision#1222.

For now, EPUBCheck's behavior seems to be conforming to the spec (forthcoming 3.2 vocab), so I'm closing the issue as `invalid`. But feel free to keep on discussing here! 😊

**Comment by mattgarrish** [comment]
The general consensus on the call today is that invalid use of epub:type doesn't warrant warning/errors. It serves no particular function beyond pop-up footnotes, so there's no value in forcing people to fix any misuses.

I misunderstood the issue a bit, as I thought this was about the terms we had marked recently as deprecated, not about the terms that are only intended for media overlays, but my impression is that the group wants them all treated the same way as usage messages.

**Comment by rdeltour** [comment]
> The general consensus on the call today is that invalid use of epub:type doesn't warrant warning/errors.

Ah, sorry I wasn't on the call… So everything `epub:type` related becomes a `USAGE`, right?

What happen to generic errors like an undeclared prefix or invalid prefix declaration, they would still be reported as errors, correct?

**Comment by mattgarrish** [comment]
> What happen to generic errors like an undeclared prefix or invalid prefix declaration, they would still be reported as errors, correct?

I don't think we need to go that deep into changing severity, no. If you're using those mechanisms, then you'll likely want the messages.

This issue generally focuses around not causing validation problems for the unprefixed terms in epub:type.

Correct @dauwhe @RachelComerford @TzviyaSiegman ?

**Comment by rdeltour** [comment]
would the deprecated properties other than `epub:type` (e.g. the deprecated records in `link` `rel` properties) would still be reported as `WARNING`, or do they get the same treatment?
