### ISSUE TITLE
4.2.0-RC: please provide Maven artifact

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#1016]
There have been alpha/RC maven artifacts of EPUBCheck in the past: https://mvnrepository.com/artifact/org.idpf/epubcheck

So it would be great to have one for 4.2.0-RC as well.

**Comment by rdeltour** [comment]
Sure. Note there's already [a Maven artifact for 4.2.0-beta](https://search.maven.org/artifact/org.w3c/epubcheck/4.2.0-beta/jar), so everything is in place already 🙂

**Comment by tofi86** [comment]
awesome. not sure why I didn't found it in first place... and why it didn't sync to mvnrepository.com 🤷‍♂️

**Comment by tofi86** [comment]
> not sure why I didn't found it in first place... and why it didn't sync to mvnrepository.com

my fault. the group id changed! 🤦‍♂️ 

old: `org.idpf:epubcheck`
new: `org.w3c:epubcheck`
