### ISSUE TITLE
Validate exits with no error/exception in Aws Lambda

### ISSUE THREAD

**Issue by ioannist** [w3c/epubcheck#1020]
I have no problem running epubCheck.validate in my local Windows machine. However, when I deploy the code to AWS Lambda (Linux based), the Java process exits without an error or exception, after printing "here", inside the put statement!!!

com.adobe.epubcheck.ocf.OCFChecker
```
Predicate<ValidationContext> p = Predicates.and(path(OCFData.containerEntry), version(EPUBVersion.VERSION_2));
System.out.println("here");
builder.put(p, XMLValidators.CONTAINER_20_RNG);
```

I had to break the initialization of validatorMap into its components and move it inside a static block in order to track where the code gets crashes. I also wrap the above code in try-catch block, but nothing gets thrown. Guava is 24.0-android (older version excluded).

Any ideas?

**Comment by tofi86** [comment]
What's the Java version you're running on your AWS machine? And what's the vendor? Is it Oracle JDK? Or OpenJDK?

**Comment by ioannist** [comment]
Ok, solved. This was my fault. The lambda had a short timeout and and cloudwatch was not catching the timeout error. Not sure why, but I should have give it more time to complete.

Btw, if anybody else stumbles into this
com/google/common/base/MoreObjects: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects

Just make sure you are excluding any old versions of Guava in maven.

**Comment by ioannist** [comment]
While digging around the code i noticed that a lot of exceptions were being eaten, so I had to print some of them. That might have been the case with the above exception too, but I don't remember 100%.

**Comment by nelliemckesson** [comment]
(Sorry to hijack this thread) @ioannist sounds like you successfully got an aws lambda implementation of epubcheck up and running? I need to do something similar - would love it if you could email me to chat about that -- nellie@hederis.com
