### ISSUE TITLE
Testing Tools for EPUBCheck

### ISSUE THREAD

**Issue by wareid** [w3c/epubcheck#1023]
I have created a simple script for running a folder of files through EPUBCheck and outputting results in a single text file. 

https://github.com/wareid/EPUB3-tests/tree/master/EPUBCheck%20Testing%20Tools

Would this be worthwhile including in the EPUBCheck repo for potential testers? Also, please let me know if there's other tools or changes I can make to improve this :). My personal version runs the same files against 2 versions of EPUBCheck for comparison.

**Comment by rdeltour** [comment]
Hi @wareid, cool, thanks for sharing!

I'm a bit ambivalent about adding this to the core repo however. I appreciate it can be (very) useful to others, but it will –sooner or later– lead to maintenance work or feature requests.

Maybe this is better left in its own repo, and we can add a link to our ["Third party tools" page](https://github.com/w3c/epubcheck/wiki/GUI) (currently in the wiki, and primarily about GUIs, but we can change that)?

**Comment by rdeltour** [comment]
(see also #996, where we're considering moving a third-party reporting tool to its own repo)

**Comment by wareid** [comment]
Totally fine leaving it in my repo and just linking to it. And if there's any changes people can log issues on it there or here!

**Comment by rdeltour** [comment]
I just created a new "Other tools" section to our third-party apps list, and added EPUB3-tests there. This list will be ultimately be documented on EPUBCheck’s website, when we have one 😊
Thanks again @wareid for the tool!
