### ISSUE TITLE
Report trailing whitespace in mimetype file

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1028]
Epubcheck reports newlines at the end of the mimetype file as being in error, but is silent if there is only trailing whitespace.

We should be consistent and report any whitespace in the file, which is what the wording changes in https://github.com/w3c/publ-epub-revision/issues/1206#issuecomment-476339458 will make even more explicit.

**Comment by rdeltour** [comment]
Do we need to do this for both EPUB 2 and 3, or just 3?

**Comment by mattgarrish** [comment]
2 and 3. The wording in 2 was maybe even clearer in this regard, although in a parenthetical kind of way:

> The first file in the ZIP Container MUST be a file by the ASCII name of ‘mimetype’ which holds the MIME type for the ZIP Container (i.e., “application/epub+zip” as an ASCII string; no padding, white-space or case change).

**Comment by rdeltour** [comment]
thanks for the confirmation (and sorry I haven't looked up the spec, I was momentarily AFK on my phone 😄 )

**Comment by rdeltour** [comment]
Fixed in #1030
