### ISSUE TITLE
Message OPF-054 lists duplicate source content

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#1040]
```
ERROR | OPF-054 | /OEBPS/content.opf (line 10, col 35)
Date value 'May 21, 2011' is not valid as per http://www.w3.org/TR/NOTE-datetime:[For input string: "May 21, 2011"] is not an integer.
```

Source message is:
```
Date value '%1$s' is not valid as per http://www.w3.org/TR/NOTE-datetime:%2$s.
```

The following would be a better message:

```
Date value 'May 21, 2011' is not valid as per http://www.w3.org/TR/NOTE-datetime: is not an integer.
```

Or even better if it's doable to strip the parts in brackets:
```
Date value 'May 21, 2011' is not an integer. Invalid date as per http://www.w3.org/TR/NOTE-datetime

Date value '%1$s' %2$s. Invalid as per http://www.w3.org/TR/NOTE-datetime
```

Bot for that, other errors for OPF-054 must be checked first...

**Comment by rdeltour** [comment]
I had a fresh look at this issue: the extra message (the parts in square brackets) comes from an exception message, so it cannot easily be fixed; there might be some cases where keeping the whole message makes more sense.

Also, this comes from quite old data parsing code, which could probably be replaced now by standard Java classes from the `java.time` package.

I'm closing as won't fix (not worth the effort for some old code that should be refactored).
