### ISSUE TITLE
role "doc-endnote" not allowed on "li" element

### ISSUE THREAD

**Issue by thiagoeec** [w3c/epubcheck#1041]
Hi everyone.

Acording to the [Epub Type to ARIA Role Authoring Guide](https://idpf.github.io/epub-guides/epub-aria-authoring/), the "doc-endnote" should be used on "li" elements (or inside a "div" with "list" role).

But when I tried the [Example 17](https://www.w3.org/TR/dpub-aria-1.0/#doc-endnote) in the specfications, I got this error:

```
ERROR(RSC-005): Notas.xhtml(13,88): Error while parsing file: value of attribute "role" is invalid; must be equal to "listitem", "menuitem", "menuitemcheckbox", "menuitemradio", "none", "option", "presentation", "radio", "separator", "tab" or "treeitem"
```

Is this a bug?

**Comment by rdeltour** [comment]
I could reproduce. Apparently the role is rejected on `li` children of `ol`, but accepted on `li` children of `ul`, which indeed looks like a bug.

I'll submit a PR to the upstream HTML schemas, and will port the fix to the next version.

Thanks for the report!

**Comment by rdeltour** [comment]
> I'll submit a PR to the upstream HTML schemas

Done in validator/validator#794

**Comment by flittle8** [comment]
@rdeltour I'm getting this error as well, and I'm using the epubcheck v1.9.1.

**Comment by rdeltour** [comment]
FYI, this has now been released in EPUBCheck v4.2.1!

**Comment by flittle8** [comment]
@rdeltour is this update command line only? when I attempt to update via the app it says there are no updates. cheers

**Comment by rdeltour** [comment]
> @rdeltour is this update command line only? when I attempt to update via the app it says there are no updates. cheers

Yes, the “official” EPUBCheck project is command line only. By “the app” i'm guessing you're talking about [pagina's EPUB-Checker](https://www.pagina.gmbh/produkte/epub-checker/); this is a separate project volunteered by @tofi86 for pagina GmbH. Usually they're pretty fast in releasing an update; you can track the project or file specific issues on [their GitHub repository](https://github.com/paginagmbh/EPUB-Checker).

**Comment by tofi86** [comment]
I'll try to release an update of "pagina EPUB-Checker" this evening or tomorrow.

**Comment by flittle8** [comment]
@tofi86 awesome, thank you!

**Comment by tofi86** [comment]
"pagina EPUB-Checker" version 1.9.2 has just been released: https://twitter.com/paginagmbh/status/1130946567698112519
