### ISSUE TITLE
alue of attribute "role" is invalid

### ISSUE THREAD

**Issue by shashikumar1** [w3c/epubcheck#1043]
We are now getting below error. However the role is valid based on instruction.
<body epub:type="cover" role="doc-cover">
<div class="figure_nomargin figure_cover" id="cvi">

ERROR(RSC-005): Ross_9780385541893_epub3_all_r1.epub/OEBPS/xhtml/Ross_9780385541893_epub3_cvi_r1.xhtml(11,42): Error while parsing file: value of attribute "role" is invalid; must be equal to "application", "document", "none" or "presentation"
ERROR(RSC-005): Ross_9780385541893_epub3_all_r1.epub/OEBPS/xhtml/Ross_9780385541893_epub3_ded_r1.xhtml(11,52): Error while parsing file: value of attribute "role" is invalid; must be equal to "application", "document", "none" or "presentation"
ERROR(RSC-001): Ross_9780385541893_epub3_all_r1.epub(-1,-1): File 'OEBPS/xhtml/Ross_9780385541893_epub3_p01_r1.xhtml' could not be found.

**Comment by rdeltour** [comment]
>  Error while parsing file: value of attribute "role" is invalid; must be equal to "application", "document", "none" or "presentation"

This error would be raised when an ARIA role was set on an element to a value that is not allowed for this element, when following the rules defined in the [ARIA in HTML](https://www.w3.org/TR/html-aria/) specification.

Can you please check that your markup conforms to this spec, or give more details or a markup sample?

**Comment by shashikumar1** [comment]
Please refer a below code and suggest if it is wrong.
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<title></title>
<link rel="stylesheet" type="text/css" href="../css/style.css"/>
<meta charset="utf-8" />
</head>
<body epub:type="cover" role="doc-cover">
<div class="figure_nomargin figure_cover" id="cvi">
<div class="squeeze squeeze100">
<img src="../images/cover.jpg" alt="Cover for Know Thyself" class="image"/>
</div>
</div>
</body>
</html>

**Comment by rdeltour** [comment]
The `doc-cover` role is [not allowed on the `body` element](https://www.w3.org/TR/html-aria/#body). See also what the [EPUB Type to ARIA Role Authoring Guide](https://www.w3.org/TR/html-aria/#body) says about it.

I'm closing this issue as invalid, but feel free to keep commenting here or reopen if you think I missed a real issue.
