### ISSUE TITLE
Role is invalid when doc-endnotes attached to list

### ISSUE THREAD

**Issue by flittle8** [w3c/epubcheck#1049]
@rdeltour epubcheck is giving the below error when role="doc-endnotes" is attached to a list. According to the[ Knowledge Base](http://kb.daisy.org/publishing/docs/html/notes.html) this is legit (let me know if that's not the case!).
 I've attached a screenshot of the code and the epubcheck error. Cheers
![epubcheck-error](https://user-images.githubusercontent.com/23460746/58332694-aea52080-7e33-11e9-8670-a2bfa7c1fe9c.png)
![ol-role-docnotes-invalid](https://user-images.githubusercontent.com/23460746/58332695-aea52080-7e33-11e9-9dfd-b6443d560bc4.png)

**Comment by mattgarrish** [comment]
Epubcheck is reporting the error correctly. I've corrected the example in the KB to place the endnotes role on the section tag.

If you ever run into a conflict like this, you can always double-check which is right in the [ARIA in HTML document](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties), as it provides the element mappings.
