### ISSUE TITLE
Official packages  for Debian

### ISSUE THREAD

**Issue by aurora-of-earth** [w3c/epubcheck#1051]
Provide official Debian packages and upload them to the Debian's main repository.
The GitHub release versions is way ahead of even the Debian Experimental repos.

**Comment by tofi86** [comment]
ping @ezhukov

**Comment by ezhukov** [comment]
https://tracker.debian.org/pkg/epubcheck
Here you can find the information about Epubcheck Debian packages. Next Debian release (Debian 10) will contain epubcheck version 4.1.0.
Epubcheck version 4.2.1 Debian package can later be provided via backports repository.
