### ISSUE TITLE
[HTM-010] reports the filename only in some cases but not all

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#1052]
I'm forwarding an issue reported by a german EPUBCheck user:

`USAGE(HTM-010)` reports the filename only in some cases but not all.

You can test it with this public domain ebook: https://www.mobileread.com/forums/attachment.php?attachmentid=152446&d=1476794027 (EdithNesbit-TheWouldBeGoods--illus-v2.epub)

```
java -jar epubcheck.jar -u EdithNesbit-TheWouldBeGoods--illus-v2.epub
```

reports

```
USAGE(HTM-010): EdithNesbit-TheWouldBeGoods--illus-v2.epub(21,191): Namespace uri 'http://www.w3.org/1999/xlink' was found.
...
...
USAGE(HTM-010): EdithNesbit-TheWouldBeGoods--illus-v2.epub/OEBPS/Text/cover.xhtml(21,191): Namespace uri 'http://www.w3.org/1999/xlink' was found.
```

The user expects to find a filename for the first USAGE message as well.

**Comment by rdeltour** [comment]
Closing this, as HTM-010 is no longer reported.
