### ISSUE TITLE
Updated some untranslated zh-TW messages

### ISSUE THREAD

**Issue by davidmaxlee** [w3c/epubcheck#1054]
@tofi86 
Hi Tobias, I just finished the remaining untranslated messages for Traditional Chinese / zh-TW. Take your time to have them integrated in the next release. Thanks!

**Comment by rdeltour** [comment]
Great, thank you @davidmaxlee!

**Comment by davidmaxlee** [comment]
Not at all. Thank you for sharing this tool @rdeltour and all.
