### ISSUE TITLE
aria-dpub-role-fallback now being reported in EPUBCheck 4.2.2

### ISSUE THREAD

**Issue by clapierre** [w3c/epubcheck#1062]
I am not sure this is an error or not but the link to the DAISY KB is missing at any event.

Moderate: aria-dpub-role-fallback
`<span xmlns="http://www.w3.org/1999/xhtml" class="sup" id="fnn1" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="noteref" role="doc-noteref"><a href="#fn1"><span title="Reference number. "></span>1</a></span>
`
Element’s implicit ARIA role is not a good fallback for the (unsupported) role
Learn more about: (no specific entry)

Which looks like the issue is that this should be on a <a> not a <span>  right?  But linking to KB goes nowhere and description of error is misleading as well.

**Comment by rdeltour** [comment]
I guess this issue was intended to be reported on [daisy/ace](https://github.com/daisy/ace)?

**Comment by clapierre** [comment]
Sorry about that, moving this over now.
