### ISSUE TITLE
aria-hidden-focus reported now in EPUBCheck 4.2.2

### ISSUE THREAD

**Issue by clapierre** [w3c/epubcheck#1063]
I got this error today but the description of the error and linking to the KB is not helpful.

```
<p aria-hidden="true" epub:type="title" class="parttitle" id="part6"><a href="../Text/contents.xhtml#part6">RUPTURE OF RELATIONAL BONDS</a></p>
<h2 epub:type="title" class="parttitle1"><span class="sr-only">Rupture of Relational Bonds, </span>Violence, Affairs, and Divorce</h2>
```

Description from ACE:
Focusable content should have tabindex='-1' or be removed from the DOM
Learn more about: (no specific entry)

Not sure why they are trying to hide this link from the SR but then speak that same content minus the linkage.  Very odd, will discuss this with the publisher but in any event is there anything to be done about the description and linkage to the KB?

**Comment by rdeltour** [comment]
I guess this issue was intended to be reported on [daisy/ace](https://github.com/daisy/ace)?

**Comment by clapierre** [comment]
Ugg. sorry Romain, my bad. will move it over
