### ISSUE TITLE
Unable to open file with Unicode characters in name

### ISSUE THREAD

**Issue by spajak** [w3c/epubcheck#1064]
Command:
```
java -jar "d:\Applications\tools\epubcheck\epubcheck.jar" ".\release\Mały Książę - Antoine de Saint-Exupéry.epub"
```
Tells me:
```
File not found: './release/Mały Książę - Antoine de Saint-Exupéry.epub'
```
Whereas:
```
ls ".\release\Mały Książę - Antoine de Saint-Exupéry.epub"
...
05.08.2019    01:58        1441484 Mały Książę - Antoine de Saint-Exupéry.epub
```
Please fix. We have 2019..

`EPUBCheck v4.2.2 / Windows 10 / java version "1.8.0_211"`

**Comment by laudrain** [comment]
@spajak looks like an operating system issue.
No problem on Mac OS with latest version of EPUBCheck.
I renamed an existing EPUB file with your file name:
```
java -jar /Users/laudrain/Documents/Fichiers/eBook/epubcheck/epubcheck4_2/epubcheck.jar "Mały Książę - Antoine de Saint-Exupéry.epub" 
Vérifications faites en utilisant les règles de la version epub 3.2.
Aucune erreur ou avertissement détecté.
Messages: 0 fatale / 0 erreur / 0 avertissement / 0 info
```

**Comment by spajak** [comment]
I've managed to make it work - just added :
```
-Dsun.jnu.encoding=UTF8 -Dfile.encoding=UTF8
```
to the command line. But this is not documented anywhere. Found it [here](https://www.baeldung.com/java-char-encoding) if someone has a similar issue.

**Comment by danielweck** [comment]
Thanks for sharing your resolution, @spajak 
I added your findings to the "Troubleshooting" section of the wiki:
https://github.com/w3c/epubcheck/wiki/Running#troubleshooting

CC @rdeltour @tofi86
