### ISSUE TITLE
Absolute paths not supported, but error message says "not found."

### ISSUE THREAD

**Issue by jgilmore** [w3c/epubcheck#1066]
This is a bug, and I missed something in the EPUB spec.

I've made an epub with a fairly deep directory structure. ALL my xhtml files have a line in them:
&lt;link href="/site.css" media="screen" rel="stylesheet" type="text/css" /&gt;
 
And each and every one gets an error:
ERROR(RSC-007): OldCovenants.epub/Publication/0001_oc/0028_ezekiel/021.21_ezekiel.xhtml(3,86): Referenced resource 'Publication/0001_oc/0028_ezekiel/site.css' could not be found in the EPUB.

So I finally found the *closed* issue someone else made to complain about this. https://github.com/w3c/epubcheck/issues/233 There's even a suggestion made there to improve the error message.

Please give an intelligible error message. Seriously, that's the very purpose of epubcheck, and I feel it's failed me on this one.

The error message should be:  "Absolute URI references are not allowed"

Further, the text of the error that IS given indicates that this isn't being checked correctly. The error indicates that epubcheck looked for "Referenced resource 'Publication/0001_oc/0028_ezekiel/site.css" which indicates that if "site.css" existed in the "Publication/0001_oc/0028_ezekiel" directory, I wouldn't have gotten this error.

But the epub would still be wrong, because absolute URI's aren't allowed. And if my survey of the behavior of ebook readers is correct, the readers would then NOT find the resource and behave unexpectedly! Very bad. Maybe.

**Comment by rdeltour** [comment]
It looks like the error message could be improved indeed. Thanks for the report!

**Comment by rdeltour** [comment]
This should now be reported as `RSC-026` since #1396
