### ISSUE TITLE
What's the proper way to set URL identifier?

### ISSUE THREAD

**Issue by spajak** [w3c/epubcheck#1068]
Which is the correct identifier?
```xml
<dc:identifier>urn:https://example.com/foo</dc:identifier>
<dc:identifier>urn:uri:https//example.com/foo</dc:identifier>
<dc:identifier>https://example.com/foo</dc:identifier>
```
Or none of the above?

**Comment by rdeltour** [comment]
All these are valid identifiers:

> This specification imposes no additional restrictions or the requirements of the identifier except that it MUST be at least one character in length after white space has been trimmed.

although the last one is probably recommended:

>  It is strongly encouraged that the identifier be a fully qualified URI, however.

URLs with the `urn` scheme (aka URNs) are commonly used too, but typically when the identifier is an ISBN or UUID.

**Comment by rdeltour** [comment]
Closing this as `invalid` as it is a support request, not an issue with EPUBCheck.
