### ISSUE TITLE
HTML doctype should be case insensitive

### ISSUE THREAD

**Issue by spajak** [w3c/epubcheck#1069]
In `.xhtml` file `<!doctype html>` should be allowed the same way as `<!DOCTYPE html>`. See the [spec](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype).

**Comment by rdeltour** [comment]
You’re pointing to the HTML syntax of HTML; EPUB uses the XML syntax (aka XHTML)

In XML, [DOCTYPE must be upper-case](https://www.w3.org/TR/xml/#dt-doctype). See also this good (albeit old) [article by Mathias Bynens on XHTML5](https://mathiasbynens.be/notes/xhtml5).
