### ISSUE TITLE
null pointer exception on valid ePub w/ obfuscated SVG

### ISSUE THREAD

**Issue by VeryGoodErotica** [w3c/epubcheck#1077]
With an obfuscated SVG image, current ePubCheck exits with a null pointer exception.

Minimal Test case: https://librelamp.com/testCase.epub

If the SVG image is not obfuscated the same ePub validates.

If the same obfuscation method is used to obfuscate fonts there is no issue, it is only an issue when obfuscating an SVG.

ePub viewers display the test case, including the obfuscated SVG, just fine.

I still am not able to run ePubCheck myself because of a Java dependency issue but https://www.mobileread.com/forums/showpost.php?p=3887641&postcount=7 shows the error when run by Doitsu at mobileread forum

**Comment by rdeltour** [comment]
I could reproduce the `NullPointerException`, so there’s clearly a bug here.

I’ll have to dig deeper to know more, but thanks for the report!
