### ISSUE TITLE
Allow underscores in the host part of URLs

### ISSUE THREAD

**Issue by Mustaf2659** [w3c/epubcheck#1079]
While validate the ePub File the below URL showing error as "**missing 1 slash(es) '/' after the protocol 'http:'**", but the url link works fine.

> &lt;a href="http://encyclopedie_universelle.fracademic.com/65285"&gt; http://encyclopedie_universelle.fracademic.com/65285 &lt;/a&gt;

Please suggest how solve this issue.

**Comment by rdeltour** [comment]
At first sight this looks like the same issue as #1034, but I’m not 100% sure sine the URL you’re showing here looks right.

Would you be able to share a full EPUB file to help us reproduce the error?

**Comment by Mustaf2659** [comment]
Herewith attached the sample epub file with the actual link we facing issue

[Sample.zip](https://github.com/w3c/epubcheck/files/3609205/Sample.zip)

**Comment by Mustaf2659** [comment]
Herewith attached Sample ePub Package with the URL link causing error in Checker

[Sample.zip](https://github.com/w3c/epubcheck/files/3609219/Sample.zip)

**Comment by Mustaf2659** [comment]
Unable to share full ePub file, herewith attached Sample ePub Package with the URL link causing error in Checker

[Sample.zip](https://github.com/w3c/epubcheck/files/3609251/Sample.zip)

**Comment by rdeltour** [comment]
thanks @Mustaf2659!

**Comment by rdeltour** [comment]
Ah, the issue comes from the use of the underscore character ('`_`') in the host name, which is disallowed.
Now, as most browsers will be able to reach the link, I'm wondering if EPUBCheck should be more permissive here.

**Comment by Mustaf2659** [comment]
Thanks @rdeltour for your information.

**Comment by rdeltour** [comment]
All things considered, I still think there is an issue here. EPUBCheck should not reject this URL, as the hyperlink works in most browsers.

I’m reopening the issue and changing its title for easier reference.

**Comment by mattgarrish** [comment]
Ya, isn't the issue that you can't register domain names with underscores but you can create subdomains with them as the rules aren't often enforced?

It really shouldn't result in warnings, as there's no encoding fix to get around it that I know of and the author likely can't change the URL.

**Comment by Mustaf2659** [comment]
Hi @rdeltour and @mattgarrish,

Thanks for fixes in ePub checker 4.2.3, issue resolved.

Regards,
Mustafa
