### ISSUE TITLE
fragment identifiers in manifest

### ISSUE THREAD

**Issue by dauwhe** [w3c/epubcheck#1085]
As an experiment I tried to put a fragment identifier on an item:

```xml
  <item id="content_001"  href="content_001.xhtml#p2" media-type="application/xhtml+xml"/>
```
EPUBCheck seems to interpret the fragment as part of the file extension:

```
WARNING(HTM-014a): ..epub/OPS/package.opf(11,91): XHTML Content Document file name 'OPS/content_001.xhtml#p2' should have the extension '.xhtml'.
ERROR(RSC-001): ..epub/fragment.epub(-1,-1): File 'OPS/content_001.xhtml#p2' could not be found.
ERROR(RSC-008): ..epub/OPS/nav.xhtml(8,33): Referenced resource 'OPS/content_001.xhtml' is not declared in the OPF manifest.
WARNING(OPF-003): ..epub/fragment.epub(-1,-1): Item 'OPS/content_001.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
```
Perhaps EPUBCheck could provide a more informative message. 

****

While researching this haven't yet found anything in EPUB 3.2 that forbids fragment identifiers in `href` attributes! Stay tuned.

**Comment by rdeltour** [comment]
Good, catch! The message could definitely be improved.

> While researching this haven't yet found anything in EPUB 3.2 that forbids fragment identifiers in `href` attributes! 

I think it's kinda implied by the spec saying:

> Each `item` element in the manifest identifies a Publication Resource by the IRI [RFC3987] provided in its `href` attribute

but yeah it would be worth being explicit.
