### ISSUE TITLE
ebook error message

### ISSUE THREAD

**Issue by IsleofGough** [w3c/epubcheck#1087]
I have a ePub generated from MadCap Flare. It opened fine in Apple Books until the Catalina upgrade, and now generates a message "missing file or directory". It passes all ePub checks though. In IngramSpark it gives three strange error messages. Would you please suggest where I might look to find solutions to whatever is the ePub problem. Error messages in IngramSpark:
[ERROR]OPS/Common.Knots.xhtml: 20:90: value of attribute "id" is invalid: must be an XML name without colons
[ERROR]OPS/HandAndInstrumentTies.xhtml: 121,168: value of attribute "id" is invalid: must be an XML name without colons
[ERROR]OPS/HandAndInstrumentTies.xhtml: 156,131: value of attribute "id" is invalid: must be an XML name without colons.

**Comment by laudrain** [comment]
Hi @IsleofGough, if your EPUB "passes all ePub checks", this is not an EPUBCheck question, but more an issue to report to IngramSpark.

**Comment by mattgarrish** [comment]
It could be an epubcheck problem if the file is an EPUB 2, as epubcheck should catch any non-XML IDs.

The requirement to use non-colonized XML names for IDs was lifted in (X)HTML5, though, so if it's an EPUB 3 file then IngramSpark is either validating the file incorrectly or being more restrictive than the specification.

**Comment by rdeltour** [comment]
@IsleofGough Feel free to send me a sample EPUB, I can have a further look and try to reproduce.

**Comment by IsleofGough** [comment]
Thank you. MadCap Flare used to compress the mime attachment, generating errors, until the most recent release a few weeks ago. It adds a lot of extra style references if dynamic content is enabled in the export, which also generate warnings or errors. But without dynamic content being enabled, the ePub output passes epub-checker.app without problems. It does bring over the print CSS designations, but they aren't actually used. It sounds like an IngramSpark issue. I appreciate the comments.
