### ISSUE TITLE
New error reported with EpubCheck 4.2.2

### ISSUE THREAD

**Issue by raducoravu** [w3c/epubcheck#1088]
The error gets reported in "nav.xhtml" which is missing a title element:

       Error while parsing file: assertion failed: WARNING: The 'head'            element should have a 'title' child element.

Maybe this particular error is not useful for the nav.xhtml because its title would not be used at anything anyway.

**Comment by rdeltour** [comment]
Thanks for the report @raducoravu, that's interesting.

I haven't checked, but this error is probably issued by the XHTML schemas. On the one hand I understand why some requirements are not strictly and practically useful or important when the Nav Doc isn't included in the spine, on the other hand I don't think that the specs make a special case, and we currently do not have an easy technical way to filter these in EPUBCheck.

We probably don't want to create custom, filtered-down schemas for the Nav Doc only. The only exception is for our schematron rules, which we can adapt for the Nav Doc.

@mattgarrish thoughts?

**Comment by raducoravu** [comment]
If you want you can leave the current behavior, but it's possible that existing EPUB books did not have the title added inside the nav.xhtml file so their validation will report this extra error until the publishing processes are modified to include a title for the nav.xhtml file.

**Comment by raducoravu** [comment]
Does the specification state that the "nav.xhtml" must be valid XHTML 5? Because if it does then the error is accurately given.

**Comment by rdeltour** [comment]
> Does the specification state that the "nav.xhtml" must be valid XHTML 5?

Yes, the Navigation Document is defined as a special case of an XHTML Content Document, which in turn must conform to HTML.

**Comment by mattgarrish** [comment]
Right, there are restrictions on the content of the navigation document, but the document itself still has to be a valid instance of xhtml.

The only exceptions to the title requirement are for srcdoc documents and if there is a higher-level protocol that specifies the title. The first case doesn't apply and the second would be a bit of a stretch, so we'd be blessing invalid documents if we made this exception.

Also, the nav document can be presented as-is even if it's not in the spine. Reading systems aren't required to process it into a menu widget. A web-based reading system, for example, would likely use the document as html. In that case, you should still have a title.

**Comment by raducoravu** [comment]
Ok, you can close the issue if you want.

**Comment by rdeltour** [comment]
> Also, the nav document can be presented as-is even if it's not in the spine. Reading systems aren't required to process it into a menu widget. A web-based reading system, for example, would likely use the document as html. In that case, you should still have a title.

Good point! I'm closing the issue.
