### ISSUE TITLE
playOrder validation

### ISSUE THREAD

**Issue by ltuch** [w3c/epubcheck#1089]
I have an epub with a ncx file which has navPoints missing the playOrder attribute, but epubcheck is not flagging an error.

According to the ncx specifications it seems that the playOrder attribute is required - see http://www.daisy.org/z3986/2005/Z3986-2005.html#NCXplay.

"The playOrder attribute is required on each pageTarget, navTarget and navPoint. It provides a means to collate all pageTargets, navTargets, and navPoints into a single ordered sequence that reflects their order in the normal playback sequence of the book as presented in the spine and SMIL file(s)."

Should epubcheck flag an error in the case of a missing playOrder?

**Comment by mattgarrish** [comment]
EPUB 2 makes a number of exceptions to the NCX, including that playOrder is optional:

> playOrder attributes are not required. Although playOrder attributes are not used to sequence SMIL content, if present, they should contain valid values that reflect the linear document reading order. This could, for example, be used when one is navigating a pageList to find a corresponding location in the navMap.

See http://idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.4

**Comment by mattgarrish** [comment]
Sorry, the link got cut off. Should be http://idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.4.2

**Comment by rdeltour** [comment]
Closing as `invalid`, as per Matt’s comment. But feel free to keep on commenting! 😊

**Comment by laudrain** [comment]
@ltuch is your EPUB an EPUB 2 ?
As another way to escape NCX issues is to switch to EPUB3. On the EPUB2 functional perimeter, EPUB3 does everything better, noticeably enabling accessibility.
