### ISSUE TITLE
ARIA role=landmark on cover PAGE section's

### ISSUE THREAD

**Issue by LaZay** [w3c/epubcheck#1090]
In order to respect the specification of mapping between epub:type and ARIA roles, it would be necessary to allow the ARIA role=landmark on <SECTION> elements contained in cover **page**. In the spec, it was not said in the mapping table indeed, though it was specified in part about **sections** in cover pages.
https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-covers

So far, epubcheck says that only the following ARIA roles are permitted on sections:  "alert", "alertdialog", "application", "banner", "complementary", "dialog", "doc-abstract", "doc-acknowledgments", "doc-afterword", "doc-appendix", "doc-bibliography", "doc-chapter", "doc-colophon", "doc-conclusion", "doc-credit", "doc-credits", "doc-dedication", "doc-endnotes", "doc-epilogue", "doc-errata", "doc-example", "doc-foreword", "doc-glossary", "doc-index", "doc-introduction", "doc-notice", "doc-pagelist", "doc-part", "doc-preface", "doc-prologue", "doc-pullquote", "doc-qna", "doc-toc", "document", "feed", "log", "main", "marquee", "navigation", "region", "search", "status" ou "tabpanel"

COVER XHTML PAGE
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns:epub="http://www.idpf.org/2007/ops" xmlns="http://www.w3.org/1999/xhtml"
    xmlns:schema="http://schema.org/" lang="fr" xml:lang="fr">
    <head>
        <title>Étrangers à la terre</title>
        <link rel="stylesheet" href="couverture.css" type="text/css" />
        <meta charset="utf-8" />
    </head>
    <body lang="fr" xml:lang="fr" epub:type="frontmatter" >
        <section epub:type="cover" class="couverture" role="landmark"><a id="cover"><img
            src="cover/cover.jpg" alt="Image de couverture" class="img" role="doc-cover" /></a>
        </section>
    </body>
</html>

**Comment by laudrain** [comment]
@LaZay isn't this issue more related to Ace than EPUBCheck ?
About this subject of cover, you may have a look on https://github.com/daisy/ace/issues/214

**Comment by LaZay** [comment]
It is an epubcheck error. Not an ACE error...

**Comment by LaZay** [comment]
COVER XHTML PAGE
![image](https://user-images.githubusercontent.com/28054954/69439644-a9278500-0d47-11ea-8d06-4da674265c1c.png)

**Comment by laudrain** [comment]
in [Accessible Rich Internet Applications (WAI-ARIA) 1.1](https://www.w3.org/TR/wai-aria/#role_definitions), 'landmark' as a value for HTML role attribute is specified in 'Abstract Roles' entries (5.3.1).
With the following recommandation:
> Abstract roles are used for the ontology. Authors MUST NOT use abstract roles in content.

Then, https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-covers is perhaps faulty ?
```
If a section of cover content needs to be identified, the generic landmark role can be used with a label:

<section role="landmark"> aria-label="Cover"
   …
</section>

```

**Comment by mattgarrish** [comment]
> Then, https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-covers is perhaps faulty ?

Yes, it's supposed to say to use the `region` role. Landmark, as you note, is an abstract role that is used to define the hierarchical model of ARIA, but is not for content.

**Comment by rdeltour** [comment]
@laudrain is right: `landmark` is an abstract role and must not be used on elements, so EPUBCheck is correct in reporting this as an error.

> Then, https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-covers is perhaps faulty ?

Yes, it seems the guide is wrong there. I guess it is meant to recommend using the `region` landmark role instead? But then a `section` element does have an implicit `region` role when it has an accessible name (e.g. using `aria-label` or `aria-labelledby`)

**Comment by mattgarrish** [comment]
> But then a `section` element does have an implicit `region` role when it has an accessible name (e.g. using `aria-label` or `aria-labelledby`)

Yes, good point. I'm forgetting the ARIA in HTML rules.

**Comment by rdeltour** [comment]
Ah, @mattgarrish beats me to it 😊

Anyways, I'm closing this issue since EPUBCheck is not at fault here. But of course feel free to keep on commenting here!

**Comment by mattgarrish** [comment]
>  I'm closing this issue since EPUBCheck is not at fault here.

Right, and I'll take a look at updating that guidance.
