### ISSUE TITLE
epubcheck 4.2.0 and higher version are throwing StackOverflowError error.

### ISSUE THREAD

**Issue by apiyush** [w3c/epubcheck#1094]
I have validated my epub file with epubcheck 4.0.2 ,4.1.1 ,4.2.0 and 4.2.1 . It is validating correctly with 4.0.2 and 4.1.1 but for 4.2.0 and higher version it is throwing below errors.

 java.lang.StackOverflowError
	at java.util.LinkedList.poll(Unknown Source)
	at com.adobe.epubcheck.opf.XRefChecker.checkReadingOrder(XRefChecker.java:532)
	at com.adobe.epubcheck.opf.XRefChecker.checkReadingOrder(XRefChecker.java:576)
	............
I have checked the source code of 4.1.1 and 4.2.0 and found that in 4.2.0 there is a recursive methods which is not available in 4.1.1 and lower version. At this point my epub check throwing errors.
`com.adobe.epubcheck.opf.XRefChecker.checkReferences()
com.adobe.epubcheck.opf.XRefChecker.checkReadingOrder(Queue<Reference>, int, int)`
I am able to access epub in edge browser , calibre.
I cannot share epub file because it has copyright.

Please advise me to solve the problem
Thanks!

**Comment by rdeltour** [comment]
Thanks for the report!

Have you tried [increasing the thread stack size](https://github.com/w3c/epubcheck/wiki/Running#javalangstackoverflowerror)? It might help…

Also, I understand the file is copyrighted, but would it be possible for you to send the the EPUB file privately? Or maybe create a scrambled version? I won't share it with anyone (I can possibly sign an NDA if needed).

**Comment by apiyush** [comment]
Thanks for the reply!
Sorry! I cannot share any assets of my client since I have an agreement with my client. 
It would be helpful if you will suggest me any solution(Any api or tool) to find the recursive reference in my epub file . I think there are some bad recursive references in toc.ncx.

**Comment by rdeltour** [comment]
> Sorry! I cannot share any assets of my client since I have an agreement with my client.

I understand. Sadly, it will be harder for me to reproduce.

> It would be helpful if you will suggest me any solution(Any api or tool) to find the recursive reference in my epub file .

You can always try to debug the code in Eclipse (or any other Java editor+debugger), but that would require understanding EPUBCheck's source code, possibly in depth.

> I think there are some bad recursive references in toc.ncx.

Is it an EPUB 2 book? Can you manually spot any suspicious recursive references?

**Comment by apiyush** [comment]
It is an epub3 book. I am trying to spot suspicious recursive references. since toc.ncx and package.opf file are too large file and It has many recursive references. So I am facing difficulty to  find exact suspicious point.

**Comment by rdeltour** [comment]
Ok, thanks for the help. You may just be hitting a system limit due to the large number of references, and increasing the allocated thread stack size might be the solution here.

**Comment by apiyush** [comment]
Thanks for the help!
I have increased thread stack size to 3mb and it is working fine now.

**Comment by rdeltour** [comment]
Ok, great!
