### ISSUE TITLE
Checking headings seems too aggressive?

### ISSUE THREAD

**Issue by jenstroeger** [w3c/epubcheck#1095]
While I was playing around with various heading levels, I stumbled upon something curious: I can’t format text portions of them:
```html
<h1 id="some-chapter">
  A <em>Schnufte</em><br/>and<br/><strong>Palufte</strong><br/>Chapter Heading
</h1>
```
This chapter heading is being marked by epubcheck (EPUBCheck v4.2.3-SNAPSHOT) with the following errors:
```
Validating using EPUB version 3.2 rules.
ERROR(RSC-005): test.epub/OEBPS/chapter.xhtml(5,18): Error while parsing file: element "em" not allowed here; expected the element end-tag or text
ERROR(RSC-005): test.epub/OEBPS/chapter.xhtml(5,36): Error while parsing file: element "br" not allowed here; expected the element end-tag or text
ERROR(RSC-005): test.epub/OEBPS/chapter.xhtml(5,45): Error while parsing file: element "br" not allowed here; expected the element end-tag or text
ERROR(RSC-005): test.epub/OEBPS/chapter.xhtml(5,53): Error while parsing file: element "strong" not allowed here; expected the element end-tag or text
ERROR(RSC-005): test.epub/OEBPS/chapter.xhtml(5,74): Error while parsing file: element "br" not allowed here; expected the element end-tag or text
```
According to this error message, only text or end-tag are allowed; however, an `<a>` tag seems to be tolerated but that’s missing from the error message.

Looking at the HTML5 standard<sup>†</sup>, though, any one of the `H` elements allows for all sorts of content formatting ([W3 docs](https://www.w3.org/TR/html52/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements)): it says that an `H` element’s “Content model: [Phrasing content](https://www.w3.org/TR/html52/dom.html#phrasing-content-)” which includes `<em>` and `<strong>` etc.

Could somebody please shed some light on this?

—————
<sup>†</sup> I assume here that EPUB3 supports HTML5 fully, at least that’s how I understand [the Content documentation](http://idpf.org/epub/30/spec/epub30-overview.html#sec-content-docs).

**Comment by rdeltour** [comment]
I tried to reproduce, but using the snippet above validates just fine here. Would you be able to share a sample to help me reproduce?

**Comment by jenstroeger** [comment]
@rdeltour, next time I see you I owe you a ☕️

Sigh, please disregard.
