### ISSUE TITLE
Catch NuValidator's StackOverflowError

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#1096]
For pagina EPUB-Checker I updated the Windows wrapper to add the JVM argument `-Xss1024k` as suggested in https://github.com/w3c/epubcheck/wiki/Running#javalangstackoverflowerror but it seems that on certain systems this does not help and the SOE is still thrown. This leads to an unwanted situation: EPUBCheck is finished "successfully without errors or warnings" – but only because _no_ checks were performed at all because of the SOE.

![grafik](https://user-images.githubusercontent.com/365118/72423731-0c042e00-3785-11ea-86f4-f3721f255f0b.png)

This can be reproduced on Mac and Windows by setting `-Xss144k` for example and checking a medium or large sized book.

Is there any chance to throw a `FATAL` exception if the NuValidator crashes?

And as a workaround I'm looking for a way to catch the previously uncaught SO-Errors when running [`EpubCheck.doValidate()`](https://github.com/w3c/epubcheck/blob/master/src/main/java/com/adobe/epubcheck/api/EpubCheck.java#L208)? Does anyone know of a solution for that? Hint: Wrapping `EpubCheck.doValidate()` in a `try/catch` does _not_ work ;-)

Thanks, Tobias

**Comment by rdeltour** [comment]
By essence a StackOverflowError indicates a serious issue that is likely unrecoverable, and I don't think it would make much sense (nor would be much helpful) to catch that.

I'm closing the issue as `wontfix`, but feel free to keep commenting here if anyone can suggest a better handling!
