### ISSUE TITLE
 cli + js library for epubcheck

### ISSUE THREAD

**Issue by b3u** [w3c/epubcheck#1100]
I came across <https://github.com/chialab/epubchecker>, which seems to be an up-to-date javascript library and nodejs-based cli tool for epubcheck. Should this be added to the wiki?

**Comment by rdeltour** [comment]
I added the tool to the [list of know third-party apps](https://github.com/w3c/epubcheck/wiki/GUI#other-tools). The list should shortly be migrated to EPUBCheck’s web site, when we have one. Thanks for the notification!
