### ISSUE TITLE
Discrepancy between EPUBCheck and Ace tools.

### ISSUE THREAD

**Issue by jenstroeger** [w3c/epubcheck#1116]
I’ve been playing with Glossary and Index of accessible EPUB3 and noticed a discrepancy between EpubCheck and [Ace](https://daisy.github.io/ace/); reporting this here because I think that the Ace side is actually correct.

### Glossary

Suppose a Glossary [description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) (in a chapter labeled as a Glossary):
```html
<dl epub:type="glossary" role="doc-glossary">
  ...
</dl>
 ```
then EpubCheck gives me the following error:
```
OEBPS/glossary.xhtml(23,50): Error while parsing file: value of attribute "role" is invalid; must be equal to "group", "list", "none" or "presentation"
```
If I change the role to `"list"` or remove it then Ace complains:
```json
    {
      "@type": "earl:assertion",
      "earl:result": {
        "earl:outcome": "fail"
      },
      "assertions": [
        {
          "@type": "earl:assertion",
          "earl:result": {
            "earl:outcome": "fail",
            "dct:description": "Element has no ARIA role matching its epub:type",
            "earl:pointer": {
              "cfi": [
                "/4/2/10"
              ],
              "css": [
                "dl"
              ]
            },
            "html": "<dl xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:epub=\"http://www.idpf.org/2007/ops\" epub:type=\"glossary\">"
          },
          "earl:assertedBy": "aXe",
          "earl:mode": "automatic",
          "earl:test": {
            "earl:impact": "minor",
            "dct:title": "epub-type-has-matching-role",
            "dct:description": "Ensure the element has an ARIA role matching its epub:type",
            "help": {
              "url": "http://kb.daisy.org/publishing/docs/html/roles.html",
              "dct:title": "ARIA role",
              "dct:description": "ARIA role should be used in addition to epub:type"
            },
            "rulesetTags": [
              "best-practice"
            ]
          }
        }
      ],
      "earl:testSubject": {
        "url": "glossary.xhtml",
        "dct:title": "Glossary"
      }
    }
```
The [IDPF docs](http://idpf.org/epub/dict/#sec-2.3) don’t mention ARIA roles, though.

### Index

The same goes for an Index [body](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) element:
```html
<body> 
  ...
</body>
```
where EpubCheck gives me
```
OEBPS/index.xhtml(9,9): Error while parsing file: The document containins only index content, its 'body' element must have the epub:type 'index'
```
and if I add that:
```html
<body epub:type="index" role="doc-index">
```
then I get
```
OEBPS/index.xhtml(9,44): Error while parsing file: value of attribute "role" is invalid; must be equal to "application", "document", "none" or "presentation"
```
and if I change the role to `"document"` (because I [must not override `body`](https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-body)) or remove it then Ace complains as above. 

### So…

Something doesn’t seem quite right and consistent here, or what am I missing? I can’t seem to manage building a Glossary and an Index that passes for both tools, EpubCheck _and_ Ace.

**Comment by jenstroeger** [comment]
Addendum. After talking with @flittle8 I removed all attributes from `<dl>` considering the context `<section>` is set up correctly as glossary. Should EpubCheck have tagged the existence of these attributes?

**Comment by rdeltour** [comment]
Ace is known to be too strict about reporting `epub:type` attributes with unmatched ARIA roles. You can safely ignore this best practice violation.

About the EPUBCheck rules:

- the allowed roles come from the XHTML schemas, which implement the authoritative rules defined in the [ARIA in HTML](https://www.w3.org/TR/html-aria) specification.
- the rules related to `index-*` `epub:type` attributes are defined in the EPUB Indexes satellite specification which has never been widely implemented (as far as I know).

At first sight I think EPUBCheck is correct here, and Ace is too strict about the missing ARIA role. This is a known issue in Ace, so I'm closing this one here. Feel free to reopen if you disagree, or keep on commenting here in any case!
