### ISSUE TITLE
html link requirements inconsistent and don't match spec

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1118]
I'm finding epubcheck has rules on resources referenced from html `link` that don't exist in the specification:

- The xpgt tests require a css style sheet link or manifest fallback
- But there's also a foreign resource test that allows anything to be linked without a fallback (foreign-res-in-html-link-valid)

I'm all in favour of not expending energy on html link elements, but the only exemption the spec offers is when rel=pronunciation is specified.

I've opened an issue about this against the core specs at https://github.com/w3c/publ-epub-revision/issues/1312

The xpgt tests could be removed if the rules are loosened as it would validate the general ignoring that's also in place.

**Comment by rdeltour** [comment]
EPUBCheck should better match the spec since #1378.
