### ISSUE TITLE
epub 2.0 doesn't enforce ops file extension

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1125]
I'm trying to classify a test that issues a warning if a content document doesn't have an `.xhtml`, `.html` or `.htm` extension but there's nothing in the specs that recommends this.

For now, I'm going to dump it into a content.feature file under the requirements of 1.4.1.2, but doesn't seem like something we should be checking at all.

**Comment by rdeltour** [comment]
Fixed in #1388
