### ISSUE TITLE
Any chance you could add an Automatic-Module-Name?

### ISSUE THREAD

**Issue by io7m** [w3c/epubcheck#1128]
Hello!

Any chance you could add an `Automatic-Module-Name` manifest entry? I'd suggest `org.w3c.epubcheck`.

See the following for details: http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by io7m** [comment]
PR here: https://github.com/w3c/epubcheck/pull/1129

**Comment by rdeltour** [comment]
Thanks for the issue and the PR 👍

I’m not familiar with the Java 9 module system, so I’ll have to dig into it first (thanks for the pointer 😊), but the request sounds reasonable at first sight!

**Comment by io7m** [comment]
Thanks!

What this basically comes down to is that if your jar file doesn't contain a module descriptor (an explicit `module-info.class` file containing lists of required modules and exported packages), the module system will essentially try to infer one for you. It'll use the name of the jar file as the module name (`epubcheck` in your case) and it'll pretend that you exported all of your packages and that you can also read any package exported by other modules. The problem is the module name part... The module name being derived from the jar name is a bit unpleasant, and it only takes one mistake in a build system to accidentally cause the module name to change. What the JPMS group ended up doing was to allow for people to say "Here's the module name we would use if we were ever to expend the effort to fully modularize the codebase" by adding an `Automatic-Module-Name` entry. That allows other projects to depend on the module name without any risk of it changing under them.

**Comment by io7m** [comment]
On a related note, I really commend your up-to-date OSGi metadata. The fact that you've gone to the trouble of having OSGi headers with detailed imports and exports means that you're likely to have a relatively easy time if you ever attempt full JPMS modularization. It demonstrates that you've given some consideration as to the exposed ABI of the packages. :+1:

**Comment by rdeltour** [comment]
Thank you @io7m  for the issue and the PR, it will be included in the next maintenance release (v4.2.3).

I also created issue #1137 as a reminder to try to provide a proper module descriptor.

**Comment by io7m** [comment]
Thanks!
