### ISSUE TITLE
EPUB Structural Semantics to ARIA Roles Mapping incorrectly rejected

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epubcheck#1130]
epubcheck 4.2.2 rejects the following ARIA role mappings: (1) epub-type="cover" to ARIA role "doc-cover" and (2) epub-type"epigraph" to ARIA role "doc-epigraph". Both mappings are specified in https://w3c.github.io/publ-cg/guides/aria-mapping.html but are rejected by epubcheck 4.2.2. More mappings might be rejected, a complete role mapping review might be necessary.

**Comment by rdeltour** [comment]
Thanks for the report!

EPUBCheck isn't necessarily wrong here, as ARIA roles are not allowed on all the elements where `epub:type` is. For instance, `doc-cover` is only allowed on images.

For more details, you can look at the [EPUB Type to ARIA Role Authoring Guide](https://idpf.github.io/epub-guides/epub-aria-authoring/), or directly at the normative [ARIA in HTML specification](https://w3c.github.io/html-aria/).

Would you be able to share a sample EPUB or code snippet? I can look into it and see if it's a false-negative or if EPUBCheck is indeed correct.

**Comment by ThomasR128** [comment]
Romain,

“doc-cover” solved by moving the role from <section> to <img>
“doc-epigraph” solved by moving the role from <section> or <body> to a newly inserted <blockquote>

Thanks for pointing me to the Authoring Guide, I only knew about the https://w3c.github.io pages.

Saludos
Thomas
