### ISSUE TITLE
OPF package accessiblity metadata a11y:certifierCredential raises error "undefined property" when link instead of meta

### ISSUE THREAD

**Issue by danielweck** [w3c/epubcheck#1140]
(tested with EPUB Check 4.2.2 - via the Pagina Mac app)

http://kb.daisy.org/publishing/docs/metadata/evaluation.html#a11y:certifierCredential

> The property can either be a text field with the name of the credential held, or it can be a link to a description of the credential.

Relevant test files:

https://github.com/w3c/epubcheck/blob/master/src/test/resources/30/single/opf/valid/vocab-a11y-declared.opf#L11

https://github.com/w3c/epubcheck/blob/master/src/test/resources/30/single/opf/valid/vocab-a11y-undeclared.opf#L10

**Comment by rdeltour** [comment]
Good catch @danielweck, thanks! This will be fixed by #1151 in v4.2.3.
