### ISSUE TITLE
(RSC-007): /index_split_019.html: Referenced resource 'website' could not be found in the EPUB.

### ISSUE THREAD

**Issue by chosn4one** [w3c/epubcheck#1159]
I am at a loss. The "reference website resource is in fact in the ePub, but this error is preventing me from uploading.

**Comment by rdeltour** [comment]
Hi @chosn4one. Thanks for reporting the issue. Would you be able to send a sample EPUB to help us reproduce?

**Comment by rdeltour** [comment]
Closing (for lack of reply, we can't reproduce the issue).
