### ISSUE TITLE
glossary property in the manifest is not allowed on content documents

### ISSUE THREAD

**Issue by acabal** [w3c/epubcheck#1170]
Tested on epubcheck 4.2.4.

At Standard Ebooks we're trying to add a glossary according to the [EPUB Dictionaries and Glossaries 1.0](http://idpf.org/epub/dict/epub-dict.html#sec-2.5.3) spec.

In the manifest file, we add two items:

````xml
<item href="glossary-search-key-map.xml" id="glossary-search-key-map.xml" media-type="application/vnd.epub.search-key-map+xml" properties="search-key-map glossary"/>
<item href="text/glossary.xhtml" id="glossary.xhtml" media-type="application/xhtml+xml" properties="glossary"/>
````

[According to the spec](http://idpf.org/epub/dict/epub-dict.html#sec-2.5.3), we should be able to add the `glossary` property both to the search key map file to to indicate that the file applies to a glossary, and to the XHTML content document file to indicate that it contains the actual glossary.

However epubcheck outputs:

````
ERROR(OPF-015): /path/to/glossary.xhtml(-1,-1): The property 'glossary' should not be declared in the OPF file.
````

It seems to allow `glossary` for the search key map, but not for the XHTML file.

**Comment by rdeltour** [comment]
Have you checked that your `glossary.xhtml` XHTML Content Document includes at least an element with the `epub:type` `glossary`? This is mandatory for the `glossary` property to be allowed on the manifest item.

If that's not the issue, then it's possibly a bug in EPUBCheck 😊

**Comment by acabal** [comment]
Yes, `glossary.xhtml` has an element with `epub:type="glossary"`, though it's on a `<section>` element in `glossary.xhtml`, not a `<dl>` element.

**Comment by rdeltour** [comment]
OK, thanks for your answer 😊
Are you running EPUBCheck with the `dict` profile? 
Would you be able to share a test EPUB?

**Comment by rdeltour** [comment]
I was able to reproduce, so no need to send a test EPUB after all 😉
I'll dig deeper, but it does seem like a bug. Thanks for the report!
