### ISSUE TITLE
Mathjax - Remote resource reference not allowed

### ISSUE THREAD

**Issue by vigneshkumarelumalai** [w3c/epubcheck#1179]
Hi,

while trying to validate the ePub linked with Mathjax, i'm getting the below error could you please help me to solve the issue.

**Error:**
Validating using EPUB version 3.2 rules.
(https://github.com/w3c/epubcheck)

13 August, 2020 7:01:21 PM IST

---------------------------------------------------
WARNING (OPF-018) at "#####_epub/OEBPS/chapter02.xhtml" (line 562, col 562):
   The 'remote-resources' property was declared in the Package Document, but no reference to remote resources has been found.

ERROR (RSC-006) at "#####_epub/OEBPS/chapter02.xhtml" (line 26, col 123):
   Remote resource reference not allowed; resource must be placed in the OCF.****

---------------------------------------------------

Check finished with 1 warnings and 1 errors!

EPUB from source folder wasn't saved because it contains errors or warnings!

---------------------------------------------------

**opf:**

<item id="chapter02" href="chapter02.xhtml" media-type="application/xhtml+xml" properties="scripted mathml remote-resources" />
<item id="ef2829c3" href="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js" media-type="text/html" />

**xhtml:**
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:epubsc="http://idpf.org/epub/vocab/sc/#" xmlns:mml="http://www.w3.org/1998/Math/MathML">
<head>
<meta charset="utf-8"/>
<title>aaaaaaa</title>
<link rel="stylesheet" type="text/css" href="css/style.css"/>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=MML_HTMLorMML"></script>
</head>
<body epub:type="bodymatter">
<section epub:type="chapter">
 
<section id="sec2_1"><h2 class="h1a"><span class="label">2.1 </span>Introduction</h2>
<p class="equation">
<mml:math alttext="" display="block"><mml:mrow><mml:msub><mml:mi>&#x039B;</mml:mi><mml:mrow><mml:msup><mml:mtext>C</mml:mtext><mml:mo>+</mml:mo></mml:msup></mml:mrow></mml:msub><mml:mo>=</mml:mo><mml:mi>n</mml:mi><mml:mrow><mml:mo>(</mml:mo><mml:mtext>e</mml:mtext><mml:mo>)</mml:mo></mml:mrow><mml:mi>n</mml:mi><mml:mrow><mml:mo>(</mml:mo><mml:mrow><mml:msup><mml:mtext>C</mml:mtext><mml:mo>+</mml:mo></mml:msup></mml:mrow><mml:mo>)</mml:mo></mml:mrow><mml:mn>8</mml:mn><mml:mo>&#x00D7;</mml:mo><mml:msup><mml:mrow><mml:mn>10</mml:mn></mml:mrow><mml:mrow><mml:mo>&#x2212;</mml:mo><mml:mn>33</mml:mn></mml:mrow></mml:msup><mml:msup><mml:mi>T</mml:mi><mml:mrow><mml:mo>&#x2212;</mml:mo><mml:mn>1</mml:mn><mml:mo>/</mml:mo><mml:mn>2</mml:mn></mml:mrow></mml:msup><mml:mi>exp</mml:mi><mml:mrow><mml:mo>(</mml:mo><mml:mrow><mml:mo>&#x2212;</mml:mo><mml:mn>92</mml:mn><mml:mtext>K</mml:mtext><mml:mo>/</mml:mo><mml:mi>T</mml:mi></mml:mrow><mml:mo>)</mml:mo></mml:mrow><mml:msup><mml:mrow><mml:mtext>Jm</mml:mtext></mml:mrow><mml:mrow><mml:mo>&#x2212;</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:msup><mml:msup><mml:mtext>s</mml:mtext><mml:mrow><mml:mo>&#x2212;</mml:mo><mml:mn>1</mml:mn></mml:mrow></mml:msup></mml:mrow></mml:math>
</p> 

</section>
</section>
</body>

**Comment by rdeltour** [comment]
The [spec says](https://www.w3.org/publishing/epub32/epub-spec.html#sec-resource-locations):
> All Publication Resources MUST be located in the EPUB Container

So you can’t have an XHTML doc pointing to a remote script. 

Please note that this issue tracker is intended to be used to report issues and feature requests only. Other channels are preferred for user support (although there is no official EPUBCheck forum, there are various other places discussing ebook production topics, like forums, Twitter, or StackOverflow) 😊
