### ISSUE TITLE
Minor release glitch in 4.2.4

### ISSUE THREAD

**Issue by fire-eggs** [w3c/epubcheck#1183]
The epubcheck 4.2.4 release contains another copy of the release as a contained folder.

![image](https://user-images.githubusercontent.com/9809727/92268490-79013b00-eeb0-11ea-8f29-4ce39979479e.png)

**Comment by rdeltour** [comment]
I believe this is somehow due to how you unpacked the files. I checked the ZIP file on the release page and do not see an `epubcheck-4.2.4` directory…
I'm closing the issue, but feel free to keep on commenting below.

**Comment by fire-eggs** [comment]
Whoops you're right - sorry, "Bad User on Device"!
