### ISSUE TITLE
checker reports image/jpeg as non-standard media-type requiring fallback for epub 3.2

### ISSUE THREAD

**Issue by rakutenjeff** [w3c/epubcheck#1187]
I copied from https://github.com/w3c/epubcheck/issues/12?fbclid=IwAR0511IlICtl1XoqcWEC-bMaqv8paux4uBb3paFRzpinOrDYI5ziJ3iF3BM.
The original discussion was base on old spec and was closed.
But the problem we are facing now is even though epub 3.2 is applied(which includes jpeg as one of Core Media Type) I still see OPF-043 error was raised (Spine item with non-standard media-type "image/jpeg" has no fallback.) when Validating using EPUB version 3.2 rules.

Refer to Epub 3.2 section of core media type: https://www.w3.org/publishing/epub3/epub-spec.html#sec-core-media-types

I wonder if possible to remove the error when applying Epub 3.2 rules?

**Comment by dauwhe** [comment]
I believe you're talking about `image/jpeg` as a spine item? This is still forbidden by the [spec](https://www.w3.org/publishing/epub32/epub-spec.html#dfn-epub-content-document):

> Each referenced manifest item MUST be either a) an EPUB Content Document or b) another type of Publication Resource which, regardless of whether it is a Core Media Type Resource or a Foreign Resource, MUST include an EPUB Content Document in its fallback chain.

So only XHTML or SVG are allowed in the spine without fallbacks.

**Comment by rakutenjeff** [comment]
Yeah, I am talking about spine item.
I might have different understand here.
So, the statement I have read from https://www.w3.org/publishing/epub32/epub-spec.html#dfn-epub-content-document is the definition of "EPUB Content Document" so yeah, XHTML and SVG.

But from this introduction of [Core Media Type](https://www.w3.org/publishing/epub32/epub-spec.html#sec-cmt-intro) we can see
`those that can be included without fallbacks (Core Media Type Resources) and those that cannot (Foreign Resources).`

**Comment by rakutenjeff** [comment]
If not spine itemref elements Foreign Resources does not require a fallback from [here](https://www.w3.org/publishing/epub32/epub-spec.html#sec-foreign-restrictions).

`Foreign Resources MAY be included in an EPUB Publication without a fallback provided they are not referenced from spine itemref elements [Packages32] or directly rendered in their native format in EPUB Content Documents `

**Comment by shiestyle** [comment]
In spine itemref spec,
`Each referenced manifest item MUST be either a) an EPUB Content Document or b) another type of Publication Resource which, regardless of whether it is a Core Media Type Resource or a Foreign Resource, MUST include an EPUB Content Document in its fallback chain.`

And 'EPUB Content Document' spec says,
`A Publication Resource with an XHTML or SVG media type that contains all or part of the content of an EPUB Publication (i.e., the textual, visual and/or audio content). These resources have to conform to their respective XHTML or SVG definitions to be used in the spine or be referenced from another EPUB Content Document.`
`An EPUB Content Document is a Core Media Type Resource, so can be included in the EPUB Publication without the provision of fallbacks.`

Then, JPEG is 'EPUB Content Document'? or 'EPUB Content Document' is only XHTML and SVG?

**Comment by rakutenjeff** [comment]
Thanks for clarifying @dauwhe @shiestyle 

Is there any reference about why an EPUB Content Document has to be either xhtml or svg? Maybe this is more like something needs to be discussed in wg than here.

**Comment by mattgarrish** [comment]
> Is there any reference about why an EPUB Content Document has to be either xhtml or svg?

I think we've discussed this in the working group at least every other revision. I think it was 3.1 last. Anyway, my memories of these discussions include

- It's partially for accessibility reasons that they're not allowed without fallbacks. XHTML and SVG both offer options for making the content accessible, while raw image formats like JPEG effectively turn EPUBs into content-less shells for anyone who can't see the content. It's not an outcome that has generated a lot of support.
- There have been questions about what reading systems are supposed to do with the images (i.e., how to render them).
- It's also been questioned in the past what value allowing will really provide. It's been put forward before as a way of taking on comic and manga formats, but it's been pointed out that EPUB's significant overhead (i.e., it's packaging requirements) make it unappealing and unlikely to make anyone switch.

**Comment by rakutenjeff** [comment]
Thanks @mattgarrish 

Yeah, it seems like inherited from Epub 3.1.

I still feel it is strange that even web browser could render images "directly" while in EPUB ecosystem publishers/creators are required to provide fallback. Yeah, image itself does not have any accessibility support but I don't think a11y should be a reason to prevent us from accepting CoreMedia Type to be appearing in spine item without fallback.

**Comment by clapierre** [comment]
>Yeah, image itself does not have any accessibility support but I don't think a11y should be a reason to prevent us from accepting CoreMedia Type to be appearing in spine item without fallback.

I disagree @rakutenjeff, accessibility is the number 1 reason why we must have a fallback for anything that appears in the spine.  Its a WCAG-A violation that anything visual or auditory in nature must have an alternative modality to be perceivable, operable, understandable, and robust. 

EPUBs because it is build on web technologies must also follow WCAG guidelines and our [Accessibility 1.0](https://www.w3.org/Submission/epub-a11y/) requirements which builds upon those guidelines.  So by definition then anything that is to be rendered by the reading system which is in the spine must also be accessible which restricts what can be included in the spine or have an appropriate fallback which can be made accessible.

**Comment by mattgarrish** [comment]
> I don't think a11y should be a reason to prevent us from accepting CoreMedia Type to be appearing in spine item without fallback.

Sure, but the problem you'll find is that that is not a consensus opinion and the debate tends to inflame passions. We've had strong objections to images in spine in the past (and not coming from the accessibility community). One of the prime pillars of EPUBs development has been to provide publishers with an accessible format, and there are vendors and publishers who don't want that undermined.

Even if that doesn't stop people from making inaccessible content, there's a difference between authoring content poorly and the format itself encouraging a type of publication that is known to be inaccessible. PDF already fills that inaccessible image space.

**Comment by dauwhe** [comment]
> I still feel it is strange that even web browser could render images "directly" while in EPUB ecosystem publishers/creators are required to provide fallback.

Browsers actually [create the HTML DOM themselves](https://html.spec.whatwg.org/multipage/browsing-the-web.html#read-media) when displaying images "directly:" 

> When an image, video, or audio resource is to be loaded, provided navigation params *navigationParams* and a string type, the user agent should:
>  1. Let *document* be the result of creating and initializing a `Document` object given "html", *type*, and *navigationParams*.
>  2. Append an `html` element to document.
>  3. Append a `head` element to the `html` element.
>  4. Append a `body` element to the `html` element.
>  5. Append an element *host element* for the media, as described below, to the body element.
>  6. Set the appropriate attribute of the element *host element*, as described below, to the address of the image, video, or audio resource.

**Comment by rakutenjeff** [comment]
Yeah, that's why I put double quotation on _directly_. 
As you can see to wrap image in dom tree is web browser's concern but not content creator's concern. That is the thing I wanted to point out.

**Comment by mattgarrish** [comment]
> Browsers actually [create the HTML DOM themselves](https://html.spec.whatwg.org/multipage/browsing-the-web.html#read-media) when displaying images "directly:"

Right, but weren't there questions about how to size the image and render it in the viewport? I seem to remember us getting into how these would work within the fixed layout framework, not that a browser can render them.

**Comment by rakutenjeff** [comment]
For a11y support to force an xhtml fallback does not improve a11y for epub. I think we should provide a way to make book accessible (maybe in the new epub accessibility spec?). A fallback means if a system could not deal with the first item in fallback chain then move on to next one in the chain but since usually web browser and reading system could generally display images without support of xhtml then the fallback chain is actually not useful to provide a11y support.
On the other side, most image only spine item I have seen along with fallback xhtml does not actually provide a11y support inside fallback xhtml (this book is an example https://github.com/IDPF/epub3-samples/blob/master/30/haruko-jpeg/OPS/package.opf#L32 (sorry @mattgarrish :) ) ). 

If the xhtml/svg fallback is mainly for a11y support. Then probably image attaching with a11y information could be more useful. Here is the a11y recommendation for [informative images](https://www.w3.org/WAI/tutorials/images/) by w3c (as following): 
> Informative images: Images that graphically represent concepts and information, typically pictures, photos, and illustrations. The text alternative should be at least a short description conveying the essential information presented by the image.

The same as EPUB, some alternative text (specified in metadata if we already have) should be good enough.

My two cents is, to help providing accessible comic or FXL book is a different layer of discussion (it's very important discussion I totally agree) rather than frame of epub. To provide accessible FXL or comic can be part of discussion of epub accessibility sub spec in wg.

**Comment by mattgarrish** [comment]
> For a11y support to force an xhtml fallback does not improve a11y for epub.

Except that's not why fallbacks are required. The reason fallbacks are required for non-content documents is to ensure support in reading systems, and there are reading systems that won't render images in spine. It's not specifically about accessibility. 

Why only formats with at least some accessibility features have been adopted as content document formats is a different discussion.

But again, this just gets back to the divide between whether you can author something inaccessibly and whether the format encourages that as a core feature. Yes, you can make inaccessible image-based EPUBs right now, but it's a cumbersome nuisance to do, so most people don't bother.

What I'm getting at, though, is that it's not a technical argument you have to solve, but a philosophical one, and there are two sides to this issue with valid points. The result has been deadlock over the years, and I'm not sure anything has changed since we last discussed it.

**Comment by rakutenjeff** [comment]
Want to see if can get further consensus in epub 3.3. But yeah it seems still not a issue for epubcheck.
I kinda think it's more like philosophical topic about design of a tech spec but yes behind it could be a more controversial one that needs to be improving rather than resolving.
Let me close this ticket and create one in wg. I get that we have spent long while (years) discussing this (and each time I forgot about why :) ).

**Comment by rdeltour** [comment]
> epucheck is following the spec, so the issue is one for the working group.

👍 
I'm closing this issue here, but feel free to keep on discussing or commenting (although, as it was previously mentioned, spec updates should preferrably be discussed in the CG/WG).

**Comment by rakutenjeff** [comment]
Thanks @mattgarrish my guess is it's shot down less than pagination support in web browser and MathML :) I will reach out to get more context about the comics and manga discussion happened so far. Look forward to the coming epub spec which might have more clear direction or vision about accessibility.
