### ISSUE TITLE
Changes to core media types in 3.3

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1189]
The current draft of EPUB 3.3 supports the following new core media types:

- Opus (audio/opus) as a core audio type. See https://github.com/w3c/epub-specs/issues/645
- WebP (image/webp) as a core image type. See https://github.com/w3c/epub-specs/issues/1344

**Comment by rdeltour** [comment]
> Should there also be a status label to indicate that these are pending completion of EPUB 3.3 @rdeltour, or is it sufficient just to label them as EPUB 3.3?

Labelling them as EPUB 3.3 works great, thx!
