### ISSUE TITLE
The property 'remote-resources' should be declared in the OPF file.

### ISSUE THREAD

**Issue by anacab03** [w3c/epubcheck#1191]
This message keeps popping up and I'm not sure how to fix it, it's for a book I'm trying to publish #OPF-014 #834

**Comment by rdeltour** [comment]
This message indicates that a contains references to resources located outside the EPUB container (typically, these resources have a URL starting with http:// or https://). This is only allowed by the EPUB specification for special kind of resources; but then, the Content Document (XHTML) referencing these resources should be annotated with the `remote-resources` property in the Package Document.

I'm closing this issue as this is not specifically a bug with EPUBCheck. Please note that this issue tracker is intended to be used to report issues and feature requests only. Other channels are preferred for user support (although there is no official EPUBCheck forum, there are various other places discussing ebook production topics, like forums, Twitter, or StackOverflow) 😊
