### ISSUE TITLE
Documentation errors on the 'Java Library' page

### ISSUE THREAD

**Issue by jiakuan** [w3c/epubcheck#1193]
On this page (https://github.com/w3c/epubcheck/wiki/Library), I found  a few errors which are confusing.

* `EPUBCheck` should be changed to `EpubCheck`
* All occurrences of `org.idpf` should be changed to `org.w3c`. The old groupId didn't work any more.

I couldn't find the **Edit** button, so thought to create an issue here.

**Comment by laudrain** [comment]
@jiakuan EPUBCheck is the official spelling of the tool.

**Comment by mattgarrish** [comment]
@laudrain I believe he's referring to the Java example. The constructor in the code doesn't use the new name:

```
public class EpubCheck implements DocumentValidator
```

**Comment by laudrain** [comment]
ah, ok.

**Comment by jiakuan** [comment]
Yes, I meant the class name in the demo Java code, which is wrong. `EPUBCheck ` doesn't compile.

**Comment by rdeltour** [comment]
good catch, I just fixed the wiki page. Thanks  @jiakuan!
