### ISSUE TITLE
Attempting to Self Publish A Book

### ISSUE THREAD

**Issue by Jamarr5242** [w3c/epubcheck#1195]
I am havign trouble a epub document on IngramSpark. I am receiving the following error message... 

![image](https://user-images.githubusercontent.com/74262698/98711200-b374d180-2352-11eb-8482-7bd501b5b597.png)

How do I fix. Please include screenshots. I am unable to find anything useful on Google and coding is an absolute foreign language to me. Please help.

Thanks,
Jamarr

**Comment by rdeltour** [comment]
The error messages indicate that the file ITECCollatedDraft.xhtml contains references to resources (like images) located outside the EPUB container (typically, these resources have a URL starting with `http://` or `https://`). This is not allowed by the EPUB specification; these resources should be moved to the EPUB, referenced with a relative URL.

I'm closing this issue as this is not specifically a bug with EPUBCheck.  Please note that this issue tracker is intended to be used to report issues and feature requests only. Other channels are preferred for user support (although there is no official EPUBCheck forum, there are various other places discussing ebook production topics, like forums, Twitter, or StackOverflow) 😊
