### ISSUE TITLE
Uploading epub file type for Ingram Spark

### ISSUE THREAD

**Issue by Jamarr5242** [w3c/epubcheck#1196]
I am havign trouble a epub document on IngramSpark. I am receiving the following error message... 

![image](https://user-images.githubusercontent.com/74262698/98711200-b374d180-2352-11eb-8482-7bd501b5b597.png)

How do I fix. Please include screenshots. I am unable to find anything useful on Google and coding is an absolute foreign language to me. Please help.

Thanks,
Jamarr

**Comment by rdeltour** [comment]
Closing as duplicate of #1195
