### ISSUE TITLE
Misleading error message regarding mtable/@rowspacing

### ISSUE THREAD

**Issue by Matt-1** [w3c/epubcheck#1197]
This is a minor issue. I got the following error from epubcheck-4.2.4:

ERROR(RSC-005): [...].xhtml(2,19901): Error while parsing file: value of attribute "rowspacing" is invalid; token "-\jot" invalid; must be a string matching the regular expression "\s*((-?[0-9]*([0-9]\.?|\.[0-9])[0-9]*(e[mx]|in|cm|mm|p[xtc]|%)?)|(negative)?((very){0,2}thi(n|ck)|medium)mathspace)\s*"

The error is certainly justified. However, the error message implies that rowspacing can only contain one value, for example, "1mm". However, values like "1mm 1mm 1mm" are perfectly valid (and accepted by epubcheck). But you wouldn't think that when reading the error message.

**Comment by rdeltour** [comment]
Thanks for the report! I'll look into it.

**Comment by rdeltour** [comment]
I had a closer look at this issue. The message includes only the value in the list which does not conform, it is what is meant by "token" here I guess.

In other words, if you have the attribute `rowspacing="1mm blah 1mm"`, you'll get a message saying `Error while parsing file: value of attribute "rowspacing" is invalid; token "foo" invalid`.

I think that's acceptable. In addition, this message is generated by a third-party schema checker (Jing), so changing it is not straightforward.

I'll mark this issue as `wontfix`, but anyone please feel free to comment if you'd like to add anything!
