### ISSUE TITLE
EPUB2 errors need to be treated at least as warnings in EPUB3 profiles

### ISSUE THREAD

**Issue by acli** [w3c/epubcheck#1199]
In the EPUB2 profile, orphaned files are treated as errors. In the default EPUB3 profile, they don’t even trigger warnings. I know this because at one point I switched my project to EPUB3, and the validation error disappeared.

But Amazon seems to be validating all EPUB files with an EPUB2 profile, so files that validate with zero errors can get rejected by KDP. Worse, KDP is spitting out the misleading error message “There is a broken link in your Table of Contents” when the problem is neither with a broken link nor in a toc.

So I think from a practical standpoint orphaned files need to be at least flagged as warnings, because broken generators might put extra, unused files inside an EPUB, and users need to be warned that this (or other EPUB2 errors that aren’t errors in EPUB3) could be a problem in practice.

**Comment by wareid** [comment]
Hi @acli could you provide some more information on "orphaned" files? I'm not familiar with that term. The error from EPUBCheck would be helpful as well, to help diagnose the issue.

**Comment by acli** [comment]
@wareid I mean files that have no links to them. Sorry for inventing a word.

(I just noticed InDesign by itself won’t cause this; I need to take out links to the unwanted file. But my script that does this has changed too much to produce a usable test case; I’ll need to backtrack or trim it down. I’ll fix the description and have an error message later.)

**Comment by acli** [comment]
I can’t reproduce it. Let me close this and reopen when I figure out what really happened. Sorry.
