### ISSUE TITLE
confusion in ePubCheck 4.2.4 with ERROR(HTM-046) when checking viewport in fxl vs rfl epub

### ISSUE THREAD

**Issue by JackieFei** [w3c/epubcheck#1214]
Test case :

- the viewport (height or width) without proper value, such as `height=705, width=`

ePubCheck 4.2.4 :

- output `ERROR(HTM-046)` in **fixed layout** epub
- but `all pass` in **reflowable** epub with itemref  properties="rendition:layout-pre-paginated".

### Sample 1 :
[fxl_without_viewport_width.epub.zip](https://github.com/w3c/epubcheck/files/6105707/fxl_without_viewport_width.epub.zip)

content.opf
```
<meta property="rendition:layout">pre-paginated</meta>
<meta property="rendition:spread">landscape</meta>
<meta property="rendition:orientation">auto</meta>
```

Cover.xhtml
```
<meta name="viewport" content="height=705, width="/>
```

epubcheck-4.2.4 :

- `ERROR(HTM-046)`: Fixed format item has no viewport defined.

### Sample 2 :
[rfl_without_viewport_width.epub.zip](https://github.com/w3c/epubcheck/files/6105719/rfl_without_viewport_width.epub.zip)

content.opf
```
<itemref idref="Cover.xhtml" properties="rendition:layout-pre-paginated rendition:spread-none rendition:page-spread-center"/>
```

Cover.xhtml
```
<meta name="viewport" content="height=705, width="/>
```

epubcheck-4.2.4 is all pass.

- We think the rfl_without_viewport_width.epub should also output ERROR(`HTM-046`), or `HTM-047` (Html viewport is missing height and/or width.)

reference #419

**Comment by rdeltour** [comment]
Thanks for the report @JackieFei! It looks like a false-negative indeed (an error should probably be reported).

I'll try to have a closer look for the next milestone.
