### ISSUE TITLE
Check whitespace handling in package document schemas

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1224]
EPUB 3.3 has clarified element values in the package document are to be trimmed and have whitespace collapsed. I don't believe this affects anything, as I remember we went through the schematron tests a couple of years back to ensure all values were being normalized (element and attribute), but also no harm in doing another check.

https://github.com/w3c/epub-specs/issues/1528

**Comment by rdeltour** [comment]
I had another look and did not identify any new issue with this. Closing as completed.
