### ISSUE TITLE
No error or warning for incomplete fragment identifiers

### ISSUE THREAD

**Issue by davidchat** [w3c/epubcheck#1228]
I found an issue where incomplete fragment identifiers in an epub did not throw any errors or warnings. The fragment identifiers do not have the filename in them at all, however they are all referencing ids within the same file. An example of how these incorrect fragment identifiers are formed:

`<sup><a href="#a10" id="ab10">10</a></sup>`
`<a href="#ab10" id="a10">10</a>`

**Comment by mattgarrish** [comment]
> The fragment identifiers do not have the filename in them at all, however they are all referencing ids within the same file.

It's not required that there be a filename. When the URL starts with a '#', it's called a same-document reference. It avoids having to write out a specific filename every time you want to refer to a location within the same file, which can be handy if you rename your files and don't want to have to fix all the broken references each time.

Or for the technical definition from RFC 3986:

>  When a URI reference refers to a URI that is, aside from its fragment component (if any), identical to the base URI (Section 5.1), that reference is called a "same-document" reference.  The most frequent examples of same-document references are relative references that are empty or include only the number sign ("#") separator followed by a fragment identifier.
> 
> When a same-document reference is dereferenced for a retrieval action, the target of that reference is defined to be within the same entity (representation, document, or message) as the reference; therefore, a dereference should not result in a new retrieval action.

Hope this helps.

**Comment by davidchat** [comment]
Very helpful, thank you! Makes perfect sense, especially that the fragment identifiers work as expected.
