### ISSUE TITLE
EPUBCheck v4.2.5 wrong path for java?

### ISSUE THREAD

**Issue by shoesforindustry** [w3c/epubcheck#1232]
On my MAC (Big Sur) 11.2.3 (20D91) and EPUBCheck v4.2.5 from Homebrew
My recent upgrade of epubcheck to v4.2.5 started failing with: 

`/usr/local/bin/epubcheck: line 3: /bin/java: No such file or directory
/usr/local/bin/epubcheck: line 3: exec: /bin/java: cannot execute: No such file or directory
`

`usr/local/bin/epubcheck` seems to have a path for the exec of `/bin/java` however Java on my Mac (installed from https://java.com/en/download/) is located in `/usr/bin/java`. I cannot seem to symlink it to `/bin/java`.

If I change the epubcheck file with the correct java path it works.

`#!/bin/bash
export JAVA_HOME=“${JAVA_HOME:-}”
exec “${JAVA_HOME}/usr/bin/java”  -jar “/usr/local/Cellar/epubcheck/4.2.5/libexec/epubcheck.jar” “$@“
`

**Comment by rdeltour** [comment]
It seems to be an issue related to how HomeBrew links to Java. The homebrew formula for EPUBCheck is maintained independently in the [homebrew-core](https://github.com/Homebrew/homebrew-core) project, and we don't control this. You could file an issue there to know more, or perhaps better ask this on their [discussions forum](https://github.com/Homebrew/discussions/discussions).

Also pinging @carlocab, who recently updated the formula for v4.2.5 (thanks! 👍), although at first sight I don't see anything related to the Java path.

**Comment by rdeltour** [comment]
I'm closing this issue as `invalid` since it's not an issue with the core EPUBCheck project, but feel free to keep discussing or commenting there!

**Comment by shoesforindustry** [comment]
Thanks for your assistance rdeltour and in case anyone else comes across the same problem I'm posting my solution here: 
As suggested I checked on the HomeBrew discussion forum and _SMillerDev_ suggested I needed to add JAVA_HOME to (in my case) my `.bash_profile`
[For further info see the HomeBrew Discussion list post:](https://github.com/Homebrew/discussions/discussions/1204#discussioncomment-574801)
