### ISSUE TITLE
Clarify font decryption messaging

### ISSUE THREAD

**Issue by nekennedy** [w3c/epubcheck#1235]
When epubcheck hits an obfuscated font, it doesn't confirm the font is correctly obfuscated. This is fine (I've written something on our end to check) but the message itself is confusing, since "could not" implies that an attempt was made and that there is something wrong with the font obfuscation. The current message reads:
`INFO(RSC-004): [file path](-1,-1): File [font path] could not be decrypted.
`
Could it be:
`INFO(RSC-004): [file path](-1,-1): File [font path] is encrypted, epubcheck does not check validity of encryption.xml
`
Or if we want to keep it really simple:
`INFO(RSC-004): [file path](-1,-1): File [font path] is encrypted`

**Comment by rdeltour** [comment]
Thanks for the suggestion, I agree the wording isn't ideal and your proposal is an improvement 👍
