### ISSUE TITLE
hyperlink to non-standard resource (PDF or Image)

### ISSUE THREAD

**Issue by prithiviyaso** [w3c/epubcheck#1243]
Hi,

I have found error "Reference to non-standard resource type found" in EPUBChecker 4.2.4 and 4.2.5. Please confirm is this ignorable error or need to fix, if need to fix please help how to fix this type of errors.

EPUBChecker Error:
ERROR(RSC-010): 9781568584829.epub/OEBPS/Maps0.xhtml(16,66): Reference to non-standard resource type found.

Internal resource:
<p class="aut">**<a href="source/ch19.pdf">**ch19</a></p>

**Comment by mattgarrish** [comment]
PDFs are not core media types in EPUB, so if you want to hyperlink to one in the reading order you have to provide a manifest fallback to an XHTML or SVG document.

Whether you ignore the error or not is your decision, but unless a reading system supports PDF the link won't work.

At any rate, epubcheck is reporting the issue properly, so there isn't anything to fix here.

**Comment by prithiviyaso** [comment]
@mattgarrish Thank you so much for your help
