### ISSUE TITLE
Request for reconsideration: ERROR MED_015 (Media overlay text references must be in reading order) 

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epubcheck#1244]
I understand that this newly-added check ensures what has been required by the EPUB3 MO specification.  This requirement is stated as "_The ordering of these elements MUST match the default reading order of the EPUB Content Document._"  But there appear to be a number of Japanese DAISY publications that rely on some mismatch between the reading order and the occurrence order in MO documents.

We understand that some EPUB software such as the DAISY pipeline does not work when such mismatch occurs in an EPUB or DAISY publication.  But Japanese DAISY people have used EPUB or DAISY readers that can live with this error. 

This issue is quite similar to the mismatch between the navigation document and the spine document.  We thus propose that such mismatch be treated as a warning rather than an error.

**Comment by mattgarrish** [comment]
This is covered in https://github.com/w3c/epubcheck/issues/1225

Requirements for ordering is covered by the accessibility specification going forward.

But making a formal change to epubcheck probably depends on EPUB 3.3 becoming a REC.

**Comment by murata2makoto** [comment]
Please understand that this issue has huge impacts on the Japanese DAISY Consortium.  I hear screams.

**Comment by rdeltour** [comment]
Let's move the discussion to #1225, I'll close this one as duplicate.
