### ISSUE TITLE
SVG validity is not normative

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1254]
The EPUB 3.3 specification only requires that SVG be well-formed, have unique IDs and conform to the restrictions in https://www.w3.org/TR/epub-33/#sec-svg-restrictions

This is true whether the svg is a stand-alone file or embedded within html, so will require removing embedded svg from html validation and checking separately. (Assume this can be done fairly trivially with nvdl?)

There's still a desire to output validity issues for authors who want them, however, but without having them be warnings or errors, so this change will also require looking at whether those messages can be reassigned to info level (our discretion on how to implement this, so could also be something else like a flag to turn on for full validation).

See https://github.com/w3c/epub-specs/issues/1323

**Comment by rdeltour** [comment]
Done in #1365
