### ISSUE TITLE
Item id "ncx" was not found in the manifest

### ISSUE THREAD

**Issue by MatthewCaseres** [w3c/epubcheck#1255]
I'm getting this error on an EPUB I'm making, along with

```
Error while parsing file: spine element toc attribute must reference the NCX manifest item (referenced media type was "")
```

I'm not very knowledgeable but I think .ncx files are legacy?

**Comment by dauwhe** [comment]
If there's no NCX, you must delete the `toc` attribute on the `spine` element.

**Comment by MatthewCaseres** [comment]
Thank you!
