### ISSUE TITLE
Tooling needs to switch from Travis CI  to GitHub action

### ISSUE THREAD

**Issue by plehegar** [w3c/epubcheck#1261]
Travis CI has stopped providing the service and we need to switch to GitHub action asap.

I will need to deactivate Travis on this repository soonish to avoid having it using precious resources.

If you need help switching away from Travis CI to GitHub action, please let me know.

**Comment by rdeltour** [comment]
Can you please give a bit more context? Travis CI ran correctly on [recent builds](https://travis-ci.com/github/w3c/epubcheck/builds/231245341) and I haven't heard of them discontinuing free CI for OSS projects?

I saw some issues on PRs on W3C spec repos, but was assuming this was related to spec-building repos only.

**Comment by mattgarrish** [comment]
> I haven't heard of them discontinuing free CI for OSS projects?

See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing/#building-on-a-public-repositories-only

**Comment by rdeltour** [comment]
Oh, I missed that, thanks @mattgarrish!

**Comment by plehegar** [comment]
More context: Travis CI stopped working 2 weeks ago since they no longer support free build for their open source projects. We switched to a plan that gave us 10k credits for the w3c github org (so that's for all of the repos under github.com/w3c) and we already used half of them.  This repo used 1k in the past few days. We have been going through all of repos to switch them to use GitHub actions instead.

**Comment by rdeltour** [comment]
Thanks @plehegar 😊👍
I've started the migration to GitHub Actions, and removed the Travis Config. I don't know if there's anything else to do to deactivate Travis?

**Comment by plehegar** [comment]
I updated the [Travis CI settings](https://travis-ci.com/github/w3c/epubcheck/settings) to deactivate it.

Thank you so much @rdeltour for doing the transition and sorry about the short timeline.

**Comment by rdeltour** [comment]
OK! You're welcome 😊.

I'll close this issue and we'll keep on improving the GitHub Actions setup in #1264
