### ISSUE TITLE
Changes to path handling in OCF

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1290]
You'll probably want to expand on this issue, @rdeltour, since you made the changes, but I expect epubcheck will need to be updated to handle the new URL parsing rules in https://github.com/w3c/epub-specs/issues/1374 and https://github.com/w3c/epub-specs/issues/1888

It looks like the changes now make path-absolute url strings errors, too, not the warnings they were originally set to in https://github.com/w3c/epub-specs/pull/1725.

**Comment by rdeltour** [comment]
This is reported as `RSC-026` (error) since #1396
