### ISSUE TITLE
INF-001 message is ambiguous in the JSON output

### ISSUE THREAD

**Issue by icklecows** [w3c/epubcheck#1295]
If you get the message INF-001, it begins: "The previous rule is under review..." which is fine in the STDOUT output, but in the JSON format, the messages aren't in the same order, so it's hard to identify which issue might be reviewed.  Is it possible to include the issue ID instead of "The previous rule" so that it can be related to the original issue regardless of message output order?

**Comment by rdeltour** [comment]
Yes it makes sense. Thanks for the PR! 👍
I'll try to review shortly.

**Comment by rdeltour** [comment]
Closed in 5a6dc10a662c06fc3f11401dbcccec6151aa83a3
