### ISSUE TITLE
media type mismatches on object reported as errors

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1308]
This test in content-publication.feature checks that the media types declared on `object` tags match the manifest.

>  Scenario: Report an `object` element with a media type not matching the Package Document declaration
>    When checking EPUB 'content-xhtml-object-mediatype-mismatch-error'
>    Then error OPF-013 is reported
>    And no other errors or warnings are reported

I think I finally tracked this down to an EPUB 2 requirement:

>  The MIME media type values for the codetype and type attributes must match those specified in the Publication's Manifest.

http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.3.6

But this requirement didn't come forward to EPUB 3.

**Comment by rdeltour** [comment]
I didn't remember that `OPF-013` specifically originated from an EPUB 2 requirement… nice spelunking.

That said, I think it does makes sense to warn when the MIME type of a resource declared in XHTML differs from the MIME type declared in the package document. Not only for `object` elements, but also for `source` elements and others.

I don't see a legit use case for having two different MIME types, so it would be either an authoring error or a malicious intent. So I think it is one of those cases where EPUBCheck can issue a warning even if it does not specifically match a SHOULD in the spec. What do you think @mattgarrish?

I've kept `OPF-013` as a warning in v5.0.0-beta-3 (and extended to other elements).

I'm keeping this issue open for a little while, and moving it to the v5.0.0 final milestone.

**Comment by rdeltour** [comment]
Closing this issue. Let's reopen if people complain about `OPF-013` being a warning.
