### ISSUE TITLE
dublicate "id" in <section> 

### ISSUE THREAD

**Issue by MyDK** [w3c/epubcheck#1331]
I noticed this by coincidence: EPUBCheck v.4.6.2 allows dublicate ids in `section ` elements in two different xhtml docs inside my EPUB 3 file. - Should identical ids not be flagged as errors?

**Comment by mattgarrish** [comment]
> dublicate ids in `section ` elements in two different xhtml docs

That's only a problem when an ID is duplicated in the same file as it breaks the ability to link to the fragments.

Reusing IDs across documents isn't the greatest practice, as you could wind up referencing the wrong file and still have a valid link, but as it's not a common problem I'm not surprised epubcheck doesn't test for it even as a usage message.

**Comment by MyDK** [comment]
Thanks Matt. 
I thought it was a no-go.
One could argue, that the authoring software (InDesign) should produce non-identical ids by default ... but as long as file is valid, all is well 😁
