### ISSUE TITLE
hreflang in a package document link element is not accepted (error?)

### ISSUE THREAD

**Issue by iherman** [w3c/epubcheck#1339]
The title tells it all: if my package document includes something like:

```xml
<package …>
  <metadata>
    ...
    <link rel="dcterms:description" href="description.xhtml" media-type="application/xhtml+xml" 
        hreflang="fr"/>
  </metadata>
</package>
```

The error message I see is:

```
ERROR(RSC-005): pkg-linked-records_hreflang.epub/EPUB/package.opf(12,112): Error while parsing 
file: attribute "hreflang" not allowed here; expected attribute "id", "properties" or "refines"
```

Which seems to contradict [the link element definition](http://localhost:8001/LocalData/github/EPUB/epub-specs/epub33/core/#sec-link-elem).

**Comment by mattgarrish** [comment]
We only added it in 3.3. There's already an issue to include it here: https://github.com/w3c/epubcheck/issues/1219

**Comment by rdeltour** [comment]
Damn, it should be there since alpha-1. I'll have a closer look.

**Comment by mattgarrish** [comment]
This appears to be fixed in the latest beta release.

**Comment by iherman** [comment]
Should I close this? It is fixed in the latest beta...
