### ISSUE TITLE
Usage option documentation

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epubcheck#1343]
I can’t seem to find any documentation of the usage option `-u / --usage`: 

- Is there a complete list of messages?
- What is their level of severity (purely informative / action suggested / action required)?
- Can the output be limited to certain severity levels? Some messages seem to be purely informative (e.g., CSS-028, HTM-050, NAV-002), other give very valuable information (e.g., CSS-025, OPF-090) but can easily get buried under “a lot of noise”, like hundreds of HTM-050 messages.

A wiki page similar to the [error message documentation](https://github.com/w3c/epubcheck/wiki/Errors) would be most welcome.

**Comment by rdeltour** [comment]
I'm closing this issue, as we do have existing (albeit maybe incomplete) documentation, and the website improvement is an ongoing effort. But please feel free and welcome to keep on commenting here, or contribute a pull request with improvements!
