### ISSUE TITLE
Saved epubs when not using -save mode

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1351]
I just noticed with the beta 2 release that when I run epubcheck on an expanded directory I end up with a packaged ".epub" file whether or not I also specify the -save option.

This is on Windows 10 using java se 17.0.4.1.

**Comment by rdeltour** [comment]
@mattgarrish I could not reproduce this in v5.0.0-beta-3. Can you confirm?

**Comment by rdeltour** [comment]
Closing this one, as it could not be reproduced with the latest builds. @mattgarrish feel free to reopen if needed!
