### ISSUE TITLE
Windows issue: Required META-INF/container.xml resource could not be found.

### ISSUE THREAD

**Issue by jbescos** [w3c/epubcheck#1357]
This issue happens having the file in META-INF/container.xml in the epub.

I was debugging this, the issue is the Zip was created having the ZipEntry in Windows: META-INF\container.xml

But unfortunately, this check is not passing:
https://github.com/w3c/epubcheck/blob/58a61935a8fdd2875539be58dc6bc1ed87615740/src/main/java/com/adobe/epubcheck/ocf/OCFChecker.java#L116

This is because the value of that constant contains this path: META-INF/container.xml
https://github.com/w3c/epubcheck/blob/58a61935a8fdd2875539be58dc6bc1ed87615740/src/main/java/com/adobe/epubcheck/ocf/OCFData.java#L9

It is failing to pass that check, even having the file inside the ZIP, because of that.

Possible solutions:
1. Fix by user: Make the epub zip file in Linux/Mac
2. Fix by user: When you are building the zip, add the next to the ZipEntry: ZipEntry zipEntry = new ZipEntry(zipEntryName.replaceAll("\\\\", "/"));
3. Fix by epubcheck: Do not use ZipFile#getEntry. Walk through the zip entries instead.

**Comment by rdeltour** [comment]
@jbescos  thanks for the report, and sorry for the late answer!

I will try to create a test EPUB to see if I can reproduce that, and cover that case in EPUBCheck's internal test suite.

That said:
- the code related to the OCF ZIP container has been refactored in v5.0.0-beta-3, so I'm not sure this issue remains
- a zip using `\` as the path separator should be rejected by EPUBCheck anyways, as this is disallowed by the [ZIP format](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT)

> 4.4.17 file name: (Variable)
>
> 4.4.17.1 The name of the file, with optional relative path.
> The path stored MUST NOT contain a drive or
> device letter, or a leading slash.  All slashes
> MUST be forward slashes '/' as opposed to
> backwards slashes '\' for compatibility with Amiga
> and UNIX file systems etc.  If input came from standard
> input, there is no file name field.

So I think the issue would have to be reported to the tool which created the EPUB in the first place. Do you know how the EPUB was produced, specifically which tool was used to create the ZIP container?

**Comment by jbescos** [comment]
If '\' is not allowed in ZIP, then it is a problem in the tool. I am going to close this, thank you @rdeltour for reviewing this.
