### ISSUE TITLE
Non-ascii characters in file names reported as warnings

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1384]
I noticed epubcheck reports file names if they have non-ascii characters in them, but this isn't a recommendation of the specification. Restricting to ascii is only in a note about possible issues with old reading systems, tools, etc.

Given the impact of warnings on acceptance by vendors, we should consider bumping this down to a usage message. Otherwise, we're creating a barrier that doesn't exist in the spec.

**Comment by rdeltour** [comment]
I could not reproduce this. EPUBCheck reports non-ascii characters, but only as a usage message (`PKG-012`).

I still opened #1455 to rename a couple test cases which still had a `-warning` suffix in their name despite being only reported as usage (could that be the source of confusion?).

I also added the spec ref tags to these tests, as they are useful to show that non-ASCII file names are accepted as valid.
