### ISSUE TITLE
SVG CSS Error (CSS-030) being reported in 5.0.0-beta-3 but not earlier versions.

### ISSUE THREAD

**Issue by wareid** [w3c/epubcheck#1450]
When testing the file `mol-timing-synchronization_svg.epub` against EPUBCheck versions for EPUB 3.2 and EPUB 3.3, we are getting different results. 

EPUBCheck (v.4.2.6) for EPUB 3.2 validates. 

EPUBCheck (v.5.0.0-alpha-1) also validates. 

EPUBCheck (v.5.0.0-beta-3) for EPUB 3.3 returns:
`ERROR(CSS-030): /GitHub/epub-tests/tests/mol-timing-synchronization_svg.epub/EPUB/mobydick.svg(55,7): The package document declares media overlays styling class names but no CSS was found in the content document.`

This error seems to come back regardless of how CSS is referenced in the SVG file. I tested it against: 

- CSS directly added within a `<style>` element 
- CSS file referenced via `@import` in the `<style>` element 
- CSS file linked via the `<link>` element

**Comment by rdeltour** [comment]
Ah, I guess this check wasn’t properly tested with SVG content docs. Good catch! 👍

**Comment by rdeltour** [comment]
ref: #1402 where CSS-030 was introduced
