### ISSUE TITLE
RTL Language ePub Issue

### ISSUE THREAD

**Issue by MedoHamdani** [w3c/epubcheck#1462]
The Issue:

Hello everyone,
This error keeps appearing every time the option of RTL is introduced in the spine. The purpose of this line of code is to make the flow of ePub books on Google Books from right to left, especially when you read from a tablet or a mobile.

The Error:
Error while parsing file: attribute "page-progression-direction" not allowed here; expected attribute "id" or "toc"

The Image:
![image](https://user-images.githubusercontent.com/10483224/207560977-07c59016-faf2-481b-98a5-f8b01910e472.png)

If this issue has been tackled-down in any other article, please direct me to it.

Thanks,

Medo Hamdani

**Comment by mattgarrish** [comment]
From the message, it appears you've created an EPUB 2 file. EPUB 2 didn't include the `page-progression-direction` attribute; it was only introduced in EPUB 3.

Support for internationalization in EPUB 2 isn't very good. That was one of the major upgrades in EPUB 3. If possible, I'd recommend converting your file to EPUB 3.

**Comment by MedoHamdani** [comment]
> From the message, it appears you've created an EPUB 2 file. EPUB 2 didn't include the `page-progression-direction` attribute; it was only introduced in EPUB 3.
> 
> Support for internationalization in EPUB 2 isn't very good. That was one of the major upgrades in EPUB 3. If possible, I'd recommend converting your file to EPUB 3.

Thank you Matt for your reply, however, it seems Google Docus options to export to ePub don't work, and don't know for sure what version would be the output.
Currently, Calibre is being used to convert Docx files into ePub, and will check if there is a possibility to get it into EPUB 3.
If you would recommend any software to do so, please do let me know.
Thanks again

Medo Hamdani

**Comment by mattgarrish** [comment]
> Calibre is being used to convert Docx files into ePub, and will check if there is a possibility to get it into EPUB 3.

I don't use the program, but according to this thread you can convert files: http://www.mobileread.mobi/forums/showthread.php?t=334737

> If you would recommend any software to do so, please do let me know.

If you're converting Word files, the DAISY Consortium created a plugin that will turn docx files to EPUB 3. You can read more about it, and download it, here: https://daisy.org/activities/software/wordtoepub/

**Comment by rdeltour** [comment]
Closing this, as it does not seem to be a bug with EPUBCheck 🙂
