### ISSUE TITLE
Unable to delete generated archive. on  --mode exp

### ISSUE THREAD

**Issue by jarupxx** [w3c/epubcheck#1477]
When verifying a folder expanded with epubcheck 5.0.0, epub files are not deleted when an error occurs.
Run it from the command line: The epubfile is expanded epub folder.

>C:\Desktop\epubcheck-5.0.0>java -jar epubcheck.jar --mode exp epubfile
>EPUB version 3.3 のルールを使って検証します.
>ERROR(OPF-014): .\epubfiles.epub/OEBPS/Text/cover_page.xhtml(-1,-1): プロパティ "svg" をOPFで宣言し
>てください.
>WARNING(HTM-025): .\epubfiles.epub/OEBPS/Text/part0001.xhtml(93,66): 登録されていないURI schemeがhrefで検出されました.
>WARNING(NAV-011): .\epubfiles.epub/OEBPS/Text/nav.xhtml(25,42): "toc" nav は閲覧順でなければなりません; リンクターゲット "OEBPS/Text/cover_page.xhtml" は spine 順で前述のリンクのターゲットの前になるようにしてください.
>
>チェックは終了しましたがエラーが検出されました
>Unable to delete generated archive.
>メッセージ: 0 件の致命的エラー / 3 件のエラー / 11 件の警告 / 0 件の情報
>
>EPUBCheck 完了

Windows 11 22H2
Java SE 8u361

**Comment by jarupxx** [comment]
In this case EPUBCheck v4.2.6 will delete the epub file. Another Windows 10 PC have the same issue.

**Comment by rdeltour** [comment]
Thanks for the report, and apologies for the late reply.

Does this error still occurs with the latest EPUBCheck version?
I was not able to reproduce.

This might be due to your local environment (for example file permissions).

**Comment by jarupxx** [comment]
It's not a problem. Don't worry about it.

No longer this errors with the latest EPUBCheck version.
