### ISSUE TITLE
Version 5.0: Exception in thread "main" ...

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epubcheck#1478]
I tested the epubcheck 5 on debian linux.
Instead of testing the book I only got this message:

~/ePub/epubcheck/epubcheck-5.0.0.jar *.epub
Exception in thread "main" java.lang.NoClassDefFoundError: io/mola/galimatias/GalimatiasParseException
        at com.adobe.epubcheck.tool.Checker.main(Checker.java:30)
Caused by: java.lang.ClassNotFoundException: io.mola.galimatias.GalimatiasParseException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more

**Comment by rdeltour** [comment]
Did you extract the `.jar` file out of its parent directory? It needs to be next to the `lib` directory so that 3d-party dependencies are in the class path…

**Comment by Doktorchen** [comment]
Presumably the main problem is, that you do not provide a zip-archive anymore including all necessary files and directories as for previous versions.
What I downloaded as version 5 has only a size of 1.2 MiB, previous zip-archives have one order of magnitude more content - including a lib directory, licences, changelog, readme.
Something seems to be missing.
Why not to provide such a complete zip-archive as for previous versions - this requires no further diving into details for people just wanting to check EPUBs.

**Comment by Doktorchen** [comment]
I looked intensively on this page, but found no download at all.
I even looked in the source code of the page for 'zip' or 'ZIP' - without a result.
The SVG with 'downloads@5.0.0' is included in an a element pointing to this SVG file again.
Therefore I looked at this Maven Central Repository page and found only this jar file named epubcheck-5.0.0.jar.
Can you provide a precise link to the zip file? ;o)

**Comment by rdeltour** [comment]
Here’s a direct link:
https://github.com/w3c/epubcheck/releases/download/v5.0.0/epubcheck-5.0.0.zip

I checked on different browsers and different devices and could find the link at the usual place (under the "assets" expandable area). Maybe an extension is hiding it in your setup?

**Comment by Doktorchen** [comment]
Thanks, this zip archive works.

But I cannot see any link in assets, but an animated SVG, some buttons in a form.
Even with activated script interpretation for the two github domains no relevant changes - what happened to the simple method to set a link declaratively with an a-element?

I have never seen an element include-fragment in (X)HTML before - maybe my browser as well (SeaMonkey 2.53) ... maybe the github-server did not replace this properly or in different ways for different browers?
But if the link is somehow generated by this mysterious element - or not, this might be the source of the problem.
However, the CSS-animated SVG (seems variant tiny 1.2) in it is displayed properly.
