### ISSUE TITLE
URI escaped filepaths not always correctly identified

### ISSUE THREAD

**Issue by nekennedy** [w3c/epubcheck#1479]
When I have a URI-escaped file path in the opf and the HTML, I get a single error message:
`ERROR(RSC-001): [path to my epub]/OEBPS/images/n%26logo.jpg(-1,-1): File "OEBPS/images/n%26logo.jpg" could not be found.
`
When I use html escaping (converting %26 to `&amp;` or %2B to +) the file passes.

When I use a space in the file path and URI-escape it (using %20) the file passes, but if I don't escape it the file fails.

I would expect all URI escaped characters to function correctly and consistently regardless of what character they are replacing.

We have pretty strict requirements for our current workflows, so this doesn't have a huge impact on our frontlist. However, it is a problem for our backlist and (I suspect) many other publishers.

**Comment by rdeltour** [comment]
> I would expect all URI escaped characters to function correctly and consistently regardless of what character they are replacing.

Agreed, looks like a bug. I'll have a look for the next maintenance release. Thanks for the report Naomi!
