### ISSUE TITLE
Messages for CSS_004 and RSC_028 say "%1%s" instead of "%1$s"

### ISSUE THREAD

**Issue by walmsleyph** [w3c/epubcheck#1480]
Hi!  The messages for both CSS_004 and RSC_028 say "%1%s" instead of "%1$s" (in all the languages I checked). As a result, the message comes out looking like this in the report:

  XML documents must be encoded in UTF-8, but %s was detected.

(I tried fixing it with custom messages, but then I got CHK_004, fair enough.)

 Not a big deal, but an easy fix!

Thanks.

**Comment by rdeltour** [comment]
Oops, thanks for the report @walmsleyph, good catch!
