### ISSUE TITLE
Fragment identifier is not defined.

### ISSUE THREAD

**Issue by Scadi2** [w3c/epubcheck#1482]
I include PDF's in the epub as follows:
` <object data="Authorship.pdf#view=FitV" type="application/pdf" style="width:100%; height:100vh"></object>`

"#view=FitV" is necessary for the pdf to automatically fit on the display/monitor without being cut off.
However, this leads to the above error message.

**Comment by rdeltour** [comment]
Looks like a bug, I'll have a look for the next maintenance release. Thanks for the report!

**Comment by Scadi2** [comment]
Presumably, the error occurs everywhere where a URL is given but there is no link:
<embed src="bla#xyz" pluginspage="bla#xyz"
<link href="bla#xyz"
<iframe src="bla#xyz"
<script src="bla#xyz"
<img src="bla#xyz"
<form action="bla#xyz"
<object data="bla#xyz"
<picture src="bla#xyz" srcset="bla#xyz"
<source src="bla#xyz" srcset="bla#xyz"
<video src="bla#xyz" poster="bla#xyz"
<audio src="bla#xyz"
...
