### ISSUE TITLE
does not work with UNC paths

### ISSUE THREAD

**Issue by nverwer** [w3c/epubcheck#1485]
This issue occurs in epub-check 5.0.0, when run from the command-line.
The issue did not occur in epub-check 4.2.6, and probably other versions in the 4.x.y range.

Epub-check 5.0.0 cannot handle UNC paths, also known as Windows network paths.
For instance, when the input is something like `\\fileserver\Export$\Books\my-book.epub`, or variations of this using forward slashes, with or without 'file:' protocol, either the file cannot be found or the following error is produced:

```
     [exec] java.lang.IllegalArgumentException: URI has an authority component
     [exec] 	at java.base/java.io.File.&lt;init&gt;(File.java:425)
     [exec] 	at com.adobe.epubcheck.opf.ValidationContext.computePath(ValidationContext.java:168)
     [exec] 	at com.adobe.epubcheck.opf.ValidationContext.&lt;init&gt;(ValidationContext.java:147)
     [exec] 	at com.adobe.epubcheck.opf.ValidationContext.&lt;init&gt;(ValidationContext.java:43)
     [exec] 	at com.adobe.epubcheck.opf.ValidationContext$ValidationContextBuilder.build(ValidationContext.java:355)
     [exec] 	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:203)
     [exec] 	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:320)
     [exec] 	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:145)
     [exec] 	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
```

It looks like this is caused by `io.mola.galimatias.URL.toJavaURI()`.

**Comment by rdeltour** [comment]
Looks like a regression bug, thanks for the report @nverwer!
