### ISSUE TITLE
NoClassDefFoundError OCFMetaFileChecker

### ISSUE THREAD

**Issue by Richie94** [w3c/epubcheck#1493]
Hey there,

I have the strange case, that sometimes in our CI-pipeline, I randomly get this error here:
```
java.lang.NoClassDefFoundError: Could not initialize class com.adobe.epubcheck.ocf.OCFMetaFileChecker
	at com.adobe.epubcheck.ocf.OCFChecker.checkOtherMetaFiles(OCFChecker.java:483)
	at com.adobe.epubcheck.ocf.OCFChecker.check(OCFChecker.java:156)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:218)
```

Locally I never had this, in our CI its like 30% of the time the case.
I am using 
```
<dependency>
            <groupId>org.w3c</groupId>
            <artifactId>epubcheck</artifactId>
            <version>5.0.0</version>
        </dependency>
```

Edit: I realized NoClassDefFoundError != ClassNotFound and that there is always some stackoverflow exception which is not completely logged, I try to provide more information on the next fail.

**Comment by rdeltour** [comment]
`NoClassDefFoundError` typically happen when the Java runtime cannot find EPUBCheck's library dependencies (`.jar` files). The solution depends on how you run EPUBCheck, so it is likely dependent on your CI pipeline. If you're using the default command line distribution, make sure the `lib` directory is next to the main EPUBCheck `.jar` file.

See also answers in the previous issues with [similar questions](https://github.com/w3c/epubcheck/issues?q=is%3Aissue+NoClassDefFoundError).

I'm closing as invalid this as it does not seem to be a bug with EPUBCheck. But feel free to keep on commenting here, or reopen if you do think there is indeed a bug somewhere.
