### ISSUE TITLE
cite attribute to URI/IRI results in error message in version 5?

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epubcheck#1495]
Content like

```xml
<q cite="https://www.gesetze-im-internet.de/urhg/__2.html">
```

results in an error message in ebpubcheck 5.0 like:

```
Remote resource reference is not allowed in this context; resource "https://www.gesetze-im-internet.de/urhg/__2.html" must be located in the EPUB container.
```

I could not find such a restriction in EPUB 3.3.
With href of a this generates no error message.
Of course, one can point to a bibliography entry with the cite attribute, but is this really required, intended or a bug?

**Comment by mattgarrish** [comment]
> I could not find such a restriction in EPUB 3.3.

There isn't one on the cite attribute, so sounds like a bug. The attribute is just metadata, with the (theoretical) possibility of the URL being hyperlinked out to, neither of which violates EPUB's resource location restrictions.
