### ISSUE TITLE
Un used files (images) not shows in warning for EPUBChecker 5.0.0

### ISSUE THREAD

**Issue by prithiviyaso** [w3c/epubcheck#1496]
Hi Team,

As we verified using EPUBChecker 5.0.0 with Rule 3.3. The Unused Files (Images) warning is not displayed in the new version, but the warnings are displayed in epubcheck-4.2.6 with 3.2 Rule, as shown below.

Validating using EPUB version 3.2 rules.
WARNING(OPF-003): $$$.epub(-1,-1): Item "OEBPS/images/Art_P25a.jpg" exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): $$$.epub(-1,-1): Item "OEBPS/images/Art_P57a.jpg" exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): $$$.epub(-1,-1): Item "OEBPS/images/Art_P57b.jpg" exists in the EPUB, but is not declared in the OPF manifest.

However, the most recent version of epubcheck (5.0.0) with 3.3 Rule does not display the above Warnings.

Customers have complained that there are unused images in the ePub file. Please verify and take the appropriate action right away.

Thanks,
Prithiviraj M

**Comment by prithiviyaso** [comment]
Hi Matt,

Thank you for your responses. Could you kindly advise on how to enable (turn on) the usage message while epubcheck is running?


Thanks,
Prithiviraj M

**Comment by mattgarrish** [comment]
Start it with the `-u` or --usage` parameters. You can find more information here: https://github.com/w3c/epubcheck/wiki/Running
