### ISSUE TITLE
Index profile: Add support for index-locator being a child of index-term

### ISSUE THREAD

**Issue by japotrad** [w3c/epubcheck#1498]
Epubcheck 5.0.0 mistakenly generates these 2 RSC-005 error when parsing the pattern below (from EPUB Indexes 1.0  Recommended Specification 26 August 2015): 
- An "index-entry" must have at least one child with the type "index-entry-list" or "index-locator-list" or "index-locator", "index-locator-range" or "index-editor-note" or "index-xref-preferred" or "index-xref-related".
- The "index-locator" type is only allowed on children of elements with the (possibly implied) type "index-entry" or descendants of "index-locator-list" or "index-range".

https://idpf.org/epub/idx/epub-indexes.html#ex17
The index term may also serve as the human-readable string for the locator:
```
<span epub:type="index-term">
	<a epub:type="index-locator" href="...">Berlin</a>
</span>
<span epub:type="index-term">
	<a epub:type="index-locator" href="...">Paris</a>
</span>
```

**Comment by rdeltour** [comment]
It seems example 17 in the spec is wrong, as it contradicts the definition of `index-locator`:

> **Structural Semantics Vocabulary**
> `index-locator`
>
> **Definition**
> Reference to indexed content
> 
> **Required Parent Context**
> `index-entry`, `index-locator-list`, or `index-locator-range`

So the error report in EPUBCheck looks legit.

In any case, the EPUB Indexes specification is basically dead now, as it was never largely adopted and implemented. EPUBCheck support for EPUB Indexes may be removed in a later update.

I'm closing this as won't fix, but of course feel free to keep on commenting here!

**Comment by mattgarrish** [comment]
> the EPUB Indexes specification is basically dead now

The PMWG should probably look at doing something about these old specs. If we can't modify the old idpf.org files, maybe we can at least publish a note to let people know where things currently stand with them?

We have stuff like alt style tags and CFIs that still sort of exist but aren't widely implemented (or aren't author-facing in the case of CFIs), to all the edupub specs, previews, indexes, dictionaries, etc. that never really went anywhere.

@iherman @wareid @dauwhe @TzviyaSiegman
