### ISSUE TITLE
Plugin refused

### ISSUE THREAD

**Issue by Wim-Stijnman** [w3c/epubcheck#1517]
On my brand new PC with fresh Sigil (1.9.30), new Java, new Python, Sigil reports Epubcheck 5.0.1 as well as 5.0.0 as an invalid plugin. Tried Epubcheck 4.2.6, same failure.
Please investigate.
Wim Stijnman

**Comment by mattgarrish** [comment]
You should take this issue to the [sigil support forums](https://sigil-ebook.com/sigil/support/). They'll be able to better help you figure out what your problem is.
