### ISSUE TITLE
epubcheck 5.0.1 for EPUB2: content model for XHTML1.1 del and ins?

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epubcheck#1522]
Looks like version 5 gets the content modell for del and ins wrong for EPUB2 using XHTML1.1.
XHTML 1.1 allows 'flow mix' - block and inline, epubcheck 5.0.1 does not want block.

Something like
```
<del datetime="2011-09-02" 
     cite="#Z">
<h1>Title Old</h1>
</del>
<ins datetime="2011-09-02" 
     cite="#Z">
<h1>Title New</h1>
</ins>
```
results in:
```
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): XHTML_ref.epub/Inhalt/test3.xhtml(54,5): Error while parsing file: element "h1" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")
ERROR(RSC-005): XHTML_ref.epub/Inhalt/test3.xhtml(58,5): Error while parsing file: element "h1" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")
```

Same test with EPUB3/HTML5 results in no messages.

(edited by @rdeltour for formatting)

**Comment by Doktorchen** [comment]
Well, it seems to have problems with the XHTML code here, lets try this:
[del datetime="2011-09-02" 
     cite="#Z"]
[h1]Old Title[/h1]
[/del]
[ins datetime="2011-09-02" 
     cite="#Z"]
[h1]New Title[/h1]
[/ins]

**Comment by mattgarrish** [comment]
You use backticks to escape markup. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by rdeltour** [comment]
Looks like a bug in the schema, I'll look into it.
