### ISSUE TITLE
CREATION_DATE not populated in report info

### ISSUE THREAD

**Issue by karenhanson** [w3c/epubcheck#1532]
I noticed while testing that Creation Date is no longer populated in the report. Is this a permanent change? When I looked at the code, I saw this is commented out with a note to fix it in the future, so it looks like there are plans to bring it back?:
https://github.com/w3c/epubcheck/blob/d895f6641f100291e0c601218dc666330d55ef54/src/main/java/com/adobe/epubcheck/ocf/OCFChecker.java#L253-L262

**Comment by rdeltour** [comment]
> I saw this is commented out with a note to fix it in the future, so it looks like there are plans to bring it back?:

Oh absolutely yes, thanks for the report. It looks like I missed this one when refactoring the container parsing code. I'm adding it to the next maintenance release.

**Comment by karenhanson** [comment]
@rdeltour Sorry to be a nuisance, but do you have a rough date for the next maintenance release? Just asking as I need to make a decision about whether to submit a [PR to upgrade to EPUBCheck 5.1.0 in JHOVE](https://github.com/openpreserve/jhove/issues/857) or hold it back a bit longer. If it's likely to be more than a few months away I may do the PR now and add the CREATION_DATE field back in when it's available.

**Comment by rdeltour** [comment]
@karenhanson sorry for the late answer. The next maintenance release should be published at the end of this month!
