### ISSUE TITLE
New graphical user interface EPUBCheckFX

### ISSUE THREAD

**Issue by Wandmalfarbe** [w3c/epubcheck#1540]
I made a new graphical user interface EPUBCheckFX because I was not satisfied with the existing GUIs:

* https://github.com/Wandmalfarbe/EPUBCheckFX

I would like to include it in the list of EPUBCheck apps at https://www.w3.org/publishing/epubcheck/docs/apps-and-tools/#epubcheck-apps, but could not find an up-to-date repository. Should I send a PR to this GitHub repository https://github.com/daisy/epubcheck-website? It seems abandoned and out of date ...

I would also like to add my application to the Wiki at https://github.com/w3c/epubcheck/wiki/GUI, but I'm unsure on how to do that.

**Comment by rdeltour** [comment]
Nice! 👍

I'll add it to the list on the website (the source code is currently sitting in a private branch)

**Comment by jstallent** [comment]
Romain, would you please add FlightDeck (https://ebookflightdeck.com/) to
that list, as well?

*Joshua Tallent *| Director of Sales and Education
***@***.*** | (978) 225-2757
*FIREBRAND TECHNOLOGIES* | Where Publishers, Content, and Readers Meet

***@***.***  | ***@***.****
Join us for the Community Conference! October 25, 2023, Chicago
*https://firebrandtech.com/conference/
<https://firebrandtech.com/conference/>*

Subscribe to the BookSmarts Podcast!
http://BookSmartsPodcast.com/

Have questions? Need help? Please feel free to grab 30 minutes with me
anytime!
https://calendly.com/joshuatallent/30min

Title Performance Monitoring - See what is happening to your titles on
Amazon, B&N, and other sites daily.
https://eloquenceonalert.com

LinkedIn Learning course: Learning Metadata for Book Publishing
*https://www.linkedin.com/learning/learning-metadata-for-book-publishing
<https://www.linkedin.com/learning/learning-metadata-for-book-publishing>*

**Comment by rdeltour** [comment]
> Romain, would you please add FlightDeck (https://ebookflightdeck.com/) to that list, as well?

Yes, will do!
