### ISSUE TITLE
Error showing HTTPS URL instead of internal path

### ISSUE THREAD

**Issue by SimonPRH** [w3c/epubcheck#1542]
I'm remediating some VERY old EPUB files, and got this error:

`ERROR | OPF-032 | /content.opf (line 64, col 77) | Guide references "https://2694f716-dddd-4b2b-bbfe-64990fe68f69.epubcheck.w3c.org/OEBPS/images/cover.jpg" which is not a valid "OPS Content Document".`

Obviously I'll change the guide item target to the cover XHTML page, but I'm sure it's not intended behaviour that this shows an HTTPS URL path. This happens in EPUB Check 5.0.1 and 5.1.1, I believe the error first appeared in the former. Seen this on multiple files now, though this particular file was created 13 years ago.

**Comment by rdeltour** [comment]
This looks like a bug. The absolute URL is the internal representation of the resource used by EPUBCheck (since v5.0.0) and should not be presented to the user.
Thanks for the report! 👍
