### ISSUE TITLE
Epub errors on Smashwords Please help!?

### ISSUE THREAD

**Issue by AmyrianTrue** [w3c/epubcheck#1545]
tmp_667240a1a6944f3b8c97526b8b549fc9_mFU9RU.ch.fixed.fc.tidied.stylehacked.xfixed.sc_split_001.html

I can't guess what area of the document or what element of the document could be causing this error.  It's last error before processing.  Any ideas?

**Comment by rdeltour** [comment]
> Any ideas?

Without any detail on the document or the message that is reported, it is hard to tell 😉

Also, please not that this tracker is supposed to be used only to report bugs or feature requests, and not as a user support channel.

I'm closing this issue for now, but feel free to reopen if you do think there is a bug with EPUBCheck!
