### ISSUE TITLE
Undefined entities are not reported for EPUB2 checks.

### ISSUE THREAD

**Issue by typopaul** [w3c/epubcheck#1546]
Non-standard entities, for example &linkref; are not reported when the checked file is EPUB2. 
In EPUB3 such entities are reported as errors. 

Is there a certain reason for this behavior?

**Comment by rdeltour** [comment]
If entities are defined in an external DTD, that would be valid in EPUB 2 (but not in EPUB 3).
Could you share a sample file to reproduce the issue?

**Comment by typopaul** [comment]
@rdeltour 

Find attached a zip file with a sample file containing a "wrong" entity in an EPUB2 file and a screenshot from the Thorium Reader.
I understand that the entity should be associated with an external DTD/resource. 
I am surprised that the EPUB Checker does not report it as an error but Thorium Reader does.

[issue1546_sample-entity-error-EPUB2.zip](https://github.com/w3c/epubcheck/files/13237697/issue1546_sample-entity-error-EPUB2.zip)
