### ISSUE TITLE
EPUB Help: RSC-001 Issue and PKG-026 Issue

### ISSUE THREAD

**Issue by francisbluee** [w3c/epubcheck#1550]
<img width="415" alt="Screenshot 2023-12-06 at 5 40 58 AM" src="https://github.com/w3c/epubcheck/assets/153079804/0bbb39f8-546a-449f-8f32-141b6ebc31ec">

Please help I've been trying to fix it but nothing is working

**Comment by mattgarrish** [comment]
This isn't an issue with epubcheck. Obfuscation can only be done on core media type fonts but you're using a non-standard media type to declare your TTF fonts.

To fix the errors, change the media types of the fonts in the package document manifest from "application/x-font-ttf" to either "font/ttf" or "application/font-sfnt". Those are the only media types epub recognizes for TTF.
