### ISSUE TITLE
Undeclared content is not flagged as a warning in EPUBCheck 5

### ISSUE THREAD

**Issue by CircularKen** [w3c/epubcheck#1555]
Recently had a few EPUBs returned from a client due to them failing Apple's Transporter checks.

I realise now that through my hand editing some content was commented out from the OPF but not removed from the package folders. 

I had checked using Pagina EPUB-Checker 2.0.10 (EPUBCheck 5.1.0) and Pagina EPUB-Checker 2.0.9 (EPUBCheck 5.0.1) and had not had any flagged warnings. The issue IS flagged as a warning in EPUB-Checker 2.0.9 (EPUBCheck 4.2.6).

I have had a look at the release documentation here for EPUBCheck 5 but didn't see a reference to this, so have I (and Apple…) missed the fact that extra files in an EPUB package are no longer raising a warning in EPUBCheck?… or is there an issue with EPUBcheck? or an issue with Patina's implementation of it?
 
<img width="1953" alt="Screenshot 2024-02-13 at 11 29 06" src="https://github.com/w3c/epubcheck/assets/17338941/0c854700-590b-4243-8f22-a504dc94068c">

**Comment by mattgarrish** [comment]
Files travelling in the container but not listed in the manifest was downgraded from a warning to a usage message while we were testing spec requirements against epubcheck to get epub 3.3 through W3C process (i.e., it was a case of epubcheck having a rule of its own making as the epub spec doesn't make this a warning).

For more info, see https://github.com/w3c/epubcheck/pull/1465

**Comment by CircularKen** [comment]
OK, thanks for the info @mattgarrish 
For now we will have to remember to use earlier EPUBcheck before submitting files to Apple!
Closing this issue.
