### ISSUE TITLE
Still some issues with links on web site

### ISSUE THREAD

**Issue by martinpub** [w3c/epubcheck#1560]
Hi,

I've seen #1283 and #1549, and I want to report a related issue.

Links on the different pages, in the body text (e.g. the link to the Java library on https://www.w3.org/publishing/epubcheck/docs/running/#what-next), are missing a trailing slash, so they will take the user to the w3c.github.io version. From there the links in the navigation menu will give a 404.

**Comment by rdeltour** [comment]
Sorry for the late reply and thanks for the report @martinpub, good catch!
I've fixed all the local links missing trailing slashes. This should greatly improve the internal link issue described in #1268.
