### ISSUE TITLE
a11y:exemption is not recognized by epubcheck

### ISSUE THREAD

**Issue by jhswift** [w3c/epubcheck#1566]
The relatively new property a11y:exemption  is not recognised by the 5.1 version of epubcheck. 
If that property is used in the opf file, epubcheck give this error:
Col: 63: ERROR(OPF-027): Undefined property: ""a11y:exemption"".

**Comment by mattgarrish** [comment]
Ya, I don't think it's helpful for epubcheck to enforce what properties are allowed in the a11y vocabulary. It's not like the package document vocabularies in the core spec that have elements that require their use.

It could maybe be a usage message to help people make sure they aren't misspelling property names, but we always expected to extend the vocabulary and this is the second time in the last year alone where we've done it.

**Comment by rdeltour** [comment]
>  I don't think it's helpful for epubcheck to enforce what properties are allowed in the a11y vocabulary. It's not like the package document vocabularies in the core spec that have elements that require their use.
>
> It could maybe be a usage message to help people make sure they aren't misspelling property names, but we always expected to extend the vocabulary and this is the second time in the last year alone where we've done it.

Yeah, good point.

There is currently no way in the EPUBCheck vocabulary declaration to say "these values are ok, and all other values are ok too but should be reported as usage". It's either a fully-checked vocabulary or a fully permissive one.

For now, I'm just adding the `a11y:exemption` to the list of known properties, but will consider adding a new vocabulary type to implement what you suggest 👍
