### ISSUE TITLE
Allow the use of version parameter for .epub files

### ISSUE THREAD

**Issue by PhoenixIV** [w3c/epubcheck#1570]
I would like to check backwards compatibility and therefore would love if the -v parameter is not ignored for .epub files.

I originally created a v2 book for most compatibility, then updated to 3 to make use of popups / noteref. After some more changes I now would like to check for v2 compliance again. I know some errors will appear with v2 because of the changes I intended, but I look for those that happened on accident.

**Comment by rdeltour** [comment]
This seems to be a duplicate of #1533
