### ISSUE TITLE
epubcheck 5.1.0 failing on books with TDM opt-outs

### ISSUE THREAD

**Issue by liisamk** [w3c/epubcheck#1574]
When we test including a TDM opt-out in our OPF files, we are consistently getting an epubcheck error: ERROR (OPF-028): Undeclared prefix: "tdm"

Since this is an industry standard that many publishers around the world are starting to implement, it should be fixed. 

Example file TK

**Comment by TzviyaSiegman** [comment]
for context https://www.w3.org/community/reports/tdmrep/CG-FINAL-tdmrep-20240510/#sec-epub3

**Comment by mattgarrish** [comment]
Have you declared a prefix as in the example @TzviyaSiegman cited?

If so, what version of epubcheck are you running? I can't reproduce the error if the prefix is declared.

If you're wanting to skip declaring a prefix, you need to get the epub standard amended to add tdm as a [reserved prefix](https://www.w3.org/TR/epub-33/#sec-reserved-prefixes).

**Comment by liisamk** [comment]
Ah- mea culpa. The prefix was not declared. When we add it, the validation in 5.1.0 works.
