### ISSUE TITLE
epubcheck 5.1.0 does not recognize `--failonwarnings+`, nor `--failonwarnings-`

### ISSUE THREAD

**Issue by lemniscati** [w3c/epubcheck#1575]
According to [the help message](https://github.com/w3c/epubcheck/blob/v5.1.0/src/main/resources/com/adobe/epubcheck/util/messages.properties#L90-L92), both `--failonwarnings+` and `--failonwarnings-` should be valid.
But epubcheck 5.1.0 says about them, respectively:
```
Unrecognized argument: "--failonwarnings+"
EPUBCheck v5.1.0
...
```
and
```
Unrecognized argument: "--failonwarnings-"
EPUBCheck v5.1.0
...
```
respectively.

**Comment by rdeltour** [comment]
Thanks for the report!

As said in #1576:
> I'm not sure for how long we've had this option and it's been documented this way, but I agree that having both --failonwarnings+ and --failonwarnings- looks a bit odd.

I'm in favor of keeping the current CLI behavior (a single `--failonwarnings` switch). I'll publish a PR to simplify the code a bit and fix the documentation.
