### ISSUE TITLE
value of attribute "unique-identifier" is invalid; must be an XML name without colons

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#163]
_From [gos...@gmail.com](https://code.google.com/u/113399516844659809114/) on March 21, 2012 18:50:19_

PROBLEM:Validation fails because  of the two following Errors:
1. ERROR: /Volumes/Data Partition TBD/Ellen_eBooks/The Moon QXP version/The Moon Has Fallen_2.epub/OEBPS/content.opf(2): value of attribute "unique-identifier" is invalid; must be an XML name without colons
the offending code is:
<package xmlns=" http://www.idpf.org/2007/opf " version="2.0" unique-identifier="978-0-9852681-0-7"> (where the unique-identifier is my ISBN number.)

2.ERROR: /Volumes/Data Partition TBD/Ellen_eBooks/The Moon QXP version/The Moon Has Fallen_2.epub/OEBPS/content.opf: unique-identifier attribute in package element must reference an existing identifier element id
The offending code is:
<dc:identifier id="bookid" opf:scheme="ISBN">978-0-9852681-0-7/dc:identifier

This is most frustrating and I would appreciate any help. Thank you in advance. Give a brief description of the problem METHOD: What steps will reproduce the problem? 1. 2. 3. RESULT: What happens? EXPECTED: What did you expect to happen? It is very important to state what your expectation is. PLATFORM: What version of the product are you using? On what operating system? ADDITIONAL INFO: Please provide any additional information below.

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=163_

**Comment by kalaspuffar** [comment]
Hi @rdeltour 

I'm looking at the test case for this issue. Do you remember what the actual error was that we wanted to ensure by the test code?

Best regards
Daniel

**Comment by rdeltour** [comment]
@kalaspuffar did you intend to comment on another issue? Apparently this one has been closed as `WONTFIX` 5 years ago since it was a user error, and not a bug…

**Comment by kalaspuffar** [comment]
Hi @rdeltour 

No, this issue is referenced in the code.

```EPUB20CheckExpandedTest.java```

```
  @Test
  public void testValidateEPUBUidSpaces()
  {
    // ascertain that leading/trailing space in 2.0 id values is accepted
    // issue 163
    testValidateDocument("valid/lorem-uidspaces", "valid/lorem-uidspaces.txt");
  }
```

**Comment by rdeltour** [comment]
this seems to check that `dc:identifiers` can have text values starting and ending with spaces…
