### ISSUE TITLE
RDF metada <rdf:RDF> in SVG

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#173]
_From [j...@magusdigital.com](https://code.google.com/u/107648360298702922208/) on April 29, 2012 14:26:31_

PROBLEM: I have been using SVG inserts to scale elements in ePUB documents. The files validate cleanly in every detail, except that ePUBcheck flags up `<rdf:RDF>` as invalid. Looking at the W3C website I don't think this is correct. It is valid. The files work perfectly, so perhaps this is a bug in ePUBcheck? This was with version 3.0b4. 

METHOD: What steps will reproduce the problem?
1. include an SVG image in the flow of the document, correctly inside a `<div>` tag.
2. Make sure there are no errors at all in the ePUB, then make sure that the plain SVG contains `<rdf:RDF>` metadata, which typically it will.
3. run the file through ePUBcheck version 3.0b4.

RESULT: ePUBcheck correctly identifies that the file is in fact ePUB 2.01. Everything passes validation, except for each SVG file the `<rdf:RDF>` element is said to be invalid.

EXPECTED: As far as I can see it isn't invalid, so I would expect a complete 'No errors' result.

PLATFORM: This was with version 3.0b4. I stopped using version 1.2 because that said there was a font type specification error in the .opf file that also didn't seem to be correct and because I am beginging to develop for ePUB 3. Version 3.0b4 does not report the font error, so presumably that has been fixed.

I am using Windows 7 64 bit

ADDITIONAL INFO: My objective is to create beautiful eBooks as eBooks, not as fallout from print, so I am probably pushing the boundaries of what may be done with ePUB 2.01; however, everything I do is validated by other checks and the files work well in all the major e-readers on the market, in desktop testing and on the iPad.

I haven't tried version 3.0b5 yet. This doesn't seem to be amont the fixes listed though.

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=173_

**Comment by rdeltour** [comment]
Not sure this is still an issue. The `External DTD entities are not allowed` sound legit in EPUB 3. Needs further review of the original issue.

**Comment by ptmkenny** [comment]
This is an old thread, but I'm getting the same error (with epubcheck 4.0.2:

> ERROR(RSC-005): ..epub/EPUB/media/file0.svg(13,14): Error while parsing file 'element "rdf:RDF" not allowed anywhere; expected the element end-tag or text'.

The RDF data was added when I took an emoji SVG from the Twitter twemoji collection (https://github.com/twitter/twemoji) and exported it as a plain SVG from Inkscape.

However, as noted in the OP, this SVG is fine; it appears on iPad, Kindle, and various Mac/PC reading apps, but nevertheless epubcheck throws an error about rdf:RDF.

**Comment by rdeltour** [comment]
Closing this issue, as foreign elements are now allowed since #970. 
Feel free to reopenIf this is still an issue for you in 4.2.0-beta.

**Comment by mattgarrish** [comment]
I tried to incorporate the commented-out test for this but am still getting the error.

**Comment by mattgarrish** [comment]
Looking closer at the test, the rdf element is disallowed when the svg is embedded in an xhtml document, but if I split it off into an svg doc the error goes away.

I'm going to add a working svg test, but it should also be valid in html. When I run the test through validator.nu it only warns that it does not validate rdf.
