### ISSUE TITLE
Duplicate files ignored

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#265]
_From [jens.tro...@gmail.com](https://code.google.com/u/100817963473914031312/) on April 28, 2013 09:40:35_

PROBLEM: Generating a .zip (epub) file with Python's Zipfile module allows me to store data using the same filename.  In my case, I had OEBPS/content.html stored twice in the epub file. METHOD: Using Python, create a epub file and store multiple data under the same filename. RESULT: The first file is checked, duplicates are ignored. EXPECTED: A warning might be nice that there are duplicate filenames in the epub file. PLATFORM: ADDITIONAL INFO: If needed I can attach such a epub file for testing.

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=265_

**Comment by pettarin** [comment]
Testing with the latest code from master, file `src/test/resources/30/epub/invalid/issue265.epub` passes the validator, while I believe it should fail (I see two ZIP entries with the same name).

Files `src/test/resources/30/epub/invalid/issue265b.epub` and `src/test/resources/30/epub/invalid/issue265c.epub` fails the check, as expected.

**Comment by tofi86** [comment]
@pettarin I also noticed that in Dec. 2015 and opened isse #659 for it.
