### ISSUE TITLE
Add application/font-sfnt as a legal media type for .ttf and .otf files

### ISSUE THREAD

**Issue by baldurbjarnason** [w3c/epubcheck#339]
SFNT-based fonts share application/font-sfnt as a legal media type as per [IANA assignment](http://www.iana.org/assignments/media-types/application/font-sfnt).

This applies to .ttf and .otf font files (but not .woff files which use [application/font-woff](http://www.iana.org/assignments/media-types/application/font-woff)).

Promoting the use of a standard media type is obviously a better—more long-term—solution than telling people to use a vendor-specific media type like application/vnd.ms-opentype. 

Currently, epubcheck gives a warning when the legal media type is used but no warning when the vendor-specific media type is used. Ideally, this should be flipped around but, in the meantime, adding application/font-sfnt as a legal media type will do. 

(And, yes, the spec should be updated to reflect this).

**Comment by tofi86** [comment]
refs https://github.com/w3c/publ-epub-revision/issues/667

**Comment by tofi86** [comment]
refs https://github.com/w3c/publ-epub-revision/issues/443

**Comment by tofi86** [comment]
refs #586

**Comment by tofi86** [comment]
Resolved with EPUB 3.1 spec: https://idpf.github.io/epub-cmt/v3/#cmt-grp-content-documents
Setting the "3.1 label".

Core media types for fonts are now:

Media Type | Content Type Definition | Applies to
------------ | ------------- | -------------
`application/font-sfnt` | [OpenType] [TrueType] | OpenType and TrueType fonts. Deprecate                                     `application/vnd.ms-opentype`.
`application/font-woff` | [WOFF] | WOFF fonts

However, I have now idea how this behaves with backward compatibility.

**Comment by mattgarrish** [comment]
This is also related to #872. font/* media types were also added.

**Comment by rdeltour** [comment]
Fixed in #972.
