### ISSUE TITLE
PlayOrder

### ISSUE THREAD

**Issue by jschvartz** [w3c/epubcheck#348]
EpubCheck does not control if PlayOrder attributes are in sequence in the NCX file.
You can have 1, 3, 2, etc. as long as you don't miss any.
If we give a playorder attribute, shouldn't it be sequential ?

**Comment by rdeltour** [comment]
@danielweck @mattgarrish do you think we should validate the `playOrder` ordering?

**Comment by mattgarrish** [comment]
No, isn't the point of `playOrder` to allow the author to define an alternative ordering from the sequence of elements? I can't see the point of the attribute if it has to match the sequence, otherwise. If you want to use the sequence as the play order, you just don't specify `playOrder`.

**Comment by rdeltour** [comment]
Oh sure. Thanks for reading slower (or more likely, thinking faster) than me 😊
