### ISSUE TITLE
Updating tests so that changes to messages don't break them

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#463]
Changing small typos or messages at all, will break the tests cause english messages are hard coded in the test results...

see previous discussion in PR #458

**Comment by rdeltour** [comment]
I agree 200% with the tests being a PITA to maintain. Just remove the 4.0 milestone as this is not critical to users.

**Comment by rdeltour** [comment]
Closing this issue, as this was largely improved in the new refactored test suite. 

Some tests still verify the content of the messages (this is notably useful for the generic errors like RSC-005 and RSC-017), but the tests set the language to English programmatically before running.
