### ISSUE TITLE
Additional code comments needed

### ISSUE THREAD

**Issue by rkwright** [w3c/epubcheck#513]
I have a tool built on Eclipse that allows validating and editing EPUBs.  It uses epubcheck for the validation (by subclassing the Report  class and hooking it to Eclipse’s parsing and marker machinery).  Up to now it has been based on epubcheck 3.  I recently decided to upgrade to epubcheck 4 (largely due to the work I am doing with EDUPUB and widgets).

I am seeing some minor problems.  Specifically, missing documentation (comments in the code) that made it unnecessarily difficult (at least for me) to figure out how to integrate the new code

I will add some additional comments in the code and push this as a pull request.

**Comment by tofi86** [comment]
> I will add some additional comments in the code and push this as a pull request.

Assigned @rkwright as he stated he would work on this. Labeled as `refactoring`.

**Comment by rdeltour** [comment]
Closing this as stalled. Better comments and documentation is needed, but this would happen in the refactoring post 4.2.0.
