### ISSUE TITLE
Problem parsing relative URLs

### ISSUE THREAD

**Issue by mebibou** [w3c/epubcheck#527]
When using relative URLs for resources in html files, epubcheck complains about Invalid path. Example:

`OEBPS/test/index.html`

```
<html>
  <base href="./">
  <link href="../css/test.css" />
</html>
<body>
</body>
```

`OEBPS/css/test.css`

```
body {
 width: 100%;
}
```

When epubcheck parses the file `OEBPS/test/index.html`, the following error will show up:
`ERROR: test.epub: could not parse OEBPS/test/index.html: Invalid path: ./../css/test.css`.

If I change the `base` to: `<base href="./test/">` then there is no error but when loading the epub in a reader it cannot find the `test.css` file

**Comment by rdeltour** [comment]
Hi @mebibou. Sorry for looking only now into this old issue…
Unfortunately I wasn't able to reproduce, neither for with EPUB 2.0 or EPUB 3.

If you still face the issue, could you possibly send a sample?

**Comment by mebibou** [comment]
sorry not on this project anymore

**Comment by rdeltour** [comment]
ok, thanks for answering! I'll close as `invalid`. Anyone can comment or reopen if they face the same issue.

**Comment by mattgarrish** [comment]
I'm finding the base tag really messes up epubcheck. If I add in `<base href="./"/>` to a file, then it complains that each referenced resource could not be found in the EPUB.

If I do a little more silliness and go up and down a level - `<base href="../EPUB/"/>` - then I get the error about invalid paths.

**Comment by rdeltour** [comment]
Oh. I tried harder and was able to reproduce. I'm wondering what the heck I missed earlier. 🤔

Thanks @mattgarrish for double-checking! I'll dig deeper now…
