### ISSUE TITLE
Report deprecated epub:type values

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#531]
We should add a sch to warn about the use of marginalia, sidebar, warning, annotation/annoref and note.

**Comment by tofi86** [comment]
You mean those types marked with `[deprecated]` at https://idpf.github.io/epub-vocabs/structure/, right? There's two more then:

* help
* rearnote

plus the ones you mentioned before:

* marginalia
* sidebar
* warning
* annotation
* annoref
* note

Is this deprecated in EPUB 3.1 only, or already in 3.0.1?

**Comment by mattgarrish** [comment]
It applies to all versions; the vocabulary isn't specific to revisions to allow it to change.

The changes overlapped with 3.1, but came from separate work we were doing with the W3C's WAI group to clean up the vocabulary (part of creating the Digital Publishing module).

**Comment by nekennedy** [comment]
Adding two additional deprecations to this list, to avoid duplication of tickets:
subchapter
rearnotes (plural)

**Comment by mattgarrish** [comment]
Noting that some of these are replaced by new semantics that need to be added:

- help -> tip
- rearnote -> endnote
- rearnotes -> endnotes

**Comment by mattgarrish** [comment]
Closing this issue as it is no longer valid. Validation of epub:type is removed in 3.2.

**Comment by mattgarrish** [comment]
Re-opening, as we should emit a notification if terms outside of the SSV are used, so we'll still need to update the vocabulary list.

I'm not sure what this means in terms of deprecation of terms within the SSV. Maybe they should be a similar level of notification?

**Comment by laudrain** [comment]
Publishers using extensively SSV vocabulary in epub:type should be warned of deprecation and of values outsides SSV, even if it is allowed in 3.2.

**Comment by mattgarrish** [comment]
Just to compile up everything noted in this issue.

The following are new:

- tip
- endnote
- endnotes

The following are deprecated (with replacement in parentheses):

- annoref (open annotations)
- annotation (open annotations)
- help (tip)
- marginalia (aside element)
- note (footnote or endnote)
- rearnote (endnote)
- rearnotes (endnotes)
- sidebar (aside element)
- subchapter (-)
- warning (notice)

**Comment by mattgarrish** [comment]
And for the record, we will only warn about deprecated terms that are defined in the structural semantics vocabulary.

If a term is not specified in the vocabulary, that will be reported as a usage message because such use is only "discouraged", which carries no normative weight.

**Comment by rdeltour** [comment]
Btw, I assume that the SSV terms that are deprecated in Content Documents but allowed in Media Overlays (e.g. table, list, and figure terms) should also be reported as warning?

**Comment by mattgarrish** [comment]
I would throw errors on them unless they are applied to their matching element, like:

```
<table epub:type="table">
````

in which case you could warn that they are deprecated.

They were only created for Media Overlays to identify their corresponding structures in XHTML, and if they are used on any other element they would violate this requirement in the SSV:

> Authors may use the properties on HTML markup elements not specifically listed, but must ensure that the semantics they express represent a subset of the carrying element's semantics and do not attach an existing element's meaning to a semantically neutral element.

**Comment by mattgarrish** [comment]
> * this would create inconsistencies with how we report other deprecated properties

Ya, but deprecated doesn't mean what it does for the other properties. Like I mentioned in the other issue, what is really being said is "not allowed". I would personally prefer to throw an error on any usage of them.

**Comment by rdeltour** [comment]
> deprecated doesn't mean what it does for the other properties. Like I mentioned in the other issue, what is really being said is "not allowed".

Right, I agree (I had replied to this one before seeing your comment in the other issue).

> I would personally prefer to throw an error on any usage of them.

Yes, that removes the complexity of checking the semantics of the carrying element, so it's reasonably straightforward to implement. That's also the expected behavior if we change "deprecated" to "not allowed" as a result of w3c/publ-epub-revision#1222, so SGTM!
