### ISSUE TITLE
ePub file containing epub:type="referrer" attribute passes validation

### ISSUE THREAD

**Issue by LeoRC** [w3c/epubcheck#713]
I have an ePub document which contains the attribute `epub:type="referrer"` (in several places). This document validates under EpubCheck 4.0.1 ("No errors or warnings detected. EPUB is valid!") as an EPUB 3.0.1 document. `referrer` is one of the properties defined in the [current EPUB for Education Structural Semantics](http://www.idpf.org/epub/profiles/edu/structure/structure-20160211.html). That document states that

> The semantic terms defined in this document are all included in in the EPUB Structural Semantics Vocabulary [StructureVocab] and available for use in the epub:type attribute [ContentDocs301].

But despite this, `referrer` is one of the few properties (perhaps the only one?) in the EPUB for Education Structural Semantics which does not appear in the current (5 October 2016) version of the [EPUB 3 Structural Semantics Vocabulary](https://idpf.github.io/epub-vocabs/structure/), not even marked as DRAFT. So are documents containing `epub:type="referrer"` not valid EPUB 3.0.1 documents, and is it a bug for EpubCheck 4.0.1 to validate them as such? It certainly refuses to validate documents which contain other properties which don't appear in the default vocabulary.

(Here are some example ePubs: one contains an `epub:type="referrer"` attribute in an appropriate place, one replaces `referrer` with `backlink`, one replaces it with a property not in either vocabulary, and one drops the attribute completely. Only the first and last validate under EpubCheck 4.0.1. [samples.zip](https://github.com/IDPF/epubcheck/files/587428/samples.zip))

**Comment by mattgarrish** [comment]
There was a draft property named referrer, but was changed to backlink during the process of creating the DPUB-ARIA vocabulary.

The change has to be made to the edupub spec, too, but as that work is on hiatus at the moment we haven't had an opportunity to do it.

Epubcheck won't validate backlink until it gets updated to reflect the changes made during the 3.1 revision. It is the correct term to be using moving forward, though.

**Comment by mattgarrish** [comment]
As with #531 and #714, 3.2 drops validation of epub:type, so these particular issues are no longer applicable. Issue needs closing.
