### ISSUE TITLE
Problem with Saxon-HE when using epubcheck as a library

### ISSUE THREAD

**Issue by renauds** [w3c/epubcheck#744]
Hi, 

I'm maintaining a Java 1.7 servlet in Eclipse Mars 2 on RedHat 6. The web server is Tomcat 7.

When I send a request to the application via the browser it throws an exception when calling the library "epubcheck 4.0.2" to validate an epub file (https://github.com/IDPF/epubcheck/wiki/Library).

    ResponseBean  responseBean = new  ResponseBean(0, null);
    try {
            Controller core = new Controller();
            core.init(propretiesFilePath, workingDirectoryPath);
            responseBean = core.process(requestParameters);
            if(responseBean.getStatus() == 200){
                File epubFile = new File(responseBean.getPath());
                EpubCheck epubcheck = new EpubCheck(epubFile);                
                Boolean result = epubcheck.validate();
                if(!result) {
                    throw new Exception("Errors been found witthin the epub file.");    
                }
            }
            core = null;
    } catch (Exception e) {
        throw e;
    }
    return responseBean;

The exception is 
```
java.lang.AbstractMethodError: 
javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)
Description : The server encountered an internal error that prevented it from satisfying the request.
javax.servlet.ServletException: java.lang.AbstractMethodError: 
javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)
com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)  
com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)    
com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
```

I have tried to use the same version of Saxon-he than the epubcheck 4.0.2 library, Saxon-HE 9.5.1-5 but without success.

Is someone knows how to resolve this issue?

Thanks ! :)

**Comment by tofi86** [comment]
Why do you think this is an issue with the EpubCheck library? the stack-trace doesn't show any classes from our packages? is there more information from the stacktrace showing where an EpubCheck method fails?

**Comment by renauds** [comment]
I have this information from the exception: 
java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
	com.adobe.epubcheck.ctc.XmlDocParser.readXML(XmlDocParser.java:131)
	com.adobe.epubcheck.ctc.XmlDocParser.parseDocument(XmlDocParser.java:61)
	com.adobe.epubcheck.ctc.PackageReader.getPathToRootFile(PackageReader.java:73)
	com.adobe.epubcheck.ctc.PackageReader.readPackageData(PackageReader.java:38)
	com.adobe.epubcheck.ctc.CheckManager.<init>(CheckManager.java:20)
	com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:218)
	com.adobe.epubcheck.api.EpubCheck.validate(EpubCheck.java:189)
	ca.umontreal.cenr.epub.EpubServlet.execute(EpubServlet.java:215)
	ca.umontreal.cenr.epub.EpubServlet.getEpub(EpubServlet.java:81)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

**Comment by tofi86** [comment]
Okay, fails on setting Sax parser features in https://github.com/IDPF/epubcheck/blob/master/src/main/java/com/adobe/epubcheck/ctc/XmlDocParser.java#L131

But to be honest, I have no clue what is causing this in your environment...

Probably @rdeltour has an idea?

**Comment by rdeltour** [comment]
Is this still an issue? If yes could you possibly provide us with a way to reproduce this issue?

**Comment by rdeltour** [comment]
Closing as inactive. For information, EPUBCheck v5.0.0 now uses Saxon-HE 11.4.
