### ISSUE TITLE
Empty attribute "xml:lang" reported as invalid, even though is valid

### ISSUE THREAD

**Issue by elmimmo** [w3c/epubcheck#777]
EpubCheck v4.0.2 (installed via Homebrew on Mac) chokes with `xml:lang` attributes that have no value assigned, such as:

```
<i lang="" xml:lang="">blahblah</i>
```

by saying:

> Error while parsing file 'value of attribute "lang" is invalid; must be an RFC 3066 language identifier'.

But [Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/) states that: 

> HTML and XML also provide a means to prevent inheritance of language using the empty string, ie. `xml:lang=""`. Essentially, this says: I do not want to associate any language with this information.

**Comment by mattgarrish** [comment]
HTML 5.0 also says it explicitly:

> Setting the attribute to the empty string indicates that the primary language is unknown.
https://www.w3.org/TR/html5/dom.html#the-lang-and-xml:lang-attributes

It's a pretty rare to find, though. You can use zxx for non-linguistic content. You have text you have no idea what language it is in?

**Comment by elmimmo** [comment]
My case is that of a body of text sprinkled with some words in different languages, for which I applied, to all, the same pattern:

    <i lang="xx">_______</i>

One word in particular is in a fictional language, so I left the value of its `lang` atttribute blank, as in "unknown" which, as far as I understand it, fits the particular situation the standard contemplates.

My case is irrelevant, though. I can put up with doing it different for that lone word.

The standard has a consideration for leaving it blank, so epubcheck should consider it valid too. It not doing so is therefore a bug.

**Comment by mattgarrish** [comment]
Definitely a bug. I was just curious what you ran into. Thanks.

**Comment by tofi86** [comment]
Matt, any chance you can fix the Schema and make a PullRequest? Otherwise I'd take this in the next week or so...

**Comment by murata0204** [comment]
I did it.  I will create a pull request.

**Comment by tofi86** [comment]
Fixed an merged in `master`.

**Comment by Hellsbutt** [comment]
I'm trying to upload a book to play store but I keep getting this error please help me

**Comment by mattgarrish** [comment]
Are you getting it from HTML, SVG or the package document?

It looks like the package document schema has the same problem, as it validates against xsd:language which doesn't allow for empty strings.

**Comment by clapierre** [comment]
I believe we are now not detecting a missing xml:lang="en" attribute entirely for content documents when you relaxed the xml:lang="" check.

Ace no longer reports an error when we have
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en">

I would expect that to flag an error that we also require xml:lang="en" as well as lang="en"

**Comment by mattgarrish** [comment]
> I would expect that to flag an error that we also require xml:lang="en" as well as lang="en"

I'm not sure this is the right place for reporting this, as it's valid as far as epubcheck is concerned.

It's best practice to define both attributes because xhtml content documents may get served up as text/html, but it's not a requirement. The only requirement is that the languages match if both attributes are specified.

It's technically better to specify `xml:lang` for xhtml content documents because it's better for xml toolchains, but I don't believe it matters for browsers or reading systems which one you choose. See, for example, https://www.w3.org/International/questions/qa-html-language-declarations
