### ISSUE TITLE
RELAX NG schema for SVG

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epubcheck#779]
Before the publication of EPUB 3.0, I volunteered to create a schema for SVG 1.1 (Second edition).  At that time, there were two sets of RELAX NG schema for SVG 1.1 (First edition).  However, there are several syntactical changes between the first edition and the second edition.

Rather than trying to update existing first-edition RNG schemas, I decided to create a RNG schema by automatic conversion from the second-edition DTD.  This is the origin of svg11-flat.rnc, which is used by epubcheck.  Obviously, this automatically generated RNG schema is not modularized and thus not easy to maintain.

Validator.nu uses a set of RELAX NG schema for SVG.  I suppose that it captures widely-used features of SVG 1.1 (Second edition) and sometimes SVG2 features.  If we adopt Validator.nu for the validation of content documents, schema maintenance will be a lot easier.

**Comment by tofi86** [comment]
Thanks for taking a closer look at all the SVG schemas and issues, dear Makoto san.

This looks like a big field which needs improvements and @rdeltour also put this on the [refactoring roadmap](https://github.com/IDPF/epubcheck/wiki/WorkPlan#refactoring). In the follow up section ["HTML validation"](https://github.com/IDPF/epubcheck/wiki/WorkPlan#html-validation) he also proposes switching the HTML validation engine, which could also be used to validate SVG then.

I will label this as "epub-3.1" for further discussion.

**Comment by murata0204** [comment]
If there are other schema issues, please let me know.

**Comment by rdeltour** [comment]
Done in #934, will be released in v4.2.0.
