### ISSUE TITLE
picture element and image CMTs

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#781]
Noting that HTML 5.1 adds the picture element, which allows multiple source images to be specified. This means that you can provide a fallback CMT image for a non-CMT image type without having to use manifest fallbacks.

epubcheck will need to account for the child source elements in determining whether a CMT is available.

This doesn't change fallbacks for images outside the picture element.

**Comment by tofi86** [comment]
Is this only EPUB 3.1 or also EPUB 3.0?

**Comment by mattgarrish** [comment]
Only for 3.1.

The picture element wasn't in HTML 5.0, and EPUB 3.0(.1) have hard references to that version.

**Comment by rdeltour** [comment]
> epubcheck will need to account for the child source elements in determining whether a CMT is available.

I'm not sure what the rule should be, given that a non-naïve check would need to compute not-only the image source set,  but also the image selection algorithm (in other words, an image from the source set can only be considered as a fallback when it can be selected in the same conditions –viewport size, etc– as the non-CMT image).

Thoughts?

**Comment by rdeltour** [comment]
So after discussed with @mattgarrish we agreed we should at least:
- add support for the `source` element and `srcset` attribute (i.e. parse `srcset` and add the found paths to the xref checker)
- once the above is done, make sure the `img` is accepted as a fallback for previous `source` siblings

This requires however a correct implementation of [`srcset` parsing](https://html.spec.whatwg.org/#parsing-a-srcset-attribute).

As the full requirements depend on the discussion happening in the CG, and it's unlikely that `srcset` is heavily used in EPUB, at least not critically, let’s tackle this issue in the RC.
