### ISSUE TITLE
Error API unique-identifier

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epubcheck#849]
Hi,
we're using epubcheck to extract some data from the EPUB.

We've found a bug with the last version. The value returned by the API is not the unique identifier, but the last item's ID in manifest.

Here you can find the Java code we use:

```
EpubCheck epubcheck = new EpubCheck(tempFile,report);
epubcheck.validate();
if (report.getFeatures() != null){
String uniqueIdent = report.getFeatures().get(FeatureEnum.UNIQUE_IDENT);
}
```

Thanks,
Gregorio

**Comment by tofi86** [comment]
Thanks for the report. We'll investigate!

**Comment by rdeltour** [comment]
I had a look at this issue: I'm not sure I understand, as I don't think `getFeatures()` is part of the default Report API.

@gregoriopellegrino what report implementation are you using? Could this come from your side of the code?

Also, please note that the feature identified by `FeatureEnum.UNIQUE_IDENT` will indeed be reported once for the Publication unique ID (with a `null` URI, i.e. a feature at the package level) _and_ once for each Publication resource (with the URI set to the resource, and the ID of the `item`).

Removing the `bug` type and (tentatively) adding the `invalid` type.

**Comment by gregoriopellegrino** [comment]
Thanks for the feedback.

Here is the Implementation Report that we are using:
```
EpubValidationReport extends MasterReport

...

Map<FeatureEnum,String> features = new HashMap<FeatureEnum,String>();

...

@Override

public void info(String resource, FeatureEnum feature, String value) {

features.put(feature, value);

}
```

After the info you gave us of the double FeatureEnum.UNIQUE_IDENT we modified the code and now it seems to work.

Thank you.

**Comment by rdeltour** [comment]
Thanks for the follow up @gregoriopellegrino. Glad that you got it working, I'll close the issue now.

**Comment by gregoriopellegrino** [comment]
@rdeltour sorry I reopen this issue.

If the EPUB has two identifiers:
`<dc:identifier id="bookid">urn:uuid:BF6C4535-02C2-4CD7-B5C9-05014EAF5B97</dc:identifier>
<dc:identifier>urn:isbn:9791220010030</dc:identifier>`

Then the MasterReport returns only the first one, which is the "unique identifier", is it possible to get also the second one (the isbn)?

Thanks,
Gregorio

**Comment by laudrain** [comment]
@gregoriopellegrino what is the use case for multiple identifiers?

**Comment by gregoriopellegrino** [comment]
If in Adobe InDesign 2019 CC the user set the _Identifier_ field in the export wizard:
![image](https://user-images.githubusercontent.com/5065125/55872231-bd3dbe00-5b8c-11e9-8b00-44b5d5b7d499.png)

The exported file has:
`<dc:identifier id="bookid">urn:uuid:9976B97A-483A-4A9A-8E72-C2DC8CC57854</dc:identifier>
<dc:identifier>urn:isbn:9791220010030</dc:identifier>`

InDesign doesn't set the ISBN as _unique-identifier_, but as another identifier.

Gregorio

**Comment by laudrain** [comment]
@gregoriopellegrino ok, that's InDesign EPUB export behavior.
Would it not be better to fix that after the export to preserve the ISBN as the only and unique identifier?

**Comment by gregoriopellegrino** [comment]
Yes, even if the InDesign approach is not incorrect (EPUB specifications allow multiple identifiers).

In LIA Foundation we use the _MasterReport_ class to extract the ISBN from the files, but with the current implementation it is not possible because only the _unique identifier_ is extracted.

Is there any other way to extract this data programmatically from epubcheck?

In any case, it is not a high priority request

**Comment by laudrain** [comment]
@gregoriopellegrino if you mean "extract data programmatically from EPUB", there are many tools.
For instance, to extract schema.org accessibility metadata from our EPUB that pass Ace, I have a Python program that reads the EPUB file using available Python libraries.

**Comment by rdeltour** [comment]
@gregoriopellegrino EPUBCheck's primary objective isn't data extraction, but as we want to refactor the reporting API in a future version, it would be a good opportunity to see if it can help there!
