### ISSUE TITLE
Corrupted image file encountered.

### ISSUE THREAD

**Issue by bitcoin333** [w3c/epubcheck#850]
I have an epub which gives no error when validted by epubcheck.
But I wanted to decrease the epub size, so I compressed the jpeg images in Calibre with lossy compression. After that  epubcheck gives an error message for every jpeg file: "Corrupted image file encountered."

See the attached image as an example for "corrupted image file".

![w=mc^2](https://user-images.githubusercontent.com/6832218/41035529-39063064-698d-11e8-9aaa-2065bcbbcfa1.jpg)

**Comment by rkwright** [comment]
@bitcoin333    Reproduced this with EPUBCheck 4.0.3 on a MacPowerBook running 10.12.6.  Interestingly, while developing the EPUB, there were a few minor errors (incorrect OPF, etc.).  When those were eliminated, EPUBCheck returned the error 

```ERROR(PKG-021): ./Tiny-Corrupt-Image.epub/OPS/images/corrupted.jpg(-1,-1): Corrupted image file encountered.```

But the file is NOT corrupted according to Preview and Photoshop

Attached is the EPUB file (with zip extension).
[Tiny-Corrupt-Image.zip](https://github.com/IDPF/epubcheck/files/2372302/Tiny-Corrupt-Image.zip)
