### ISSUE TITLE
Maven Issue

### ISSUE THREAD

**Issue by akshaytiwari29** [w3c/epubcheck#856]
Started by user akshay tiwari
Building on master in workspace /var/lib/jenkins/workspace/auto2
[auto2] $ /bin/sh -xe /tmp/jenkins956186873028303875.sh
+ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.203 s
[INFO] Finished at: 2018-08-29T04:46:08+00:00
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/var/lib/jenkins/workspace/auto2). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by tofi86** [comment]
Does the `/var/lib/jenkins/workspace/auto2` directory contain all the epubcheck sources and the `pom.xml` file?

If not it should be clear that you cannot run `mvn install` in there...

The command needs to be run from the epubcheck directory.

**Comment by rdeltour** [comment]
Closing as `invalid`, as it seems it's a setup issue (as pointed by @tofi86). Feel free to keep on discussing here or reopen if you disagree.
