### ISSUE TITLE
What’s the plan for the scoped attribute?

### ISSUE THREAD

**Issue by JayPanoz** [w3c/epubcheck#861]
What’s the plan for `<style scoped="">` since [it is now deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Deprecated_attributes)? Support hasn’t be great anyway and it’s been removed from Firefox (the only major browser who did support it) anyway.

**Comment by mattgarrish** [comment]
It never made any of the w3c rec documents, so it really shouldn't have been allowed. I guess it snuck in as scoped was probably still in 5.0 when we published 3.0.

If the goal is to align with w3c validator/validator.nu for the next major release, it'll have to become invalid again.

**Comment by rdeltour** [comment]
the `scope` attribute is now disallowed with the new schemas that will be integrated in 4.2.0. Closing as completed.
