### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#864]
I'm thinking of something adapted from the [Contributor Covenant](https://www.contributor-covenant.org/), like we did in the [Ace project](https://github.com/daisy/ace/blob/master/CODE_OF_CONDUCT.md).

In the "Enforcement" section, we should point to a channel to report any complaint (ideally, more than one channel). What should this be? Is there any private address from the steering committee that could be used? Or the address of the chairs? cc @TzviyaSiegman @laudrain

**Comment by TzviyaSiegman** [comment]
The W3C offers the [Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). I am double checking whether this applies to CGs.

**Comment by rdeltour** [comment]
> The W3C offers the [Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). I am double checking whether this applies to CGs.

Good point, I didn't think about that. However, as EpubCheck contributors do not necessarily participate in the CG, I'm wondering if it can apply? Please let me know your findings!

**Comment by mattgarrish** [comment]
It does apply per the CG FAQ:

> Is there a code of conduct for CG/BG participants?
> Yes. See the participation policies of the CG Process and the W3C Code of Ethics and Professional Conduct.

https://www.w3.org/community/about/faq/#code-of-conduct

If this is now being undertaken as part of the CG's work, it would have to apply, even if not all the contributors are members. It's ultimately a statement of what the project leads expect in the way of behaviour, so regardless of what groups you might participate in you're bound to what the project indicates it expects.

**Comment by TzviyaSiegman** [comment]
@mattgarrish is correct, and I've asked the W3C systeam to add the CEPC to CG pages by defauls. But, is epubcheck the work of a CG?

**Comment by laudrain** [comment]
This revision of epubcheck is not the work of the PBG even if decided and launched by PBG SC, nor the PWG.
It's clearly in EPUB3 eco-system maintenance scope. IMO it's in the realm of the EPUB3 CG.
We should ask Dave and Rachel.

**Comment by laudrain** [comment]
Of course. Sorry if I was not clear, I didn't mean that the work would be done by the CG.
But as you are asking for a code of conduct, I may think it is for this project in GitHub.
And this Github is in W3C...

**Comment by rdeltour** [comment]
> Of course. Sorry if I was not clear, I didn't mean that the work would be done by the CG.

No worries, I had understood 😄 

> But as you are asking for a code of conduct, I may think it is for this project in GitHub.
> And this Github is in W3C...

Yes, I agree that referring to CEPC might just be what we need here. The only nit I could see would be that the definition of [participants](https://www.w3.org/Consortium/cepc/#Participant) _might_ be too limited, or at least sound "odd" for a software development project like EpubCheck:

> includes the following persons:
>  -  W3C Team (employees, contractors, fellows)
>  -  W3C group participants (members and invited experts)
>  -  Advisory Committee Representatives (and their guests)
>  -  W3C Offices staff
>  -  Anyone from the Public partaking in the W3C work environment (e.g. comment on our specs or email us, attend our conferences, functions, etc)

so if we want to adopt CEPC, maybe we should raise the issue to the PWETF? Ping @TzviyaSiegman
