### ISSUE TITLE
Script elements must reference only local scripts

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#870]
HTML and SVG script elements must not reference remote resources from their href/src attributes.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-resource-locations-script

**Comment by rdeltour** [comment]
Depends on the resolution of [w3c/publ-epub-revision#1225](https://github.com/w3c/publ-epub-revision/issues/1225) and [w3c/publ-epub-revision#1234](https://github.com/w3c/publ-epub-revision/issues/1234)
