### ISSUE TITLE
Core media type fonts

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#872]
This is a placeholder issue until https://github.com/w3c/publ-epub-revision/issues/1158 is resolved. Either we need to update the allowed core media types for font/woff2 and application/font-sfnt, or we should stop enforcing fallbacks for font resources.

**Comment by mattgarrish** [comment]
The final word on this is that we shouldn't require fallbacks for font resources. I believe this is the case already for a number of font types, but needs to be expanded to cover the newer font/* types.

**Comment by rdeltour** [comment]
Fixed in #972.
