### ISSUE TITLE
Add checks for authority and term with dc:subject

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#876]
If the authority property is attached (via refines) to a dc:subject, then a term property also has to be attached. Likewise, if a term is attached, there must be a corresponding authority attached (i.e., they must always appear together).

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-opf-dcsubject

**Comment by rdeltour** [comment]
Closed in #927
