### ISSUE TITLE
Use of display-seq meta property is deprecated

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#877]
Epubcheck should emit a warning if the property is used in the meta property attribute.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-display-seq

**Comment by murata2makoto** [comment]
The warning message is fine but epubcheck 4.2.0-alpha-1 reports that EPUB 3.0.1 rules are used.  Is this specific to the JP locale?

**Comment by rdeltour** [comment]
> epubcheck 4.2.0-alpha-1 reports that EPUB 3.0.1 rules

doh, good catch! 😅

>  Is this specific to the JP locale?

No, the EPUB "3.x" version string just hasn't been updated, it will be reported the same on all locales! oops…

**Comment by rdeltour** [comment]
I created #943 to make sure we don't forget 😄

**Comment by rdeltour** [comment]
Closed in #927

**Comment by clapierre** [comment]
This deprecation actually got reversed prior to 3.2 being published and as a result changed back in 
[https://github.com/w3c/epubcheck/pull/994](https://github.com/w3c/epubcheck/pull/994)
