### ISSUE TITLE
Add properties attribute to link element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#883]
The link element now allows properties attribute. The value(s) of the attribute must be prefixed unless they are defined in the [link properties vocabulary](https://idpf.github.io/epub-vocabs/package/link/#sec-link-properties).

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-link-elem

**Comment by mattgarrish** [comment]
See also #884 for more about the default vocabulary for this property.

**Comment by rdeltour** [comment]
Closed in #927

**Comment by rdeltour** [comment]
Oops. Forgot this was only _partially_ resolved
