### ISSUE TITLE
EPUB-defined navigation lists must not reference remote resources

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#890]
The toc, page-list and landmarks navs must reference only in-spine content documents.

All other nav elements can reference both internal and external resources.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#confreq-nav-a-href-default

**Comment by rdeltour** [comment]
Matt suggested the following Schematron snippet (thanks!):

```xml
    <pattern id="no-remote-refs">
        <rule context="html:a[ancestor::html:nav[contains('toc|landmarks|page-list',@epub:type)]]">
            <report test=".[matches(@href, '.+?://')]">Hyperlinks in toc, landmarks and page-list nav elements must not reference resources outside the container</report>
        </rule>
    </pattern>
```

However we may have a more robust facility in the Java code to test the in-container-ness. In addition, this would allow the message to be localizable (while schematron messages currently aren't).

Let's see if it's easy to do in Java, otherwise we'll fallback to the schematron solution.

**Comment by mattgarrish** [comment]
Ya, this is probably better done in java as the testing just relies on some protocol at the start.

To be safe it would really need to tokenize the epub:type value, too, so something more like:

```
html:a[ancestor::html:nav[tokenize(@epub:type)=('toc','landmarks','page-list')]
```

**Comment by rdeltour** [comment]
just a clarification: it's not only about remote resources, an embedded (non-top-level) local resource is disallowed too, correct?

**Comment by mattgarrish** [comment]
If you mean referencing a resource outside of its use within a top-level content document, then no. The fragment identifier has to occur within a top-level content document for the three epub navs.

**Comment by rdeltour** [comment]
ok, I think I was confused by the following statement:

>  For all other nav types, it MAY reference any resource, regardless of whether it is a Publication Resource, or whether it is Local or Remote Resource.

which sounds more open that it is. In reality, it can only reference _either_ Top-level Content Documents _or_ remote resources. Other non-top-level-content-document Publication Resources are disallowed, by virtue of the `spine` restriction:

> All Publication Resources hyperlinked to from the EPUB Navigation Document also MUST be listed in the spine

Maybe the first statement could be made clearer by rewording it to something like:
>  For all other nav types, it MAY reference Remote Resource.

**Comment by mattgarrish** [comment]
Yes, that language is a bit overzealous. I think it may have slipped through from earlier discussions, as I seem to recall questions of whether data sets and other items of interest in the container could be listed.

I can't find any evidence that we agreed to loosen it that much, only to allow remote references: https://github.com/w3c/publ-epub-revision/issues/594
