### ISSUE TITLE
Use of the epub:trigger element is deprecated

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#894]
Detection of the element should generate a warning.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-xhtml-epub-trigger

**Comment by tofi86** [comment]
@mattgarrish this is the wrong link. It links to `epub:switch`.

**Comment by mattgarrish** [comment]
Yup, they got reversed... I'll just fix in place.
