### ISSUE TITLE
Use of the epub:switch element is deprecated

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#895]
Detection of the element should generate a warning.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-xhtml-content-switch

(Correct link now.)

**Comment by tofi86** [comment]
@mattgarrish this is the wrong link. It links to `epub:trigger`.

**Comment by rdeltour** [comment]
`epub:switch` is now reported as deprecated with #938.

However, what should we do about the `switch` property in the OPF? Should it still be checked that the `switch` property is declared in the Package Document if the author used `epub:switch`, or should it be totally ignored altogether?

Currently, EPUBCheck keeps on report a missing `switch` property as an error.

**Comment by rdeltour** [comment]
> However, what should we do about the `switch` property in the OPF?

**RESOLUTION**: keep the check. 

Rationale (from @mattgarrish):
> Deprecated only means you shouldn't use, but if someone does we should still be reporting that the feature has been used properly
> So long as we emit warning on the features themselves, we can leave the rest of the verification structure intact.

and we do not need to  warn about  the OPF `switch` property:
> I'd stick with just warning about epub:switch because the use of the property depends on it.
