### ISSUE TITLE
Limit ARIA roles to only core ARIA and approved extensions

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#898]
The value(s) of the role attribute need to be validated so that only those defined in ARIA or the approved extensions are allowed. We shouldn't let this attribute be treated like the class attribute at the epubcheck level. Validation of correct usage would be a bonus (like the W3C validator does), but can be deferred to, for example, the Ace validator.

This relates to the implementation of #892

Reference: https://www.w3.org/TR/html/dom.html#aria-role-attribute

**Comment by mattgarrish** [comment]
Closing this issue as the updated HTML schemas in PR #934 provide validation of ARIA roles, including DPUB-ARIA.

**Comment by SarahMagdalena** [comment]
Hi! 
I created an EPUB 3 book including a glossary. I tried the following mark up:

```
<section>
<h1>Glossar</h1>
<dl epub:type="glossary" role="doc-glossary">
<dt epub:type="glossterm" role="term">...</dt><dd epub:type="glossdef" role="definition">...</dd>
</dl>
</section>
```

```
<section epub:type="glossary" role="doc-glossary">
<h1>Glossar</h1>
<dl>
<dt epub:type="glossterm" role="term">...</dt><dd epub:type="glossdef" role="definition">...</dd>
</dl>
</section>
```

Both samples are valid according to epubheck 4.1.1, but in epubcheck 4.2.0 beta I get an error for both, that says the value of the role attribute (doc-glossary) is not valid (even though the first sample looks quite similar to the one of the [DPub Module](https://www.w3.org/TR/dpub-aria-1.0/#doc-glossary)).
Now I was wondering, why doc-glossary is not allowed? Or is there another way to mark up the glossary so the epub is valid?

Thanks in advance!

**Comment by mattgarrish** [comment]
The glossary example in the specification is wrong and will be fixed in the next release. It is a landmark role, so has to be used on the containing section as in your second example. The working draft for the next version shows the correct usage: https://w3c.github.io/dpub-aria/#doc-glossary

We probably should patch that here in the interim, as we don't want the role applied to `dl`.

**Comment by SarahMagdalena** [comment]
Okay, I understand. Then I will continue with the second sample. 
Thank you a lot for the fast response!
