### ISSUE TITLE
Remove warnings when position fixed or absolute are used in CSS

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#899]
The recommendation not to use position: [fixed|absolute] was dropped from the CSS profile in 3.2 so detection of these values should not result in a warning anymore. (It was replaced with a note.)

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-css-content-conf

**Comment by clapierre** [comment]
This is currently causing us some issues where we want to have a Screen Reader specific spoken text hidden off-screen with a different visual presentation of the text onscreen.
IE. a fancy chapter H1 of "One" with sub chapter heading of "Back to Basics"
but we want the screen reacher to hear
"Chapter One, Back to Basics"
IE: CSS 
 .sr-only
            {
              clip: rect(1px, 1px, 1px, 1px);
              **position: absolute !important;** 
              white-space: nowrap;
              height: 1px;
              width: 1px;
              overflow: hidden;
            }

So having this ability to add this CSS without EPUBCheck issuing a warning would be great.

**Comment by rdeltour** [comment]
Note: a side effect of removing these warnings will be to fix the issue that they were also reported for EPUB 3.2 content, which didn't have this recommendation in the first place (only a "strongly discouraged" note).

**Comment by rdeltour** [comment]
Fixed in #971.
