### ISSUE TITLE
Unused file declared inside content.opf

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#90]
_From [RMuthura...@gmail.com](https://code.google.com/u/113484476650355105306/) on January 26, 2011 10:03:42_

PROBLEM: Checking for unused file(s) declared in content.opf but not referenced inside XHTML files.

METHOD: What steps will reproduce the problem? 1. Place a image inside /images folder
2. Reference that image inside content.opf
3. Not called anywhere inside XHTML files
4. validate epubcheck 1.1, does not gives any warning

RESULT: When epub file is validated using epubcheck 1.1, no error/warning is reported

EXPECTED: A warning message will be nice.

PLATFORM: epubcheck 1.1

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=90_

**Comment by tofi86** [comment]
> I'm not sure if that is implemented already or not. To be further investigated.

It's not. Tested with the attached EPUB2 and EPUB3 files:

[issue90_testfiles.zip](https://github.com/IDPF/epubcheck/files/676304/issue90_testfiles.zip)

**Comment by mattgarrish** [comment]
Closing this issue as it is no longer valid. EPUB 3.2 allows (foreign) resources to travel inside the container provided they are not used in rendering per https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-foreign-restrictions

**Comment by tofi86** [comment]
@mattgarrish okay for EPUB 3.2.

But how do we validate EPUB 3.0.1 in the future? You're closing a bunch of issues at the moment which were reports for EPUB 3.0(.1) issues. Are you saying we will be treating those EPUBs as EPUB 3.2 in the future? If not, a couple of your issues needs to be reopenend as they need fixes for 3.0.1 (but not for 3.2).
Or am I missing something?

/cc @rdeltour

**Comment by mattgarrish** [comment]
> Are you saying we will be treating those EPUBs as EPUB 3.2 in the future?

Yes, 3.2 is just a progression of EPUB 3 that comes with a package version number of "3.0". It's no different than 3.0 not being separable from 3.0.1.

The idea of separate versions of EPUB 3 was killed off with 3.1. The CG isn't going to make another version number change in the package document for the life of EPUB 3.

**Comment by tofi86** [comment]
Ah, Right, Sorry! I forgot about the unchanged version number. All good!

**Comment by rdeltour** [comment]
> Yes, 3.2 is just a progression of EPUB 3 that comes with a package version number of "3.0". It's no different than 3.0 not being separable from 3.0.1.

Right, but EpubCheck could still make the difference. We could envision a switch that "forces" a 3.0.1 mode (and thereby reject new 3.2 stuff).

This would potentially be useful if EPUB 3.0.1 becomes an ISO standard and people want to check strict conformance to it and not 3.2?

Let's bring this to the steering committee before closing the 3.0.1-only issues.

**Comment by mattgarrish** [comment]
> This would potentially be useful if EPUB 3.0.1 becomes an ISO standard and people want to check strict conformance to it and not 3.2?

I'd hate to see that become a reality, tbh, but fine leaving them open if you want to check. It seems like a huge interop trap for distribution (it's as bad as having different version numbers).

**Comment by rdeltour** [comment]
Closing this as @mattgarrish suggested, as we do not differentiate EPUB 3.x version.
