### ISSUE TITLE
Removal of various -epub- prefixed CSS properties

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#900]
The following prefixed properties were removed from the CSS profile:

- -epub-cue
- -epub-pause
- -epub-rest
- -epub-speak
- -epub-speak-as
- -epub-voice-family
- -epub-ruby-position
- -epub-text-combine-horizontal
- -epub-full-size-kana
- -epub-text-emphasis

Use of any of these is an error.

**Comment by rdeltour** [comment]
The [CSS content conformance section](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-css-content-conf) says:

> It MAY include the prefixed properties defined in CSS Style Sheets — Prefixed Properties.

It doesn't say that other prefixed properties must not be used, so the presence of these wouldn't be errors, would it?
