### ISSUE TITLE
Fixed layout SVG dimensions can also be obtained from height/width attributes

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#902]
Prior to 3.2, the dimensions had to be set in the viewBox attribute, but now it's valid to specify the dimension in height/width attributes on the svg root element. It's also valid to specify both the viewBox and height/width.

If only height/width are set, there should be a warning to use viewBox, as the specification contains a recommendation to only use it.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-fxl-icb-svg

**Comment by rdeltour** [comment]
So the spec says:
> If only the `x`, `y`, `height` and `width` attributes are present, they _SHOULD_ be defined in pixel values (establishing the ICB). Note that if the pixel values defined by `x`, `y`, `height` and `width` attributes exceed the Viewport's pixel values, the graphic will be clipped on the Viewport boundaries (i.e., the graphics will not be rescaled).

I'm wondering why other absolute length values are not allowed, is this a shortcoming of the spec or was it actually intended to limit it to **pixel** values?

Also, I'm no SVG expert but wouldn't it suffice to require `width` and `height` to be set in absolute lengths? Wouldn't percentage-valued `x` and `y` be resolved in the coordinate system created by `width` and `height`?
