### ISSUE TITLE
Support the latest Unicode

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#905]
The various EPUB specifications uses an auto-updating reference to the latest version of Unicode so that changes can be immediately reflected in validation (same as is used in HTML, etc.).

This applies to the package document, META-INF files, file naming the in the container, media overlays.

(This may be a non-issue?)

**Comment by rdeltour** [comment]
I see nothing that needs to be updated in EPUBCheck code. We inherit Unicode support from Java.

Closing this as `wontfix`, feel free to reopen or keep commenting if you think something else should be done!
