### ISSUE TITLE
Foreign resources must be converted to core media types

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#906]
If a script presents a foreign resource in a content document, it has to transform the foreign resources into core media type or else provide a fallback.

(I don't see how this can be verified outside of a runtime environment, but adding it for review.)

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#confreq-cd-scripted-flbk

**Comment by rdeltour** [comment]
Suggesting to close this as `wontfix`, for the reasons explained in [this comment on #908](
https://github.com/w3c/epubcheck/issues/908#issuecomment-461237561).

Please upvote if you agree, or comment if you disagree!
