### ISSUE TITLE
The epubReadingSystem.layoutStyle property is deprecated

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#907]
Epubcheck should issue a message if epubReadingSystem.layoutStyle property is referenced by javascript.

(This may not be verifiable by epubcheck, but adding for review.)

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#app-ers-properties

**Comment by rdeltour** [comment]
Suggesting to close this as `wontfix`, for the reasons explained in [this comment on #908](
https://github.com/w3c/epubcheck/issues/908#issuecomment-461237561).

Please upvote if you agree, or comment if you disagree!
