### ISSUE TITLE
Maven tests failing for localization changes in 4.1.0

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#916]
Starting with PR #911 the maven tests are failing on my german system:

```
Results :

Failed tests:
  UtilMessage_LocalizationTest.ensureDefault:23 Default constructor should use the (host) default locale. expected:<en_DE> but was:<en_US>
  UtilMessage_LocalizationTest.ensureNullIsDefault:32 Null locale should use (host) default locale. expected:<en_DE> but was:<en_US>

Tests run: 1027, Failures: 2, Errors: 0, Skipped: 1
```

This is my maven setup:

```
mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Conte
nts/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"
```

Running the class `UtilMessage_LocalizationTest` in Eclipse as standalone JUnit tests, it works fine though.

**Comment by rdeltour** [comment]
I could reproduce by setting my OS version to a non-english locale.

I'm puzzled for two reasons:
- tests are launched with `-Duser.language=en`
- if you dive in the code, `Messages.getInstance()` uses `Locale.getDefault()`, like the expected result…

to be further investigated…

**Comment by tofi86** [comment]
> I'm puzzled for two reasons:
> 
>     * tests are launched with `-Duser.language=en`

Fter re-reading this: maybe this is the reason for weird `en_DE` locale! We should invoke it with additional `-Duser.country=US`, right?

wdyt, romain?

**Comment by rdeltour** [comment]
> After re-reading this: maybe this is the reason for weird `en_DE` locale! We should invoke it with additional `-Duser.country=US`, right?

Oh, I only realize about the weirdness of `en_DE` (sorry I had read too fast all that time 😄 ). Yeah, we should probably use `-Duser.country=US` too. Or even remove this setting altogether: tests should not rely on the environment's configuration; if a test checks the default locale, it should set it first with `Locale.setDefault`…

Anyways, it s/b a non-impacting detail, so we probably don't need a PR for that, maybe you could include it in #914?

**Comment by tofi86** [comment]
> Or even remove this setting altogether: tests should not rely on the environment's configuration; if a test checks the default locale, it should set it first with `Locale.setDefault`…

Yep, but we would need to fix a couple of tests first. This is the maven result without `-Duser.language=en` in maven-surefire-plugin arguments:

```
Results :

Failed tests:
  OCFCheckerTest.testInvalidLoremBasic30:346 null
  OCFCheckerTest.testInvalidLoremBindings30:365 null
  OCFCheckerTest.testInvalidLoremForeign30:386 null
  OCFCheckerTest.testInvalidLoremRNG30:423 null
  UtilMessage_LocalizationTest.ensureDefault:23 Default constructor should use the (host) default locale. expected:<en> but was:<en_US>
  UtilMessage_LocalizationTest.ensureNullIsDefault:32 Null locale should use (host) default locale. expected:<en> but was:<en_US>
  api_Test.EpubCheck_InputStream_Test:76 Expected: ERROR: EPUB/lorem.opf(13,63): Spine item with non-standard media-type 'font/opentype' has no fallback. Actual: ERROR: EPUB/lorem.opf(13,63): Ein 'spine'-Eintrag mit MimeType 'font/opentype' ist nicht erlaubt und enthält auch kein Fallback. expected:<...B/lorem.opf(13,63): [Spine item with non-standard media-type 'font/opentype' has no f]allback.> but was:<...B/lorem.opf(13,63): [Ein 'spine'-Eintrag mit MimeType 'font/opentype' ist nicht erlaubt und enthält auch kein F]allback.>
  api_Test.EpubCheck_PrintWriter_Test:48 Expected: ERROR: EPUB/lorem.opf(13,63): Spine item with non-standard media-type 'font/opentype' has no fallback. Actual: ERROR: EPUB/lorem.opf(13,63): Ein 'spine'-Eintrag mit MimeType 'font/opentype' ist nicht erlaubt und enthält auch kein Fallback. expected:<...B/lorem.opf(13,63): [Spine item with non-standard media-type 'font/opentype' has no f]allback.> but was:<...B/lorem.opf(13,63): [Ein 'spine'-Eintrag mit MimeType 'font/opentype' ist nicht erlaubt und enthält auch kein F]allback.>

Tests run: 1027, Failures: 8, Errors: 0, Skipped: 1
```

It fails because we have a couple of tests which have english strings in it's expected logs, etc.

Will open a new issue for fixing this.

----

> Yeah, we should probably use `-Duser.country=US` too.

This works fine, even without your patch. All tests pass with maven-surefire-plugin arguments `-Xmx1g -Duser.language=en -Duser.country=US`.

Will push this as a first fix directly to master.
