### ISSUE TITLE
Is "font-size:0;" an error?(4.1.0)

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/epubcheck#922]
I checked an existing EPUB 3.0.1 (reflowable) file by epubcheck 4.1.0, and got an error message.
It says "font-size: 0;" is an error, but is this correct?

 file: https://github.com/toshiakikoike/epub_file/tree/master/mymedia
(The file shows no error or warning on epubcheck 4.0.2)
 Error message: 
`
ERROR(CSS-020): /home/koike/Downloads/epub_file-master/mymedia.epub/OEBPS/styles/ebook_style.css(152,3): CSS font selector declaration uses unexpected font-size value '0'.`
`
ERROR(CSS-020): /home/koike/Downloads/epub_file-master/mymedia.epub/OEBPS/styles/ebook_style.css(158,3): CSS font selector declaration uses unexpected font-size value '0'.
    Check finished with errors
    Messages: 0 fatal / 2 errors / 0 warnings / 0 info
`

Error detected part in CSS:

    body.coverpage {
       text-align:center;
       margin:0;
       padding:   0;
       font-size: 0;
    }
    body.imgpage {
       text-align:center;
       margin:0;
       padding:   0;
       font-size: 0;
    }

I also checked another EPUB 3.0.1 file that contains the same CSS but is fixed-layout, and epubcheck 4.1.0 shows no error.
file: https://github.com/toshiakikoike/epub_file/tree/master/jp_comic_type
Used CSS:

    html,
    body {
       margin:    0;
       padding:   0;
       font-size: 0;
    }

**Comment by rdeltour** [comment]
Thanks for the report, I'll have a look. I'm adding that tentatively in the 4.1.1 milestone.

**Comment by dauwhe** [comment]
I think I've set `font-size: 0` in the past, trying to solve some weird problem which I can't remember. Zero is a perfectly valid length in CSS, so I don't see a spec justification for making this an error.

**Comment by ShinyaTakami** [comment]
We also found that our KADOKAWA's EPUBs are affected according to the same errors. We strongly hope that the modified new version will be released or this version will be dropped ASAP because some eBook stores in Japan reject EPUBs with epubcheck's errors. Until then, we have to encourage NOT to use 4.1.0 in Japan.

**Comment by murata2makoto** [comment]
Will this commit be included as part of the upcoming 4.2.0?

**Comment by rdeltour** [comment]
yes: it will in fact be integrated in 4.1.1 (stable release stream, to be released next week), which will then be merged in the 4.2.0 stream.
