### ISSUE TITLE
Mistaken warning in 4.1.0 as fallout from PR #738

### ISSUE THREAD

**Issue by robinwhittleton** [w3c/epubcheck#926]
I’m getting a new warning against my corpus after updating to epubcheck 4.1.0 (via mac homebrew):

```
WARNING(RSC-017): ./herman-melville_moby-dick.epub/epub/toc.xhtml(23,69): Warning while parsing file: Duplicate 'a' elements with the same 'epub:type' and 'href' attributes inside 'landmarks' nav element
```

I get two warnings for two landmarks entries. Removing one or more of the entries fixes the issue. They are:

```
<li>
	<a href="text/etymology.xhtml" epub:type="frontmatter preamble">Etymology</a>
</li>
<li>
	<a href="text/extracts.xhtml" epub:type="frontmatter preamble">Extracts</a>
</li>
```

Note that they have the same epub:type, but different hrefs. Changing the epub:type of one of them to an otherwise unused value (e.g. `introduction`) also fixes the issue.

I believe this is probably fallout from https://github.com/w3c/epubcheck/pull/738 but my xpath skills aren’t up to the job of diagnosing the issue. Is anyone able to have a look? The repo I’ve been testing against is http://github.com/standardebooks/herman-melville_moby-dick if that helps.

**Comment by tofi86** [comment]
Hi Robin,

thanks for your report. Indeed, that's a regression introduced with #738 where I didn't check the identical href attributes. Sorry for that.

Added to the 4.1.1 milestone.
