### ISSUE TITLE
Normalize the case of boolean attributes values

### ISSUE THREAD

**Issue by francofaa** [w3c/epubcheck#941]
epubcheck flags an error for the following attributes on element iframe: 

- allowFullScreen="allowFullScreen"
- allowfullscreen=""
- allow="fullscreen"

Error reads as follows: 

```
ERROR(RSC-005): ./Documents/Work/Validator/Testing Blank Files/S_EPUB_AllowFullScreen_ALL.epub/OEBPS/xhtml/jac_9781319048860_back.xhtml(18,106): Error while parsing file: attribute "allowFullScreen" not allowed here; expected attribute...
```

("..." omits the enumerated allowed attributes on iframe).

Markup from file here for testing: 

```
<iframe src="http://www.youtube.com/embed/xDMP3i36naA" allowFullScreen="allowFullScreen"></iframe>
<iframe src="http://www.youtube.com/embed/xDMP3i36naA" allowfullscreen=""></iframe>
<iframe src="http://www.youtube.com/embed/xDMP3i36naA" allow="fullscreen"></iframe>
```

HTML validator allows these, so I propose that this may be a bug in epubcheck.

**Comment by mattgarrish** [comment]
Are you using the alpha 4.2 release or 4.1.0? If 4.1.0, note that the attributes won't be available until EPUB 3.2 support is integrated.

I'm not able to reproduce this in the alpha, though, as both `allow` and `allowfullscreen` are defined for iframe in [embed.rnc](https://github.com/w3c/epubcheck/blob/next/v4.2.0/src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/embed.rnc).

**Comment by rdeltour** [comment]
I could reproduce on the  `next/4.2.0` branch. The issue only occurs however with the form `allowFullScreen="allowFullScreen"`; I suppose it will be the case for all the other boolean attributes. I suppose this is something checked at parsing time by the Nu Html Checker, in order to simplify their schemas.

I'll double-check and add either a parse-time check or fix the schemas where needed. Good catch @francofaa!

**Comment by mattgarrish** [comment]
> `allowFullScreen="allowFullScreen"`;

Isn't that because it has to be `allowfullscreen="allowfullscreen"`? That syntax works fine for me.

**Comment by rdeltour** [comment]
Oh no wait, I replied too fast. Actually the issue is that the attribute name is lower-case, it should be `allofullscreen` and not `allowFullScreen`…

**Comment by rdeltour** [comment]
In any case, boolean attributes accept values that are case-insensitive matches for their canonical name, so we should perform some case normalization at parsing time.
