### ISSUE TITLE
Localization plurals on EPUBCheck Summary

### ISSUE THREAD

**Issue by thiagoeec** [w3c/epubcheck#958]
Hi, everyone!

EPUCheck 4.1.0 introduced a new summary of errors, displayed at the bottom of the messages list.
One small problem: there are no rules for plurals defined.

Examples:

```
Check finished with errors
Messages: 0 fatal / 7 errors / 23 warnings / 0 info
```
```
Check finished with errors
Messages: 0 fatal / 1 errors / 0 warnings / 7 info
```
This affects english and localized messages.

**Comment by tofi86** [comment]
I implemented this feature with #655 / PR #742 and was aware of this. Although we didn't discuss it I thought it would be too much overhead regarding the localization stuff to implement plurals. I'm still of that opinion.

**Comment by rdeltour** [comment]
> I thought it would be too much overhead regarding the localization stuff to implement plurals

we're only talking about 8 new strings, rights? (2 for each issue type). I think it's not unreasonable, and user-friendliness should generally be favored to implementors' convenience 😊

**Comment by tofi86** [comment]
I agree Romain, go ahead!

I was just thinking of those poor guys and gals who need to grep on the result info to extract information and stuff...
