### ISSUE TITLE
change the Maven group ID to `org.w3c`

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#960]
Now that the project is owned by W3C and that IDPF is no more, the group ID used to distribute the Maven artifact for EPUBCheck should be updated from `org.idpf` to `org.w3c`.

**Comment by rdeltour** [comment]
Closed in 1c95c89

**Comment by tofi86** [comment]
Thanks Romain! 👏 

But what about the java code packages?

**Comment by rdeltour** [comment]
> what about the java code packages?

Changing these is a bit more involved, as it breaks the API. That's why I guess the current API is a mix of `com.adobe` and `org.idpf`.

But I agree that it's not ideal and the API would need a general cleanup, which will be the opportunity to move to `org.w3c.*` package names; this API revamp is planned for after v4.2.0! 🙂
