### ISSUE TITLE
suggestion: release announcements on the EPUBCheck mailing list

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#976]
I had a support request from a customer asking where EPUBCheck releases are being announced, besides twitter, since there is no option to subscribe.

I suggested to subscribe to the EPUBCheck mailing list, but there have been no release announcements so far.
Therefore I suggest to announce new releases also on the mailing list and point to the GitHub release page.

WDYT, @rdeltour?

**Comment by rdeltour** [comment]
Damn, I had totally forgot about the underused [`public-epubcheck` mailing list](https://lists.w3.org/Archives/Public/public-epubcheck/) 😅. We should definitely send the announcements there too, good catch!

For the record, from now on releases are also announced to:
- the [EPUB 3 Community Group mailing list](https://lists.w3.org/Archives/Public/public-epub3/)
- the [Publishing Business Group mailing list](https://lists.w3.org/Archives/Public/public-publishingbg/)
- on [Twitter](https://twitter.com/epubcheck)

Note also that it is possible to [watch a GitHub repository for releases only](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository).

**Comment by tofi86** [comment]
> Note also that it is possible to [watch a GitHub repository for releases only](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository).

Yeah, I also pointed her to that feature. However, you need a GitHub account for using this.

**Comment by rdeltour** [comment]
Announcement sent! 🎉

**Comment by laudrain** [comment]
W3C blog post published !
https://www.w3.org/blog/2019/02/epubcheck-4-2-be…elease-available/<https://www.w3.org/blog/2019/02/epubcheck-4-2-beta-release-available/>
Luc


De : Romain Deltour <notifications@github.com>
Répondre à : w3c/epubcheck <reply@reply.github.com>
Date : lundi 25 février 2019 à 17:43
À : w3c/epubcheck <epubcheck@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [w3c/epubcheck] suggestion: release announcements on the EPUBCheck mailing list (#976)


Announcement sent! 🎉
