### ISSUE TITLE
iframes and internal HTML documents

### ISSUE THREAD

**Issue by JayPanoz** [w3c/epubcheck#985]
Hi, Captain Edgecase here. :-)

Looks like some authoring tools have been using a hack to get their [HTML interactive widgets into EPUB3](https://github.com/readium/readium-js-viewer/issues/723) and get around the “XHTML restriction.” And [it’s been going for a very long time](https://forums.tumult.com/t/howto-get-hype-output-into-a-fixed-layout-epub-on-an-ipad/2457).

My worry is that it’s been implemented in a popular authoring tool (InDesign) for years so there are (valid EPUB) files using this hack in the wild.  As soon as InDesign does something, it can become widely used real quick. I can’t define “widely” though, I don’t have data. But this fix could break quite a handful of files. On the other hand, compatibility is really bad in real life so we’re probably talking about “semi-private”/“living in closed circuit” files.

Quoting @mattgarrish from [epub-revision issue](https://github.com/w3c/publ-epub-revision/issues/1238)

> It is a hack if the HTML document itself doesn't have a fallback, as that would be a hole in epubcheck. If an `iframe` references a foreign resource, which is what html is, it would have to provide a manifest fallback to be conforming. We already have that requirement here: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-foreign-restrictions-manifest

 If we’re talking about `fallback` attribute for the HTML `item`, no there isn’t any.

I corrected the [original sample so that it can pass EPUBCheck validation here](https://www.dropbox.com/s/ssuwv96sohco1sr/test__created-with-epubcheck.epub?dl=0) if you need a sample/test file.

**Comment by JayPanoz** [comment]
Addendum: forgot about that – sorry, tired… It may well be more widely used that one would expect actually. 

See [this tweet from Ken Jones](https://twitter.com/CircularKen/status/659387781714694144?s=20). As far as I can remember, the entire eprdctn-hour that day was all about leveraging existing web authoring/widget tools and using their HTML output in your EPUB3, using this trick.

**Comment by dauwhe** [comment]
Consensus from the EPUB 3 CG call today was to encourage EPUBCheck to allow this, as we do have working content out in the wild. There was not consensus on whether to change EPUB 3.2 itself to make the usage official.

**Comment by SeldomScene** [comment]
Great decision. Thanks for that.
