### ISSUE TITLE
epubcheck 4.2.0.-beta: SVG Xlink:href IRI 

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epubcheck#987]
epubcheck 4.2.0.-beta (and previous versions) indicate an error message for this SVG fragment:

"
&lt;image xlink:href="Titelseite.svg#v1" width="2000" height="1600" 
 preserveAspectRatio="xMidYMid slice"/&gt;
"
The IRI points to a view in the referenced file:
"
&lt;view id="v1" viewBox="0 600 2000 2000" /&gt;
"
The error message goes like this: "ERROR(RSC-009): SVG.epub/Inhalt/preserveAspectRatio.xhtml(192,40): A fragment identifier should not be used with an img src attribute."

Well, it is not an img element at all and it has no src attribute. ;-)
If it means the XLink:href, SVG notes about this, that the value has to be an IRI
https://www.w3.org/TR/SVG11/linking.html#IRIReference
therefore Titelseite.svg#v1 is ok.

Even for HTML5:img src I could not find any indication, that 'Titelseite.svg#v1'
should be a problem.

Simlar problem for XLink:href of the SVG:a element:
"
&lt;a xlink:href="#svgView(viewBox(1000,0,100,100))" xlink:title="Ansicht 2"&gt;
"
results in "ERROR(RSC-012): SVG.epub/Inhalt/view02.svg(18,75): Fragment identifier is not defined."

Because it is an svgView
https://www.w3.org/TR/SVG11/linking.html#SVGFragmentIdentifiers
this is ok as well, it references correctly an SVG fragment identifier.

**Comment by rdeltour** [comment]
Thanks for the report; this clearly looks like bugs.
